# netlify.toml
[build]
  publish = "build"

[[headers]]
  for = "/metadata/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/images/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
