#!/usr/bin/env bash
# Write the nginx real_ip allowlist from Cloudflare's current published ranges.
# A failed download does not keep or invent a previous list: trusting a stale
# range lets a former Cloudflare address spoof CF-Connecting-IP.
set -euo pipefail

out="${1:-/etc/nginx/snippets/cloudflare-real-ip.conf}"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

fetch() {
  local url="$1" dest="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fsS --max-time 20 "$url" > "$dest"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$dest" "$url"
  else
    echo "ops/nginx: neither curl nor wget is available" >&2
    exit 1
  fi
}

fetch "https://www.cloudflare.com/ips-v4" "$tmp/v4"
fetch "https://www.cloudflare.com/ips-v6" "$tmp/v6"

python3 - "$tmp/v4" "$tmp/v6" "$out" << 'PY'
import ipaddress
import sys
from pathlib import Path

v4, v6, out = sys.argv[1:]
lines = []
for path in (v4, v6):
    text = Path(path).read_text()
    rows = [row.strip() for row in text.splitlines() if row.strip()]
    if not rows:
        raise SystemExit(f"ops/nginx: empty range list {path}")
    for row in rows:
        try:
            ipaddress.ip_network(row)
        except ValueError:
            raise SystemExit(f"ops/nginx: refused non-CIDR line {row!r}")
        lines.append(f"set_real_ip_from {row};")
if len(lines) < 10:
    raise SystemExit("ops/nginx: range list is too short to be Cloudflare's")
import os
dest = Path(out)
dest.parent.mkdir(parents=True, exist_ok=True)
tmp = dest.with_name(dest.name + ".tmp")
tmp.write_text("# Generated by ops/nginx/refresh-cloudflare-ips.sh. Do not edit.\n" + "\n".join(lines) + "\n")
os.chmod(tmp, 0o644)
os.replace(tmp, dest)
print(f"ops/nginx: wrote {len(lines)} ranges to {out}")
PY
