#!/usr/bin/env python3
"""Regenerate frontend/src/lib/coreInstructions.ts from the committed IDL.

[AUDIT F-32] The wallet guard can only reject an instruction it can name. This
generator keeps the frontend's discriminator table in step with
aof_backend/src/idl/aof_core.json, which itself is regenerated by
`anchor build` and kept honest by scripts/check-idl-drift.py.

Usage: scripts/gen-core-instruction-table.py [--check]
  --check  exit 1 when the committed file is out of date (for CI).
"""
from __future__ import annotations
import argparse, json, os, sys

IDL = "aof_backend/src/idl/aof_core.json"
OUT = "frontend/src/lib/coreInstructions.ts"

# Instructions only the program authority may sign. A player wallet must never
# be asked to sign one of these.
AUTHORITY_ONLY = {
    "initialize", "set_fees", "set_paused", "set_resource_mints", "init_craft_economy",
    "set_craft_economy", "init_rarity_counter", "init_pack_config", "set_pack_config",
    "init_reroll_config", "set_reroll_config", "init_material_mints", "mint_resource",
    "mint_resource_once", "mint_tool", "migrate_tool", "pay_out", "pay_out_with_referral",
    "sweep_gas_fees", "adjust_player_capacity", "grant_season_xp", "init_season",
    "init_issuance_cap", "set_issuance_cap", "set_pending_authority", "accept_authority",
    "cancel_pending_authority", "set_mining_enabled", "init_vault_guard", "set_vault_guard",
    "set_supply_cap", "register_collector_mint", "revoke_collector_mint",
}

# Account names that denote the acting wallet.
ACTOR = {
    "user", "buyer", "seller", "maker", "caller", "cranker", "payer", "bidder",
    "recipient", "renter", "owner", "creator", "fulfiller",
}

HEADER = """/**
 * [AUDIT F-32] Generated table of aof-core instructions.
 *
 * Generated from aof_backend/src/idl/aof_core.json by
 * scripts/gen-core-instruction-table.py; re-run it after every `anchor build`
 * that changes the instruction set. The wallet guard uses this table to reject:
 *
 *   1. any instruction whose 8-byte discriminator is not recognised (an
 *      unrecognised aof-core call is never "probably fine");
 *   2. any authority-only instruction presented for the player to sign - a
 *      player wallet has no business signing `pay_out`, `mint_tool`,
 *      `set_paused` or any other authority instruction;
 *   3. any instruction whose account list length differs from the program's
 *      own context;
 *   4. any instruction where the connected wallet is not the signing actor.
 *      Every account slot the program declares as a signer and that names a
 *      party (user / buyer / maker / renter / ...) must be the wallet; that is
 *      what stops a tampered backend from putting the victim in the `seller`
 *      slot of a purchase. Slots the program does not require a signature for
 *      (auction_settle's `seller`, order matching's payees) are deliberately
 *      left alone, because those instructions are permissionless.
 *
 * Do not edit by hand: regenerate.
 */
export type CoreInstructionSpec = {
  readonly name: string;
  readonly discriminator: readonly number[];
  readonly accounts: readonly string[];
  /** Indexes of accounts that name a party (user / buyer / maker / renter ...). */
  readonly actorIndexes: readonly number[];
  /** Indexes of accounts the program requires a signature from. */
  readonly signerIndexes: readonly number[];
  /** Authority-signed only: a player wallet must never be asked to sign it. */
  readonly authorityOnly: boolean;
};

export const CORE_INSTRUCTIONS: readonly CoreInstructionSpec[] = [
"""

FOOTER = """];

const BY_DISCRIMINATOR: Map<string, CoreInstructionSpec> = new Map(
  CORE_INSTRUCTIONS.map((spec) => [spec.discriminator.join(","), spec]),
);

/** Resolve a raw instruction to its aof-core spec, or undefined when the
 * discriminator is unknown to this build of the program. */
export function coreInstructionSpec(
  programId: string,
  data: Uint8Array,
  coreProgramId: string,
): CoreInstructionSpec | undefined {
  if (programId !== coreProgramId || data.length < 8) return undefined;
  return BY_DISCRIMINATOR.get(Array.from(data.slice(0, 8)).join(","));
}
"""


def render() -> str:
    idl = json.load(open(IDL, encoding="utf-8"))
    lines = [HEADER.rstrip("\n")]
    for ix in idl["instructions"]:
        names = [a["name"] for a in ix["accounts"]]
        actors = [i for i, n in enumerate(names) if n in ACTOR]
        signers = [i for i, a in enumerate(ix["accounts"]) if a.get("signer")]
        lines.append("  {")
        lines.append(f'    name: "{ix["name"]}",')
        lines.append("    discriminator: [" + ", ".join(str(b) for b in ix["discriminator"]) + "],")
        lines.append("    accounts: [" + ", ".join(f'"{n}"' for n in names) + "],")
        lines.append("    actorIndexes: [" + ", ".join(str(i) for i in actors) + "],")
        lines.append("    signerIndexes: [" + ", ".join(str(i) for i in signers) + "],")
        lines.append(f'    authorityOnly: {"true" if ix["name"] in AUTHORITY_ONLY else "false"},')
        lines.append("  },")
    return "\n".join(lines) + "\n\n" + FOOTER


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print(f"{OUT} is out of date; run scripts/gen-core-instruction-table.py")
            return 1
        print(f"{OUT} is up to date")
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"wrote {OUT} ({len(json.load(open(IDL))['instructions'])} instructions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
