#!/usr/bin/env python3
"""
Regenerate programs/aof-quests/src/vrf.rs from aof-core/src/vrf.rs.

[F-06] Both programs CPI Switchboard On-Demand with the same audited code. The
crates are independent (a shared crate would change the `--locked` dependency
graph), so aof-quests carries a generated copy that differs only in:
  * the error type (QuestError aliased as AofError);
  * the seed / window constants, which aof-core keeps in constants.rs;
  * the tool-settlement rent helper, which only aof-core needs.
tests/readiness/vrf.test.cjs fails when the copy drifts.

    python3 scripts/sync-quests-vrf.py           # rewrite the copy
    python3 scripts/sync-quests-vrf.py --check   # exit 1 if it is stale
"""
from __future__ import annotations

import sys

CORE = "aof-core/src/vrf.rs"
QUESTS = "programs/aof-quests/src/vrf.rs"

HEADER_FROM = """//! [F-06 / SECURITY_CHECKLIST #36 #37] Production randomness: a future slot
//! hash, settled by this program."""
HEADER_TO = """//! [F-06] Switchboard On-Demand for the Drum of Luck — a copy of
//! aof-core/src/vrf.rs generated by scripts/sync-quests-vrf.py (the crates are
//! independent; a shared crate would change the `--locked` dependency graph).
//! tests/readiness/vrf.test.cjs keeps the two copies identical apart from the
//! error type and the seed constants.
//!
//! Original documentation (aof-core):"""
IMPORTS_FROM = "use crate::errors::AofError;\nuse crate::state::VrfSlot;"
IMPORTS_TO = """use crate::errors::QuestError as AofError;
use crate::state::VrfSlot;

pub const VRF_AUTHORITY_SEED: &[u8] = b"vrf_authority";
pub const VRF_SLOT_SEED: &[u8] = b"vrf_slot";
pub const VRF_RANDOMNESS_SEED: &[u8] = b"vrf_randomness";
/// Same reveal window / refund threshold as aof-core (~3 min at 400 ms slots).
pub const VRF_REFUND_AFTER_SLOTS: u64 = 432;
/// SlotHashes sysvar.
pub const SLOT_HASHES_ID: Pubkey = anchor_lang::solana_program::sysvar::slot_hashes::ID;"""


def render(core: str) -> str:
    for needle in (HEADER_FROM, IMPORTS_FROM):
        if needle not in core:
            raise SystemExit(f"{CORE}: expected block not found:\n{needle}")
    out = core.replace(HEADER_FROM, HEADER_TO).replace(IMPORTS_FROM, IMPORTS_TO)
    out = out.replace("crate::randomness::SLOT_HASHES_ID", "SLOT_HASHES_ID")
    for name in ("VRF_AUTHORITY_SEED", "VRF_RANDOMNESS_SEED", "VRF_REFUND_AFTER_SLOTS"):
        out = out.replace(f"crate::constants::{name}", name)
    cut = out.find("/// Maximum rent the settler")
    if cut >= 0:
        out = out[:cut].rstrip("\n") + "\n"
    if "crate::constants" in out or "crate::randomness" in out:
        raise SystemExit("unresolved aof-core-only path left in the quests copy")
    return out


def main() -> int:
    text = render(open(CORE, encoding="utf-8").read())
    if "--check" in sys.argv:
        current = open(QUESTS, encoding="utf-8").read()
        if current != text:
            print(f"{QUESTS} is stale: run python3 scripts/sync-quests-vrf.py")
            return 1
        print(f"{QUESTS} is up to date")
        return 0
    open(QUESTS, "w", encoding="utf-8").write(text)
    print(f"wrote {QUESTS}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
