#!/usr/bin/env python3
"""
Generate the PostgreSQL Prisma schema + baseline migration from the SQLite ones.

Prisma cannot switch `datasource.provider` from an env var, and a migrations
directory is provider-specific (migration_lock.toml). Instead of maintaining
two schemas by hand — which is how they drift — the PostgreSQL variants are
DERIVED from the SQLite sources by this script and checked in:

    prisma/schema.prisma                      (source, sqlite)
    prisma/migrations/*/migration.sql         (source, sqlite)
        │  scripts/gen-postgres-schema.py
        ▼
    prisma/postgres/schema.prisma             (generated)
    prisma/postgres/migrations/0_baseline/    (generated: all sqlite migrations squashed)
    prisma/postgres/migrations/migration_lock.toml

CI runs this script with --check and fails if the committed generated files
are stale. New SQLite migrations therefore always land in the PG baseline too.
Once production is on PostgreSQL and SQLite is dev-only, the direction can be
flipped (or SQLite dropped) — see docs/POSTGRES_MIGRATION.md.

Translation rules (SQLite DDL → PostgreSQL DDL):
    DATETIME            -> TIMESTAMP(3)          (Prisma's PG mapping for DateTime)
    REAL                -> DOUBLE PRECISION      (Float)
    BIGINT / INTEGER / TEXT / BOOLEAN            unchanged
    DEFAULT CURRENT_TIMESTAMP                     unchanged
    PRAGMA ...          -> dropped
    boolean literals true/false                   unchanged (valid in PG)
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SQLITE_SCHEMA = ROOT / "prisma" / "schema.prisma"
SQLITE_MIGRATIONS = ROOT / "prisma" / "migrations"
PG_DIR = ROOT / "prisma" / "postgres"
PG_SCHEMA = PG_DIR / "schema.prisma"
PG_MIGRATIONS = PG_DIR / "migrations"
PG_BASELINE = PG_MIGRATIONS / "0_baseline" / "migration.sql"
PG_LOCK = PG_MIGRATIONS / "migration_lock.toml"

HEADER = "// GENERATED by scripts/gen-postgres-schema.py from prisma/schema.prisma — do not edit.\n"


def gen_schema(src: str) -> str:
    out = src.replace('provider = "sqlite"', 'provider = "postgresql"', 1)
    if out == src:
        sys.exit("sqlite provider line not found in schema.prisma")
    # Client output stays default; both providers generate into node_modules/.prisma
    # only one at a time, selected by which schema `prisma generate` is run with.
    return HEADER + out


def translate_sql(sql: str) -> str:
    lines = []
    for line in sql.splitlines():
        if line.strip().upper().startswith("PRAGMA"):
            continue
        line = re.sub(r"\bDATETIME\b", "TIMESTAMP(3)", line)
        line = re.sub(r"\bREAL\b", "DOUBLE PRECISION", line)
        lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def gen_baseline() -> str:
    parts = ["-- GENERATED by scripts/gen-postgres-schema.py: all SQLite migrations squashed into one PostgreSQL baseline.\n"]
    for mig in sorted(p for p in SQLITE_MIGRATIONS.iterdir() if p.is_dir()):
        sql = (mig / "migration.sql").read_text()
        parts.append(f"\n-- ===== from {mig.name} =====\n")
        parts.append(translate_sql(sql))
    return "".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if committed generated files are stale")
    args = ap.parse_args()

    expected = {
        PG_SCHEMA: gen_schema(SQLITE_SCHEMA.read_text()),
        PG_BASELINE: gen_baseline(),
        PG_LOCK: '# Please do not edit this file manually\n# It should be added in your version-control system (i.e. Git)\nprovider = "postgresql"\n',
    }
    stale = [p for p, content in expected.items() if not p.exists() or p.read_text() != content]
    if args.check:
        if stale:
            print("stale generated PostgreSQL files (run scripts/gen-postgres-schema.py):", *[str(p.relative_to(ROOT)) for p in stale], sep="\n  ")
            return 1
        print("postgres schema/baseline up to date")
        return 0
    for p, content in expected.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        print("wrote", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
