//! [F-06] Switchboard On-Demand for the Drum of Luck — a copy of
//! aof-core/src/vrf.rs generated by scripts/sync-quests-vrf.py (the crates are
//! independent; a shared crate would change the `--locked` dependency graph).
//! tests/readiness/vrf.test.cjs keeps the two copies identical apart from the
//! error type and the seed constants.
//!
//! Original documentation (aof-core):
//!
//! Why program-owned: Switchboard lets ONLY the `authority` of a randomness
//! account commit or reveal it. If the player owned the account, the player
//! could look up the oracle's answer off-chain and simply not reveal a bad
//! roll; if the backend owned it, the house could do the same to a jackpot.
//! Here the authority is the PDA [VRF_AUTHORITY_SEED] of this program, so:
//!
//!  1. commit  — the mechanic's commit instruction takes the payment, snapshots
//!     every outcome parameter and CPIs `randomness_commit` on a free pool slot
//!     in the same instruction, locking the slot to the commit PDA. The seed is
//!     fixed at the moment the stake is locked; nobody can re-seed later.
//!  2. reveal  — permissionless. Whoever brings the oracle's signed value (the
//!     backend crank, the player, anyone) makes this program CPI
//!     `randomness_reveal` (signed by the PDA) and the outcome is settled in
//!     the same instruction. A settlement nobody can block leaves nothing to
//!     withhold.
//!  3. refund  — only from `commit_slot + VRF_REFUND_AFTER_SLOTS`, the same
//!     slot the reveal closes. "Reveal" and "refund" are never open together.
//!
//! No Switchboard crate is linked: the workspace builds `--locked` on
//! solana-program 1.18, and the interface is small. Account order, signer /
//! writable flags and discriminators below are pinned to the published
//! sb_on_demand IDL (vendored in docs/vendor/switchboard_on_demand_randomness.json)
//! and checked by host tests and tests/readiness/vrf.test.cjs.
use anchor_lang::prelude::*;
use anchor_lang::solana_program::hash::hashv;
use anchor_lang::solana_program::instruction::{AccountMeta, Instruction};
use anchor_lang::solana_program::program::invoke_signed;
use crate::errors::QuestError as AofError;
use crate::state::VrfSlot;

pub const VRF_AUTHORITY_SEED: &[u8] = b"vrf_authority";
pub const VRF_SLOT_SEED: &[u8] = b"vrf_slot";
pub const VRF_RANDOMNESS_SEED: &[u8] = b"vrf_randomness";
/// Same reveal window / refund threshold as aof-core (~2 h at 400 ms slots).
pub const VRF_REFUND_AFTER_SLOTS: u64 = 18_000;
/// SlotHashes sysvar.
pub const SLOT_HASHES_ID: Pubkey = anchor_lang::solana_program::sysvar::slot_hashes::ID;

/// SBondMDrcV3K4kxZR1HNVT7osZxAHVHgYXL5Ze1oMUv
pub const SWITCHBOARD_ON_DEMAND_MAINNET: Pubkey = Pubkey::new_from_array([
    6, 115, 189, 70, 242, 228, 126, 4, 241, 43, 217, 47, 183, 49, 150, 142, 205, 157, 151, 87, 194, 116, 218,
    135, 71, 111, 70, 92, 4, 12, 101, 115,
]);
/// Aio4gaXjXzJNVLtzwtNVmSqGKpANtXhybbkhtAC94ji2
pub const SWITCHBOARD_ON_DEMAND_DEVNET: Pubkey = Pubkey::new_from_array([
    144, 110, 20, 100, 197, 248, 183, 99, 60, 192, 90, 66, 76, 221, 179, 174, 205, 109, 171, 184, 174, 199, 71,
    188, 79, 62, 17, 48, 30, 64, 99, 203,
]);
/// A43DyUGA7s8eXPxqEjJY6EBu1KKbNgfxF8h17VAHn13w — Switchboard's official
/// mainnet queue (`ON_DEMAND_MAINNET_QUEUE` in @switchboard-xyz/on-demand).
pub const SWITCHBOARD_QUEUE_MAINNET: Pubkey = Pubkey::new_from_array([
    134, 128, 112, 104, 67, 47, 24, 106, 20, 124, 240, 177, 58, 48, 6, 125, 56, 98, 4, 234, 157, 108, 139, 4,
    116, 58, 194, 239, 1, 11, 7, 82,
]);
/// EYiAmGSdsQTuCw413V5BzaruWuCCSDgTPtBGvLkXHbe7 — official devnet queue.
pub const SWITCHBOARD_QUEUE_DEVNET: Pubkey = Pubkey::new_from_array([
    201, 71, 123, 251, 95, 241, 1, 40, 89, 243, 54, 207, 152, 114, 86, 128, 231, 112, 91, 162, 171, 236, 225,
    113, 136, 207, 178, 140, 166, 108, 165, 176,
]);
/// AddressLookupTab1e1111111111111111111111111
pub const ADDRESS_LOOKUP_TABLE_PROGRAM_ID: Pubkey = Pubkey::new_from_array([
    2, 119, 166, 175, 151, 51, 155, 122, 200, 141, 24, 146, 201, 4, 70, 245, 0, 2, 48, 146, 102, 246, 46, 83,
    193, 24, 36, 73, 130, 0, 0, 0,
]);

/// 7Gs9n5FQMeC9XcEhg281bRZ6VHRrCvqp5Yq1j78HkvNa — PDA ["STATE"] of the mainnet program.
pub const SWITCHBOARD_STATE_MAINNET: Pubkey = Pubkey::new_from_array([
    93, 54, 138, 60, 92, 210, 176, 193, 224, 51, 232, 253, 41, 49, 126, 85, 141, 212, 114, 100, 119, 144, 75, 58,
    185, 15, 79, 254, 150, 22, 244, 239,
]);
/// 4UFmCebEmzESoDTtHrmaftXj7YAsAH4HMios3yMWyVUT — PDA ["STATE"] of the devnet program.
pub const SWITCHBOARD_STATE_DEVNET: Pubkey = Pubkey::new_from_array([
    51, 142, 111, 37, 109, 103, 148, 27, 163, 204, 109, 58, 101, 219, 2, 155, 143, 187, 141, 6, 160, 69, 235, 220,
    140, 203, 254, 140, 100, 79, 207, 56,
]);

/// The only Switchboard program and queue this build trusts
/// (`--features devnet` for devnet). A randomness account on any other queue
/// would be served by oracles of the queue owner's choosing.
#[cfg(feature = "devnet")]
pub const SWITCHBOARD_PROGRAM_ID: Pubkey = SWITCHBOARD_ON_DEMAND_DEVNET;
#[cfg(not(feature = "devnet"))]
pub const SWITCHBOARD_PROGRAM_ID: Pubkey = SWITCHBOARD_ON_DEMAND_MAINNET;
#[cfg(feature = "devnet")]
pub const SWITCHBOARD_QUEUE: Pubkey = SWITCHBOARD_QUEUE_DEVNET;
#[cfg(not(feature = "devnet"))]
pub const SWITCHBOARD_QUEUE: Pubkey = SWITCHBOARD_QUEUE_MAINNET;
#[cfg(feature = "devnet")]
pub const SWITCHBOARD_STATE: Pubkey = SWITCHBOARD_STATE_DEVNET;
#[cfg(not(feature = "devnet"))]
pub const SWITCHBOARD_STATE: Pubkey = SWITCHBOARD_STATE_MAINNET;

/// `Program<'info, SwitchboardOnDemand>`: key AND executable flag checked by Anchor.
#[derive(Clone)]
pub struct SwitchboardOnDemand;
impl anchor_lang::Id for SwitchboardOnDemand {
    fn id() -> Pubkey {
        SWITCHBOARD_PROGRAM_ID
    }
}

/// `Program<'info, AddressLookupTableProgram>` (Switchboard creates a LUT per account).
#[derive(Clone)]
pub struct AddressLookupTableProgram;
impl anchor_lang::Id for AddressLookupTableProgram {
    fn id() -> Pubkey {
        ADDRESS_LOOKUP_TABLE_PROGRAM_ID
    }
}

// Addresses of the Switchboard accounts a CPI passes through. Switchboard
// validates them itself; binding them here as well means a wrong account fails
// in this program's account validation, attributed to its field name.

/// Oracle stats PDA ["OracleRandomnessStats", oracle] of the Switchboard program.
pub fn stats_address(oracle: &Pubkey) -> Pubkey {
    Pubkey::find_program_address(&[b"OracleRandomnessStats", oracle.as_ref()], &SWITCHBOARD_PROGRAM_ID).0
}

/// wSOL reward escrow of a randomness account: its associated token account.
pub fn reward_escrow_address(randomness: &Pubkey) -> Pubkey {
    anchor_spl::associated_token::get_associated_token_address(randomness, &anchor_spl::token::spl_token::native_mint::ID)
}

/// Switchboard LUT signer PDA ["LutSigner", randomness].
pub fn lut_signer_address(randomness: &Pubkey) -> Pubkey {
    Pubkey::find_program_address(&[b"LutSigner", randomness.as_ref()], &SWITCHBOARD_PROGRAM_ID).0
}

/// Address Lookup Table address for (authority, recent_slot).
pub fn lut_address(lut_signer: &Pubkey, recent_slot: u64) -> Pubkey {
    Pubkey::find_program_address(&[lut_signer.as_ref(), &recent_slot.to_le_bytes()], &ADDRESS_LOOKUP_TABLE_PROGRAM_ID).0
}

/// The oracle Switchboard assigned to `randomness` at commit (a reveal must
/// bring exactly that oracle's signature).
pub fn assigned_oracle_is(randomness: &AccountInfo, oracle: &Pubkey) -> bool {
    load_randomness(randomness).map(|r| r.oracle == *oracle).unwrap_or(false)
}

/// sha256("account:RandomnessAccountData")[..8]
pub const RANDOMNESS_ACCOUNT_DISCRIMINATOR: [u8; 8] = [10, 66, 229, 135, 220, 239, 217, 114];
/// sha256("global:randomness_init")[..8]
pub const RANDOMNESS_INIT_IX_DISCRIMINATOR: [u8; 8] = [9, 9, 204, 33, 50, 116, 113, 15];
/// sha256("global:randomness_commit")[..8]
pub const RANDOMNESS_COMMIT_IX_DISCRIMINATOR: [u8; 8] = [52, 170, 152, 201, 179, 133, 242, 141];
/// sha256("global:randomness_reveal")[..8]
pub const RANDOMNESS_REVEAL_IX_DISCRIMINATOR: [u8; 8] = [197, 181, 187, 10, 30, 58, 20, 73];
/// Minimum account size we parse: 8-byte discriminator + the 400-byte prefix
/// every published layout shares (the current program allocates 480 bytes).
pub const RANDOMNESS_ACCOUNT_LEN: usize = 408;
// Field offsets (RandomnessAccountData is #[repr(C)], Pod).
const AUTHORITY_AT: usize = 8;
const QUEUE_AT: usize = 40;
const SEED_SLOT_AT: usize = 104;
const ORACLE_AT: usize = 112;
const REVEAL_SLOT_AT: usize = 144;
const VALUE_AT: usize = 152;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Randomness {
    pub authority: Pubkey,
    pub queue: Pubkey,
    pub seed_slot: u64,
    pub oracle: Pubkey,
    pub reveal_slot: u64,
    pub value: [u8; 32],
}

fn read_u64(data: &[u8], at: usize) -> u64 {
    let mut bytes = [0u8; 8];
    bytes.copy_from_slice(&data[at..at + 8]);
    u64::from_le_bytes(bytes)
}

fn read_key(data: &[u8], at: usize) -> Pubkey {
    let mut bytes = [0u8; 32];
    bytes.copy_from_slice(&data[at..at + 32]);
    Pubkey::new_from_array(bytes)
}

/// Decode randomness account bytes (discriminator and size checked).
pub fn parse_randomness(data: &[u8]) -> Result<Randomness> {
    require!(data.len() >= RANDOMNESS_ACCOUNT_LEN, AofError::InvalidRandomnessAccount);
    require!(data[..8] == RANDOMNESS_ACCOUNT_DISCRIMINATOR, AofError::InvalidRandomnessAccount);
    let mut value = [0u8; 32];
    value.copy_from_slice(&data[VALUE_AT..VALUE_AT + 32]);
    Ok(Randomness {
        authority: read_key(data, AUTHORITY_AT),
        queue: read_key(data, QUEUE_AT),
        seed_slot: read_u64(data, SEED_SLOT_AT),
        oracle: read_key(data, ORACLE_AT),
        reveal_slot: read_u64(data, REVEAL_SLOT_AT),
        value,
    })
}

/// Load a randomness account owned by the trusted Switchboard program.
pub fn load_randomness(account: &AccountInfo) -> Result<Randomness> {
    require_keys_eq!(*account.owner, SWITCHBOARD_PROGRAM_ID, AofError::InvalidRandomnessAccount);
    let data = account.try_borrow_data()?;
    parse_randomness(&data)
}

/// The oracle-signed reveal exactly as the Switchboard gateway returns it and
/// `randomness_reveal` consumes it (`RandomnessRevealParams`). This program
/// never trusts these bytes itself: Switchboard verifies the enclave signature
/// before writing the value, and the value is then read back from the account.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct VrfRevealParams {
    pub signature: [u8; 64],
    pub recovery_id: u8,
    pub value: [u8; 32],
}

// ---------------------------------------------------------------- raw CPI
//
// The ONE audited exception to "CPIs use typed Anchor helpers": Switchboard
// ships no Anchor CPI crate usable on this toolchain. Every builder targets
// SWITCHBOARD_PROGRAM_ID only and pins the IDL account order and flags.

/// `randomness_init` (params: recent_slot: u64).
pub fn init_instruction(
    randomness: Pubkey,
    reward_escrow: Pubkey,
    authority: Pubkey,
    queue: Pubkey,
    payer: Pubkey,
    program_state: Pubkey,
    lut_signer: Pubkey,
    lut: Pubkey,
    recent_slot: u64,
) -> Instruction {
    let mut data = RANDOMNESS_INIT_IX_DISCRIMINATOR.to_vec();
    data.extend_from_slice(&recent_slot.to_le_bytes());
    Instruction {
        program_id: SWITCHBOARD_PROGRAM_ID,
        accounts: vec![
            AccountMeta::new(randomness, true),
            AccountMeta::new(reward_escrow, false),
            AccountMeta::new_readonly(authority, true),
            AccountMeta::new(queue, false),
            AccountMeta::new(payer, true),
            AccountMeta::new_readonly(anchor_lang::solana_program::system_program::ID, false),
            AccountMeta::new_readonly(anchor_spl::token::ID, false),
            AccountMeta::new_readonly(anchor_spl::associated_token::ID, false),
            AccountMeta::new_readonly(anchor_spl::token::spl_token::native_mint::ID, false),
            AccountMeta::new_readonly(program_state, false),
            AccountMeta::new_readonly(lut_signer, false),
            AccountMeta::new(lut, false),
            AccountMeta::new_readonly(ADDRESS_LOOKUP_TABLE_PROGRAM_ID, false),
        ],
        data,
    }
}

/// `randomness_commit` (params: empty struct -> discriminator only).
pub fn commit_instruction(randomness: Pubkey, queue: Pubkey, oracle: Pubkey, authority: Pubkey) -> Instruction {
    Instruction {
        program_id: SWITCHBOARD_PROGRAM_ID,
        accounts: vec![
            AccountMeta::new(randomness, false),
            AccountMeta::new_readonly(queue, false),
            AccountMeta::new(oracle, false),
            AccountMeta::new_readonly(SLOT_HASHES_ID, false),
            AccountMeta::new_readonly(authority, true),
        ],
        data: RANDOMNESS_COMMIT_IX_DISCRIMINATOR.to_vec(),
    }
}

/// `randomness_reveal` (params: signature [u8;64], recovery_id u8, value [u8;32]).
#[allow(clippy::too_many_arguments)]
pub fn reveal_instruction(
    randomness: Pubkey,
    oracle: Pubkey,
    queue: Pubkey,
    stats: Pubkey,
    authority: Pubkey,
    payer: Pubkey,
    reward_escrow: Pubkey,
    program_state: Pubkey,
    params: &VrfRevealParams,
) -> Instruction {
    let mut data = RANDOMNESS_REVEAL_IX_DISCRIMINATOR.to_vec();
    data.extend_from_slice(&params.signature);
    data.push(params.recovery_id);
    data.extend_from_slice(&params.value);
    Instruction {
        program_id: SWITCHBOARD_PROGRAM_ID,
        accounts: vec![
            AccountMeta::new(randomness, false),
            AccountMeta::new_readonly(oracle, false),
            AccountMeta::new_readonly(queue, false),
            AccountMeta::new(stats, false),
            AccountMeta::new_readonly(authority, true),
            AccountMeta::new(payer, true),
            AccountMeta::new_readonly(SLOT_HASHES_ID, false),
            AccountMeta::new_readonly(anchor_lang::solana_program::system_program::ID, false),
            AccountMeta::new(reward_escrow, false),
            AccountMeta::new_readonly(anchor_spl::token::ID, false),
            AccountMeta::new_readonly(anchor_spl::token::spl_token::native_mint::ID, false),
            AccountMeta::new_readonly(program_state, false),
        ],
        data,
    }
}

/// Accounts of `vrf_pool_add`'s `randomness_init` CPI.
pub struct InitAccounts<'info> {
    pub switchboard_program: AccountInfo<'info>,
    pub randomness: AccountInfo<'info>,
    pub reward_escrow: AccountInfo<'info>,
    pub vrf_authority: AccountInfo<'info>,
    pub queue: AccountInfo<'info>,
    pub payer: AccountInfo<'info>,
    pub system_program: AccountInfo<'info>,
    pub token_program: AccountInfo<'info>,
    pub associated_token_program: AccountInfo<'info>,
    pub wrapped_sol_mint: AccountInfo<'info>,
    pub program_state: AccountInfo<'info>,
    pub lut_signer: AccountInfo<'info>,
    pub lut: AccountInfo<'info>,
    pub address_lookup_table_program: AccountInfo<'info>,
}

/// Accounts of a `randomness_commit` CPI.
pub struct CommitAccounts<'info> {
    pub switchboard_program: AccountInfo<'info>,
    pub randomness: AccountInfo<'info>,
    pub queue: AccountInfo<'info>,
    pub oracle: AccountInfo<'info>,
    pub recent_slothashes: AccountInfo<'info>,
    pub vrf_authority: AccountInfo<'info>,
}

/// Accounts of a `randomness_reveal` CPI.
pub struct RevealAccounts<'info> {
    pub switchboard_program: AccountInfo<'info>,
    pub randomness: AccountInfo<'info>,
    pub oracle: AccountInfo<'info>,
    pub queue: AccountInfo<'info>,
    pub stats: AccountInfo<'info>,
    pub vrf_authority: AccountInfo<'info>,
    pub payer: AccountInfo<'info>,
    pub recent_slothashes: AccountInfo<'info>,
    pub system_program: AccountInfo<'info>,
    pub reward_escrow: AccountInfo<'info>,
    pub token_program: AccountInfo<'info>,
    pub wrapped_sol_mint: AccountInfo<'info>,
    pub program_state: AccountInfo<'info>,
}

/// Create pool randomness account #index with this program's PDA as its
/// authority. Both the randomness address and the authority are PDAs, so the
/// CPI is signed with both seed sets.
pub fn cpi_init(a: &InitAccounts, index: u32, randomness_bump: u8, authority_bump: u8, recent_slot: u64) -> Result<()> {
    require_keys_eq!(a.switchboard_program.key(), SWITCHBOARD_PROGRAM_ID, AofError::InvalidRandomnessAccount);
    let ix = init_instruction(
        a.randomness.key(),
        a.reward_escrow.key(),
        a.vrf_authority.key(),
        a.queue.key(),
        a.payer.key(),
        a.program_state.key(),
        a.lut_signer.key(),
        a.lut.key(),
        recent_slot,
    );
    let index_le = index.to_le_bytes();
    invoke_signed(
        &ix,
        &[
            a.randomness.clone(),
            a.reward_escrow.clone(),
            a.vrf_authority.clone(),
            a.queue.clone(),
            a.payer.clone(),
            a.system_program.clone(),
            a.token_program.clone(),
            a.associated_token_program.clone(),
            a.wrapped_sol_mint.clone(),
            a.program_state.clone(),
            a.lut_signer.clone(),
            a.lut.clone(),
            a.address_lookup_table_program.clone(),
            a.switchboard_program.clone(),
        ],
        &[
            &[VRF_AUTHORITY_SEED, &[authority_bump]],
            &[VRF_RANDOMNESS_SEED, &index_le, &[randomness_bump]],
        ],
    )?;
    Ok(())
}

fn cpi_commit(a: &CommitAccounts, authority_bump: u8) -> Result<()> {
    require_keys_eq!(a.switchboard_program.key(), SWITCHBOARD_PROGRAM_ID, AofError::InvalidRandomnessAccount);
    let ix = commit_instruction(a.randomness.key(), a.queue.key(), a.oracle.key(), a.vrf_authority.key());
    invoke_signed(
        &ix,
        &[
            a.randomness.clone(),
            a.queue.clone(),
            a.oracle.clone(),
            a.recent_slothashes.clone(),
            a.vrf_authority.clone(),
            a.switchboard_program.clone(),
        ],
        &[&[VRF_AUTHORITY_SEED, &[authority_bump]]],
    )?;
    Ok(())
}

fn cpi_reveal(a: &RevealAccounts, params: &VrfRevealParams, authority_bump: u8) -> Result<()> {
    require_keys_eq!(a.switchboard_program.key(), SWITCHBOARD_PROGRAM_ID, AofError::InvalidRandomnessAccount);
    let ix = reveal_instruction(
        a.randomness.key(),
        a.oracle.key(),
        a.queue.key(),
        a.stats.key(),
        a.vrf_authority.key(),
        a.payer.key(),
        a.reward_escrow.key(),
        a.program_state.key(),
        params,
    );
    invoke_signed(
        &ix,
        &[
            a.randomness.clone(),
            a.oracle.clone(),
            a.queue.clone(),
            a.stats.clone(),
            a.vrf_authority.clone(),
            a.payer.clone(),
            a.recent_slothashes.clone(),
            a.system_program.clone(),
            a.reward_escrow.clone(),
            a.token_program.clone(),
            a.wrapped_sol_mint.clone(),
            a.program_state.clone(),
            a.switchboard_program.clone(),
        ],
        &[&[VRF_AUTHORITY_SEED, &[authority_bump]]],
    )?;
    Ok(())
}

// ---------------------------------------------------------------- lifecycle

/// Commit: lock a free pool slot to `holder` (the commit PDA) and have
/// Switchboard seed it with the previous slot's hash. Returns the seed slot
/// the commit must store.
pub fn commit(slot: &mut VrfSlot, holder: Pubkey, a: &CommitAccounts, authority_bump: u8, clock_slot: u64) -> Result<u64> {
    require!(!slot.retired, AofError::VrfSlotRetired);
    require_keys_eq!(slot.lock, Pubkey::default(), AofError::VrfSlotBusy);
    require_keys_eq!(a.randomness.key(), slot.randomness, AofError::InvalidRandomnessAccount);
    require_keys_eq!(a.queue.key(), SWITCHBOARD_QUEUE, AofError::InvalidRandomnessAccount);
    let before = load_randomness(&a.randomness)?;
    require_keys_eq!(before.authority, a.vrf_authority.key(), AofError::InvalidRandomnessAccount);
    require_keys_eq!(before.queue, SWITCHBOARD_QUEUE, AofError::InvalidRandomnessAccount);

    cpi_commit(a, authority_bump)?;

    let after = load_randomness(&a.randomness)?;
    // Switchboard seeds with the newest hash in SlotHashes: the previous slot.
    require!(clock_slot > 0 && after.seed_slot == clock_slot - 1, AofError::RandomnessNotFresh);
    slot.lock = holder;
    slot.locked_at_slot = clock_slot;
    slot.commits = slot.commits.saturating_add(1);
    Ok(after.seed_slot)
}

/// Reveal: only the lock holder, only inside the reveal window, and the value
/// is read back from the account Switchboard just wrote. Frees the slot.
#[allow(clippy::too_many_arguments)]
pub fn reveal(
    slot: &mut VrfSlot,
    holder: &Pubkey,
    committed_randomness: &Pubkey,
    committed_seed_slot: u64,
    commit_slot: u64,
    a: &RevealAccounts,
    params: &VrfRevealParams,
    authority_bump: u8,
    clock_slot: u64,
) -> Result<[u8; 32]> {
    require!(reveal_window_open(commit_slot, clock_slot), AofError::RevealWindowClosed);
    require_keys_eq!(slot.lock, *holder, AofError::VrfSlotNotHeld);
    require_keys_eq!(slot.randomness, *committed_randomness, AofError::InvalidRandomnessAccount);
    require_keys_eq!(a.randomness.key(), *committed_randomness, AofError::InvalidRandomnessAccount);
    require_keys_eq!(a.queue.key(), SWITCHBOARD_QUEUE, AofError::InvalidRandomnessAccount);

    cpi_reveal(a, params, authority_bump)?;

    let r = load_randomness(&a.randomness)?;
    require!(r.seed_slot == committed_seed_slot, AofError::RandomnessNotFresh);
    require!(r.reveal_slot == clock_slot, AofError::RandomnessNotRevealed);
    require!(r.value == params.value, AofError::RandomnessNotRevealed);
    slot.lock = Pubkey::default();
    slot.reveals = slot.reveals.saturating_add(1);
    Ok(r.value)
}

/// Refund path: free the slot held by `holder` once the window has closed.
pub fn release_for_refund(slot: &mut VrfSlot, holder: &Pubkey, commit_slot: u64, clock_slot: u64) -> Result<()> {
    require!(refund_window_open(commit_slot, clock_slot), AofError::CommitNotExpired);
    require_keys_eq!(slot.lock, *holder, AofError::VrfSlotNotHeld);
    slot.lock = Pubkey::default();
    Ok(())
}

pub fn reveal_window_open(commit_slot: u64, clock_slot: u64) -> bool {
    clock_slot < commit_slot.saturating_add(VRF_REFUND_AFTER_SLOTS)
}

pub fn refund_window_open(commit_slot: u64, clock_slot: u64) -> bool {
    !reveal_window_open(commit_slot, clock_slot)
}

// ---------------------------------------------------------------- outcomes

/// Domain-separated roll: one oracle value never drives two mechanics or two
/// commits the same way.
pub fn derive_roll(value: &[u8; 32], tag: &[u8], context: &[u8]) -> [u8; 32] {
    hashv(&[b"aof-vrf-v1".as_ref(), tag, context, value.as_ref()]).to_bytes()
}

/// Independent 64-bit lane `lane` (0..4) of a roll.
pub fn lane(roll: &[u8; 32], lane: usize) -> u64 {
    let mut bytes = [0u8; 8];
    bytes.copy_from_slice(&roll[lane * 8..lane * 8 + 8]);
    u64::from_le_bytes(bytes)
}

/// Map a uniform u64 onto 0..n by multiply-shift (bias below 2^-64 * n).
pub fn below(x: u64, n: u64) -> u64 {
    (((x as u128) * (n as u128)) >> 64) as u64
}

/// A uniform basis-point roll 0..10_000.
pub fn bps(x: u64) -> u64 {
    below(x, 10_000)
}
