/**
 * [AUDIT F-32] Generated table of aof-core instructions.
 *
 * Generated from aof_backend/src/idl/aof_core.json by
 * scripts/gen-core-instruction-table.py; re-run it after every `anchor build`
 * that changes the instruction set. The wallet guard uses this table to reject:
 *
 *   1. any instruction whose 8-byte discriminator is not recognised (an
 *      unrecognised aof-core call is never "probably fine");
 *   2. any authority-only instruction presented for the player to sign - a
 *      player wallet has no business signing `pay_out`, `mint_tool`,
 *      `set_paused` or any other authority instruction;
 *   3. any instruction whose account list length differs from the program's
 *      own context;
 *   4. any instruction where the connected wallet is not the signing actor.
 *      Every account slot the program declares as a signer and that names a
 *      party (user / buyer / maker / renter / ...) must be the wallet; that is
 *      what stops a tampered backend from putting the victim in the `seller`
 *      slot of a purchase. Slots the program does not require a signature for
 *      (auction_settle's `seller`, order matching's payees) are deliberately
 *      left alone, because those instructions are permissionless.
 *
 * Do not edit by hand: regenerate.
 */
export type CoreInstructionSpec = {
  readonly name: string;
  readonly discriminator: readonly number[];
  readonly accounts: readonly string[];
  /** Indexes of accounts that name a party (user / buyer / maker / renter ...). */
  readonly actorIndexes: readonly number[];
  /** Indexes of accounts the program requires a signature from. */
  readonly signerIndexes: readonly number[];
  /** Authority-signed only: a player wallet must never be asked to sign it. */
  readonly authorityOnly: boolean;
};

export const CORE_INSTRUCTIONS: readonly CoreInstructionSpec[] = [
  {
    name: "adjust_player_capacity",
    discriminator: [207, 232, 48, 248, 66, 147, 154, 158],
    accounts: ["config", "authority", "player"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "auction_bid",
    discriminator: [83, 236, 86, 75, 173, 170, 235, 201],
    accounts: ["config", "bidder", "mint", "auction", "previous_bidder", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "auction_create",
    discriminator: [127, 58, 10, 94, 55, 185, 42, 51],
    accounts: ["config", "seller", "mint", "tool", "seller_token", "auction", "auction_vault", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "auction_settle",
    discriminator: [125, 3, 88, 2, 1, 6, 23, 26],
    accounts: ["config", "mint", "auction", "seller", "treasury", "auction_vault", "winner_token", "tool", "token_program"],
    actorIndexes: [3],
    signerIndexes: [],
    authorityOnly: false,
  },
  {
    name: "burn_nft",
    discriminator: [119, 13, 183, 17, 194, 243, 38, 31],
    accounts: ["config", "user", "mint", "tool", "token_account", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "burn_resource",
    discriminator: [252, 54, 4, 35, 74, 224, 187, 19],
    accounts: ["config", "material_mints", "user", "mint", "token_account", "token_program"],
    actorIndexes: [2],
    signerIndexes: [2],
    authorityOnly: false,
  },
  {
    name: "burn_tool",
    discriminator: [149, 3, 119, 187, 129, 207, 46, 27],
    accounts: ["config", "user", "mint", "token_account", "tool_data", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "buy_lottery_ticket",
    discriminator: [88, 10, 212, 209, 116, 244, 214, 255],
    accounts: ["config", "buyer", "treasury", "lottery_round", "lottery_ticket", "ticket_counter", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "cancel_buy_order",
    discriminator: [168, 199, 175, 242, 230, 250, 27, 100],
    accounts: ["config", "maker", "mint", "order"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "cancel_sell_order",
    discriminator: [35, 49, 106, 38, 91, 127, 157, 20],
    accounts: ["config", "maker", "mint", "order", "order_vault", "maker_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "claim_lottery_prize",
    discriminator: [52, 56, 145, 142, 169, 97, 28, 116],
    accounts: ["config", "lottery_round", "lottery_ticket", "winner"],
    actorIndexes: [],
    signerIndexes: [3],
    authorityOnly: false,
  },
  {
    name: "claim_season_reward",
    discriminator: [129, 96, 145, 129, 154, 203, 29, 150],
    accounts: ["config", "authority", "material_mints", "season", "season_pass", "wood_mint", "user_wood", "auth", "token_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "collect_bread",
    discriminator: [34, 18, 53, 67, 153, 220, 4, 61],
    accounts: ["config", "user", "material_mints", "oven_state", "auth", "bread_mint", "user_bread", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "collect_flour",
    discriminator: [75, 219, 64, 128, 18, 22, 144, 234],
    accounts: ["config", "user", "material_mints", "mill_state", "auth", "flour_mint", "user_flour", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "collect_mining",
    discriminator: [33, 146, 126, 198, 213, 79, 169, 210],
    accounts: ["config", "user", "tool", "mint", "player", "material_mints", "auth", "payout_mint", "payout_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "collect_well_water",
    discriminator: [158, 216, 6, 212, 63, 164, 34, 24],
    accounts: ["config", "user", "player", "material_mints", "well_state", "weather_state", "auth", "water_mint", "user_water", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "collector_stake",
    discriminator: [186, 188, 29, 252, 163, 190, 68, 70],
    accounts: ["config", "user", "mint", "user_token", "vault", "vault_token", "staked_collector", "collector_allow", "player", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "collector_unstake",
    discriminator: [121, 45, 226, 172, 27, 180, 45, 254],
    accounts: ["config", "user", "mint", "user_token", "vault", "vault_token", "staked_collector", "player", "gastank", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "commit_lottery_draw",
    discriminator: [33, 145, 155, 216, 175, 15, 179, 138],
    accounts: ["config", "authority", "lottery_round"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "craft",
    discriminator: [161, 233, 177, 214, 243, 109, 161, 224],
    accounts: ["config", "authority", "user", "gastank", "prev_tool", "prev_mint", "prev_token", "new_mint", "new_token", "new_tool_data", "auth", "rarity_counter", "craft_economy", "wood_mint", "user_wood", "stone_mint", "user_stone", "food_mint", "user_food", "seeds_mint", "user_seeds", "water_mint", "user_water", "potato_mint", "user_potato", "skr_mint", "user_skr", "token_program", "system_program"],
    actorIndexes: [2],
    signerIndexes: [1, 2],
    authorityOnly: false,
  },
  {
    name: "craft_order_cancel",
    discriminator: [72, 33, 167, 12, 104, 178, 254, 144],
    accounts: ["config", "creator", "craft_order"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "craft_order_create",
    discriminator: [206, 24, 56, 85, 71, 6, 137, 97],
    accounts: ["config", "creator", "craft_order", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "craft_order_fulfill",
    discriminator: [251, 90, 95, 48, 249, 94, 145, 204],
    accounts: ["config", "fulfiller", "craft_order", "creator_refund", "treasury", "wood_mint", "fulfiller_wood", "creator_wood", "stone_mint", "fulfiller_stone", "creator_stone", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "craft_recipe",
    discriminator: [184, 206, 123, 148, 189, 124, 168, 0],
    accounts: ["config", "user", "material_mints", "auth", "input_1_mint", "input_1_acc", "input_2_mint", "input_2_acc", "output_mint", "output_acc", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "deposit_gas",
    discriminator: [164, 223, 20, 23, 50, 107, 168, 108],
    accounts: ["config", "user", "gastank", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "draw_lottery",
    discriminator: [17, 188, 124, 77, 90, 34, 97, 19],
    accounts: ["config", "authority", "lottery_round", "slot_hashes"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "explore_reveal",
    discriminator: [16, 121, 80, 56, 125, 254, 216, 215],
    accounts: ["config", "authority", "exploration_state", "exploration_commit", "payer", "wood_mint", "user_wood", "stone_mint", "user_stone", "auth", "slot_hashes", "token_program"],
    actorIndexes: [4],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "forge_attempt_commit",
    discriminator: [89, 191, 80, 34, 38, 104, 53, 252],
    accounts: ["config", "user", "tool", "tool_mint", "enchant_slot", "forge_commit", "wood_mint", "user_wood", "stone_mint", "user_stone", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "forge_attempt_reveal",
    discriminator: [6, 210, 51, 190, 121, 55, 64, 35],
    accounts: ["config", "authority", "enchant_slot", "forge_commit", "payer", "treasury", "slot_hashes"],
    actorIndexes: [4],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "forge_attempt_expire",
    discriminator: [206, 118, 31, 164, 99, 185, 27, 61],
    accounts: ["config", "forge_commit", "user", "auth", "wood_mint", "user_wood", "stone_mint", "user_stone", "token_program"],
    actorIndexes: [2],
    signerIndexes: [],
    authorityOnly: false,
  },
  {
    name: "grant_season_xp",
    discriminator: [164, 174, 57, 51, 25, 50, 194, 250],
    accounts: ["config", "authority", "user", "season", "season_pass", "system_program"],
    actorIndexes: [2],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "harvest_wheat",
    discriminator: [170, 219, 76, 224, 75, 193, 177, 108],
    accounts: ["config", "user", "material_mints", "energy_account", "farm_tile", "tool_data", "auth", "wheat_mint", "user_wheat", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "init_craft_economy",
    discriminator: [63, 105, 210, 112, 67, 179, 176, 134],
    accounts: ["config", "authority", "craft_economy", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "init_lottery_round",
    discriminator: [208, 250, 71, 151, 138, 77, 160, 70],
    accounts: ["config", "authority", "lottery_round", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "init_material_mints",
    discriminator: [29, 246, 87, 231, 232, 36, 192, 169],
    accounts: ["config", "authority", "material_mints", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "init_pack_config",
    discriminator: [12, 9, 194, 89, 200, 200, 243, 84],
    accounts: ["config", "authority", "pack_config", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "init_rarity_counter",
    discriminator: [129, 105, 6, 249, 164, 72, 113, 47],
    accounts: ["config", "authority", "rarity_counter", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "init_reroll_config",
    discriminator: [39, 188, 128, 78, 177, 35, 254, 2],
    accounts: ["config", "authority", "reroll_config", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "init_season",
    discriminator: [179, 47, 101, 197, 114, 97, 174, 98],
    accounts: ["config", "authority", "season", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "initialize",
    discriminator: [175, 175, 109, 31, 13, 152, 155, 237],
    accounts: ["config", "authority", "auth", "vault", "program_data", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "marketplace_buy",
    discriminator: [92, 247, 50, 140, 72, 120, 69, 249],
    accounts: ["config", "buyer", "seller", "treasury", "mint", "tool", "listing", "listing_vault", "buyer_token", "token_program", "system_program"],
    actorIndexes: [1, 2],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "marketplace_cancel",
    discriminator: [36, 142, 66, 132, 187, 198, 47, 134],
    accounts: ["config", "mint", "listing", "seller", "listing_vault", "seller_token", "token_program"],
    actorIndexes: [3],
    signerIndexes: [3],
    authorityOnly: false,
  },
  {
    name: "marketplace_list",
    discriminator: [126, 197, 146, 219, 11, 249, 104, 168],
    accounts: ["config", "seller", "mint", "tool", "seller_token", "listing", "listing_vault", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "match_resource_orders",
    discriminator: [159, 91, 215, 168, 28, 187, 235, 211],
    accounts: ["config", "material_mints", "mint", "buy_order", "sell_order", "seller", "treasury", "sell_vault", "buyer_token", "token_program"],
    actorIndexes: [5],
    signerIndexes: [],
    authorityOnly: false,
  },
  {
    name: "migrate_tool",
    discriminator: [178, 226, 104, 122, 30, 161, 143, 250],
    accounts: ["config", "migration_authority", "authority", "auth", "vault", "mint", "vault_token_account", "tool_data", "token_program", "system_program"],
    actorIndexes: [],
    signerIndexes: [1, 2],
    authorityOnly: true,
  },
  {
    name: "mint_resource",
    discriminator: [2, 118, 133, 91, 220, 176, 214, 105],
    accounts: ["config", "material_mints", "authority", "auth", "mint", "token_account", "treasury_token", "player", "issuance_cap", "token_program", "system_program"],
    actorIndexes: [],
    signerIndexes: [2],
    authorityOnly: true,
  },
  {
    name: "mint_tool",
    discriminator: [9, 202, 31, 77, 56, 227, 14, 40],
    accounts: ["config", "authority", "auth", "mint", "token_account", "recipient", "tool_data", "token_program", "system_program"],
    actorIndexes: [5],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "offer_accept",
    discriminator: [218, 1, 39, 54, 53, 67, 142, 34],
    accounts: ["config", "seller", "mint", "tool", "offer", "buyer_refund", "treasury", "seller_token", "buyer_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "offer_cancel",
    discriminator: [243, 115, 206, 248, 38, 241, 122, 53],
    accounts: ["config", "mint", "offer", "buyer"],
    actorIndexes: [3],
    signerIndexes: [3],
    authorityOnly: false,
  },
  {
    name: "offer_create",
    discriminator: [119, 123, 83, 165, 54, 130, 202, 150],
    accounts: ["config", "buyer", "mint", "offer", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "pack_open_commit",
    discriminator: [119, 24, 174, 81, 188, 146, 76, 40],
    accounts: ["config", "authority", "user", "pack_config", "auth", "mint", "pack_commit", "system_program"],
    actorIndexes: [2],
    signerIndexes: [1, 2],
    authorityOnly: false,
  },
  {
    name: "pack_open_reveal",
    discriminator: [220, 51, 163, 236, 133, 22, 85, 61],
    accounts: ["config", "authority", "pack_commit", "user", "treasury", "pack_config", "mint", "user_token", "tool_data", "auth", "slot_hashes", "token_program", "system_program"],
    actorIndexes: [3],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "pack_open_expire",
    discriminator: [8, 126, 131, 194, 12, 202, 159, 29],
    accounts: ["config", "pack_commit", "user", "mint"],
    actorIndexes: [2],
    signerIndexes: [],
    authorityOnly: false,
  },
  {
    name: "pay_out",
    discriminator: [122, 7, 14, 119, 71, 188, 166, 34],
    accounts: ["config", "authority", "vault", "mint", "vault_token", "user_token", "player", "material_mints", "vault_guard", "token_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "pay_out_with_referral",
    discriminator: [250, 198, 134, 140, 32, 8, 48, 5],
    accounts: ["config", "authority", "vault", "mint", "vault_token", "user_token", "referral_link", "referrer_token", "player", "material_mints", "vault_guard", "token_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "place_buy_order",
    discriminator: [47, 253, 241, 214, 167, 204, 11, 39],
    accounts: ["config", "maker", "mint", "material_mints", "order", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "place_sell_order",
    discriminator: [254, 177, 180, 104, 171, 194, 79, 86],
    accounts: ["config", "maker", "mint", "material_mints", "maker_token", "order", "order_vault", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "plant_seeds",
    discriminator: [157, 33, 113, 208, 164, 49, 10, 229],
    accounts: ["config", "user", "material_mints", "energy_account", "farm_tile", "seeds_mint", "user_seeds", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "purchase_season_pass",
    discriminator: [233, 149, 73, 70, 108, 174, 246, 71],
    accounts: ["config", "user", "treasury", "season", "season_pass", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "referral_bind",
    discriminator: [94, 97, 178, 7, 104, 89, 66, 85],
    accounts: ["config", "referred", "referrer", "referrer_player", "referrer_stats", "referral_link", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "referral_upgrade",
    discriminator: [13, 103, 189, 82, 214, 68, 106, 15],
    accounts: ["config", "user", "referral_link", "wood_mint", "user_wood", "stone_mint", "user_stone", "food_mint", "user_food", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "rental_end",
    discriminator: [164, 124, 203, 70, 52, 129, 186, 66],
    accounts: ["config", "caller", "mint", "tool", "rental_agreement", "renter_refund"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "rental_list",
    discriminator: [117, 211, 91, 46, 123, 180, 139, 146],
    accounts: ["config", "owner", "mint", "tool", "rental_listing", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "rental_revoke",
    discriminator: [102, 156, 111, 193, 139, 106, 44, 46],
    accounts: ["config", "owner", "mint", "tool", "rental_agreement", "renter_refund"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "rental_start",
    discriminator: [72, 125, 23, 178, 217, 225, 224, 37],
    accounts: ["config", "renter", "mint", "tool", "rental_listing", "owner", "treasury", "rental_agreement", "system_program"],
    actorIndexes: [1, 5],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "repair",
    discriminator: [97, 230, 48, 23, 128, 133, 201, 192],
    accounts: ["config", "user", "tool", "mint", "stone_mint", "user_stone", "wood_mint", "user_wood", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "reroll",
    discriminator: [19, 251, 26, 108, 113, 68, 194, 142],
    accounts: ["config", "user", "gastank", "tool_a", "mint_a", "token_a", "tool_b", "mint_b", "token_b", "new_mint", "new_token", "new_tool_data", "auth", "rarity_counter", "craft_economy", "wood_mint", "user_wood", "stone_mint", "user_stone", "food_mint", "user_food", "seeds_mint", "user_seeds", "water_mint", "user_water", "potato_mint", "user_potato", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "reroll_random_commit",
    discriminator: [116, 32, 24, 82, 9, 94, 122, 236],
    accounts: ["config", "user", "gastank", "burn_tool", "burn_mint", "burn_token", "new_mint", "reroll_commit", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "reroll_random_reveal",
    discriminator: [123, 60, 249, 147, 211, 177, 53, 33],
    accounts: ["config", "authority", "reroll_config", "reroll_commit", "payer", "new_mint", "new_token", "new_tool_data", "auth", "slot_hashes", "token_program", "system_program"],
    actorIndexes: [4],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "set_craft_economy",
    discriminator: [120, 212, 205, 243, 202, 47, 137, 226],
    accounts: ["config", "authority", "craft_economy"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_fees",
    discriminator: [137, 178, 49, 58, 0, 245, 242, 190],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_pack_config",
    discriminator: [184, 55, 219, 28, 73, 225, 169, 241],
    accounts: ["config", "authority", "pack_config"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_paused",
    discriminator: [91, 60, 125, 192, 176, 225, 166, 218],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_reroll_config",
    discriminator: [38, 174, 229, 178, 197, 217, 46, 192],
    accounts: ["config", "authority", "reroll_config"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_resource_mints",
    discriminator: [111, 179, 202, 97, 194, 50, 136, 19],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "stake",
    discriminator: [206, 176, 202, 18, 200, 209, 179, 108],
    accounts: ["config", "user", "tool", "mint", "user_token", "vault", "vault_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "start_baking",
    discriminator: [97, 179, 181, 240, 28, 104, 190, 205],
    accounts: ["config", "user", "material_mints", "energy_account", "oven_state", "flour_mint", "water_mint", "wood_mint", "coal_mint", "user_flour", "user_water", "user_wood", "user_coal", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "start_exploration_commit",
    discriminator: [58, 145, 149, 221, 209, 9, 12, 173],
    accounts: ["config", "material_mints", "user", "exploration_state", "tool_mint", "tool", "exploration_commit", "food_mint", "user_food", "wood_mint", "user_wood", "stone_mint", "user_stone", "meat_mint", "user_meat", "token_program", "system_program"],
    actorIndexes: [2],
    signerIndexes: [2],
    authorityOnly: false,
  },
  {
    name: "start_milling",
    discriminator: [12, 183, 141, 54, 123, 57, 105, 5],
    accounts: ["config", "user", "material_mints", "energy_account", "mill_state", "wheat_mint", "stone_mint", "user_wheat", "user_stone", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "start_mining",
    discriminator: [108, 28, 69, 67, 54, 120, 245, 196],
    accounts: ["config", "user", "tool", "mint", "player", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "sweep_gas_fees",
    discriminator: [114, 3, 27, 208, 121, 220, 139, 7],
    accounts: ["config", "authority", "gastank", "treasury", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "unstake",
    discriminator: [90, 95, 107, 42, 205, 124, 50, 225],
    accounts: ["config", "user", "tool", "mint", "user_token", "gastank", "vault", "vault_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "upgrade_exploration_tier",
    discriminator: [36, 77, 217, 211, 252, 176, 30, 108],
    accounts: ["config", "user", "exploration_state", "wood_mint", "user_wood", "stone_mint", "user_stone", "food_mint", "user_food", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "weather_crank",
    discriminator: [116, 31, 101, 128, 172, 213, 119, 144],
    accounts: ["config", "cranker", "weather_state", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "withdraw_gas",
    discriminator: [35, 60, 150, 196, 226, 110, 54, 45],
    accounts: ["config", "user", "gastank", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "mint_resource_once",
    discriminator: [112, 16, 85, 114, 236, 4, 67, 139],
    accounts: ["config", "material_mints", "authority", "auth", "mint", "token_account", "treasury_token", "player", "issuance_cap", "token_program", "reward_receipt", "system_program"],
    actorIndexes: [],
    signerIndexes: [2],
    authorityOnly: true,
  },
  {
    name: "marketplace_buy_bounded",
    discriminator: [219, 1, 7, 251, 90, 189, 167, 48],
    accounts: ["config", "buyer", "seller", "treasury", "mint", "tool", "listing", "listing_vault", "buyer_token", "token_program", "system_program"],
    actorIndexes: [1, 2],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "init_issuance_cap",
    discriminator: [7, 110, 74, 57, 227, 136, 110, 214],
    accounts: ["config", "authority", "issuance_cap", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_issuance_cap",
    discriminator: [227, 134, 78, 85, 122, 198, 113, 59],
    accounts: ["config", "authority", "issuance_cap"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_pending_authority",
    discriminator: [175, 71, 167, 223, 49, 144, 102, 193],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "accept_authority",
    discriminator: [107, 86, 198, 91, 33, 12, 107, 160],
    accounts: ["config", "new_authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "cancel_pending_authority",
    discriminator: [155, 52, 245, 225, 85, 73, 58, 238],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_mining_enabled",
    discriminator: [240, 237, 205, 117, 79, 7, 125, 116],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "init_vault_guard",
    discriminator: [20, 12, 78, 107, 5, 169, 61, 101],
    accounts: ["config", "authority", "mint", "vault_guard", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_vault_guard",
    discriminator: [188, 146, 45, 181, 231, 183, 48, 53],
    accounts: ["config", "authority", "mint", "vault_guard"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_supply_cap",
    discriminator: [26, 229, 174, 213, 12, 59, 220, 71],
    accounts: ["config", "authority", "material_mints"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "register_collector_mint",
    discriminator: [230, 133, 88, 35, 115, 148, 172, 128],
    accounts: ["config", "authority", "mint", "entry", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "revoke_collector_mint",
    discriminator: [45, 151, 59, 119, 159, 240, 101, 86],
    accounts: ["config", "authority", "mint", "entry"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "refund_lottery_round",
    discriminator: [134, 87, 211, 115, 122, 237, 217, 204],
    accounts: ["config", "payer", "round", "treasury"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
  },
  {
    name: "migrate_config_v2",
    discriminator: [21, 39, 88, 172, 254, 205, 30, 141],
    accounts: ["config", "authority", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_roles",
    discriminator: [119, 86, 129, 161, 55, 23, 250, 12],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "emergency_stop",
    discriminator: [179, 143, 200, 137, 108, 245, 248, 35],
    accounts: ["config", "caller"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: true,
  },
  {
    name: "set_cashout_frozen",
    discriminator: [188, 201, 38, 248, 184, 63, 152, 137],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
  },

];

const BY_DISCRIMINATOR: Map<string, CoreInstructionSpec> = new Map(
  CORE_INSTRUCTIONS.map((spec) => [spec.discriminator.join(","), spec]),
);

/** Resolve a raw instruction to its aof-core spec, or undefined when the
 * discriminator is unknown to this build of the program. */
export function coreInstructionSpec(
  programId: string,
  data: Uint8Array,
  coreProgramId: string,
): CoreInstructionSpec | undefined {
  if (programId !== coreProgramId || data.length < 8) return undefined;
  return BY_DISCRIMINATOR.get(Array.from(data.slice(0, 8)).join(","));
}
