/**
 * [AUDIT F-32] Generated table of aof-core instructions.
 *
 * Generated from aof_backend/src/idl/aof_core.json by
 * scripts/gen-core-instruction-table.py; re-run it after every `anchor build`
 * that changes the instruction set. The wallet guard uses this table to reject:
 *
 *   1. any instruction whose 8-byte discriminator is not recognised (an
 *      unrecognised aof-core call is never "probably fine");
 *   2. any authority-only instruction presented for the player to sign - a
 *      player wallet has no business signing `pay_out`,
 *      `set_paused` or any other authority instruction;
 *   3. any instruction whose account list length differs from the program's
 *      own context;
 *   4. any instruction where the connected wallet is not the signing actor.
 *      Every account slot the program declares as a signer and that names a
 *      party (user / buyer / maker / renter / ...) must be the wallet; that is
 *      what stops a tampered backend from putting the victim in the `seller`
 *      slot of a purchase. Slots the program does not require a signature for
 *      (auction_settle's `seller`, order matching's payees) are deliberately
 *      left alone, because those instructions are permissionless.
 *
 * Do not edit by hand: regenerate.
 */
export type CoreInstructionSpec = {
  readonly name: string;
  readonly discriminator: readonly number[];
  readonly accounts: readonly string[];
  /** Indexes of accounts that name a party (user / buyer / maker / renter ...). */
  readonly actorIndexes: readonly number[];
  /** Indexes of accounts the program requires a signature from. */
  readonly signerIndexes: readonly number[];
  /** Authority-signed only: a player wallet must never be asked to sign it. */
  readonly authorityOnly: boolean;
  /**
   * Trailing accounts the IDL cannot describe: `"pairs"` means the caller adds
   * `(mint, token_account)` couples after the fixed prefix. The caller's intent
   * validator must check every one of them; `null` means the list is exact.
   */
  readonly trailingAccounts: "pairs" | null;
};

export const CORE_INSTRUCTIONS: readonly CoreInstructionSpec[] = [
  {
    name: "adjust_player_capacity",
    discriminator: [207, 232, 48, 248, 66, 147, 154, 158],
    accounts: ["config", "authority", "player"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "auction_bid",
    discriminator: [83, 236, 86, 75, 173, 170, 235, 201],
    accounts: ["config", "bidder", "mint", "auction", "previous_bidder", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "auction_create",
    discriminator: [127, 58, 10, 94, 55, 185, 42, 51],
    accounts: ["config", "seller", "mint", "tool", "seller_token", "auction", "auction_vault", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "auction_settle",
    discriminator: [125, 3, 88, 2, 1, 6, 23, 26],
    accounts: ["config", "mint", "auction", "seller", "treasury", "auction_vault", "winner_token", "tool", "token_program"],
    actorIndexes: [3],
    signerIndexes: [],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "burn_nft",
    discriminator: [119, 13, 183, 17, 194, 243, 38, 31],
    accounts: ["config", "user", "mint", "tool", "token_account", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "burn_resource",
    discriminator: [252, 54, 4, 35, 74, 224, 187, 19],
    accounts: ["config", "material_mints", "user", "mint", "token_account", "token_program"],
    actorIndexes: [2],
    signerIndexes: [2],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "burn_tool",
    discriminator: [149, 3, 119, 187, 129, 207, 46, 27],
    accounts: ["config", "user", "mint", "token_account", "tool_data", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "buy_lottery_ticket",
    discriminator: [88, 10, 212, 209, 116, 244, 214, 255],
    accounts: ["config", "buyer", "lottery_round", "lottery_ticket", "ticket_counter", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "cancel_buy_order",
    discriminator: [168, 199, 175, 242, 230, 250, 27, 100],
    accounts: ["config", "maker", "mint", "order"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "cancel_sell_order",
    discriminator: [35, 49, 106, 38, 91, 127, 157, 20],
    accounts: ["config", "maker", "mint", "order", "order_vault", "maker_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "claim_lottery_prize",
    discriminator: [52, 56, 145, 142, 169, 97, 28, 116],
    accounts: ["config", "lottery_round", "lottery_ticket", "winner"],
    actorIndexes: [3],
    signerIndexes: [3],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "claim_season_reward",
    discriminator: [129, 96, 145, 129, 154, 203, 29, 150],
    accounts: ["config", "authority", "material_mints", "season", "season_pass", "circuit_mint", "user_circuit", "auth", "token_program", "issuance_cap_circuit"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "collect_model",
    discriminator: [245, 75, 200, 30, 213, 238, 17, 98],
    accounts: ["config", "user", "material_mints", "model_state", "auth", "model_mint", "user_model", "token_program", "issuance_cap_model"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "collect_signal",
    discriminator: [146, 145, 125, 81, 58, 142, 12, 102],
    accounts: ["config", "user", "material_mints", "signal_state", "auth", "signal_mint", "user_signal", "token_program", "issuance_cap_signal"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "collect_mining",
    discriminator: [33, 146, 126, 198, 213, 79, 169, 210],
    accounts: ["config", "user", "tool", "mint", "player", "material_mints", "auth", "payout_mint", "payout_token", "vault", "vault_token", "token_program", "issuance_cap"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "collect_power",
    discriminator: [145, 202, 61, 251, 35, 228, 162, 56],
    accounts: ["config", "user", "player", "material_mints", "grid_state", "weather_state", "auth", "power_mint", "user_power", "token_program", "system_program", "issuance_cap_power"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "collector_stake",
    discriminator: [186, 188, 29, 252, 163, 190, 68, 70],
    accounts: ["config", "user", "mint", "user_token", "vault", "vault_token", "staked_collector", "collector_allow", "player", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "collector_unstake",
    discriminator: [121, 45, 226, 172, 27, 180, 45, 254],
    accounts: ["config", "user", "mint", "user_token", "vault", "vault_token", "staked_collector", "player", "gastank", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "commit_lottery_draw",
    discriminator: [33, 145, 155, 216, 175, 15, 179, 138],
    accounts: ["config", "cranker", "lottery_round", "vrf_slot", "recent_slothashes"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "craft",
    discriminator: [161, 233, 177, 214, 243, 109, 161, 224],
    accounts: ["config", "authority", "user", "gastank", "prev_tool", "prev_mint", "prev_token", "new_mint", "new_token", "new_tool_data", "auth", "rarity_counter", "craft_economy", "circuit_mint", "user_circuit", "silicon_mint", "user_silicon", "data_mint", "user_data", "neuron_mint", "user_neuron", "power_mint", "user_power", "mind_mint", "user_mind", "token_program", "system_program", "tool_metadata_registry", "metadata", "token_metadata_program"],
    actorIndexes: [2],
    signerIndexes: [1, 2],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "craft_order_cancel",
    discriminator: [72, 33, 167, 12, 104, 178, 254, 144],
    accounts: ["config", "creator", "craft_order"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "craft_order_create",
    discriminator: [206, 24, 56, 85, 71, 6, 137, 97],
    accounts: ["config", "creator", "craft_order", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "craft_order_fulfill",
    discriminator: [251, 90, 95, 48, 249, 94, 145, 204],
    accounts: ["config", "fulfiller", "craft_order", "creator_refund", "treasury", "circuit_mint", "fulfiller_circuit", "creator_circuit", "silicon_mint", "fulfiller_silicon", "creator_silicon", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "craft_recipe",
    discriminator: [184, 206, 123, 148, 189, 124, 168, 0],
    accounts: ["config", "user", "material_mints", "auth", "input_1_mint", "input_1_acc", "input_2_mint", "input_2_acc", "output_mint", "output_acc", "token_program", "issuance_cap"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "deposit_gas",
    discriminator: [164, 223, 20, 23, 50, 107, 168, 108],
    accounts: ["config", "user", "gastank", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "draw_lottery",
    discriminator: [17, 188, 124, 77, 90, 34, 97, 19],
    accounts: ["config", "cranker", "lottery_round", "treasury", "vrf_slot", "recent_slothashes", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "explore_reveal",
    discriminator: [16, 121, 80, 56, 125, 254, 216, 215],
    accounts: ["config", "material_mints", "cranker", "exploration_commit", "user", "data_mint", "dataset_mint", "circuit_mint", "user_circuit", "silicon_mint", "user_silicon", "auth", "escrow_data", "escrow_circuit", "escrow_silicon", "escrow_dataset", "vrf_slot", "recent_slothashes", "token_program", "associated_token_program", "system_program", "issuance_cap_circuit", "issuance_cap_silicon"],
    actorIndexes: [2, 4],
    signerIndexes: [2],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "forge_attempt_commit",
    discriminator: [89, 191, 80, 34, 38, 104, 53, 252],
    accounts: ["config", "authority", "user", "auth", "tool", "tool_mint", "enchant_slot", "forge_commit", "circuit_mint", "user_circuit", "silicon_mint", "user_silicon", "escrow_circuit", "escrow_silicon", "vrf_slot", "recent_slothashes", "token_program", "system_program"],
    actorIndexes: [2],
    signerIndexes: [1, 2],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "forge_attempt_reveal",
    discriminator: [6, 210, 51, 190, 121, 55, 64, 35],
    accounts: ["config", "auth", "circuit_mint", "escrow_circuit", "silicon_mint", "escrow_silicon", "cranker", "enchant_slot", "forge_commit", "user", "treasury", "vrf_slot", "recent_slothashes", "token_program", "system_program"],
    actorIndexes: [6, 9],
    signerIndexes: [6],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "forge_attempt_expire",
    discriminator: [206, 118, 31, 164, 99, 185, 27, 61],
    accounts: ["config", "forge_commit", "user", "treasury", "vrf_slot", "recent_slothashes", "auth", "circuit_mint", "user_circuit", "escrow_circuit", "silicon_mint", "user_silicon", "escrow_silicon", "token_program"],
    actorIndexes: [2],
    signerIndexes: [],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "grant_season_xp",
    discriminator: [164, 174, 57, 51, 25, 50, 194, 250],
    accounts: ["config", "authority", "user", "season", "season_pass", "claim_cursor", "system_program"],
    actorIndexes: [2],
    signerIndexes: [1, 2],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "harvest_synapse",
    discriminator: [13, 153, 110, 144, 14, 216, 30, 92],
    accounts: ["config", "user", "material_mints", "energy_account", "lab_tile", "tool_data", "auth", "synapse_mint", "user_synapse", "token_program", "system_program", "issuance_cap_synapse"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "init_craft_economy",
    discriminator: [63, 105, 210, 112, 67, 179, 176, 134],
    accounts: ["config", "authority", "craft_economy", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "init_lottery_round",
    discriminator: [208, 250, 71, 151, 138, 77, 160, 70],
    accounts: ["config", "authority", "lottery_round", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "init_material_mints",
    discriminator: [29, 246, 87, 231, 232, 36, 192, 169],
    accounts: ["config", "authority", "material_mints", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "init_pack_config",
    discriminator: [12, 9, 194, 89, 200, 200, 243, 84],
    accounts: ["config", "authority", "pack_config", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "init_rarity_counter",
    discriminator: [129, 105, 6, 249, 164, 72, 113, 47],
    accounts: ["config", "authority", "rarity_counter", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "init_reroll_config",
    discriminator: [39, 188, 128, 78, 177, 35, 254, 2],
    accounts: ["config", "authority", "reroll_config", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "init_season",
    discriminator: [179, 47, 101, 197, 114, 97, 174, 98],
    accounts: ["config", "authority", "season", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "initialize",
    discriminator: [175, 175, 109, 31, 13, 152, 155, 237],
    accounts: ["config", "authority", "auth", "vault", "program_data", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "marketplace_cancel",
    discriminator: [36, 142, 66, 132, 187, 198, 47, 134],
    accounts: ["config", "mint", "listing", "seller", "listing_vault", "seller_token", "token_program"],
    actorIndexes: [3],
    signerIndexes: [3],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "marketplace_list",
    discriminator: [126, 197, 146, 219, 11, 249, 104, 168],
    accounts: ["config", "seller", "mint", "tool", "seller_token", "listing", "listing_vault", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "match_resource_orders",
    discriminator: [159, 91, 215, 168, 28, 187, 235, 211],
    accounts: ["config", "material_mints", "mint", "buy_order", "sell_order", "seller", "treasury", "sell_vault", "buyer_token", "token_program"],
    actorIndexes: [5],
    signerIndexes: [],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "mint_resource",
    discriminator: [2, 118, 133, 91, 220, 176, 214, 105],
    accounts: ["config", "material_mints", "authority", "auth", "mint", "token_account", "treasury_token", "player", "issuance_cap", "token_program", "system_program"],
    actorIndexes: [],
    signerIndexes: [2],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "mint_tool",
    discriminator: [9, 202, 31, 77, 56, 227, 14, 40],
    accounts: ["config", "authority", "auth", "mint", "token_account", "recipient", "payer", "tool_data", "token_program", "system_program", "tool_metadata_registry", "metadata", "token_metadata_program"],
    actorIndexes: [5, 6],
    signerIndexes: [1, 6],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "offer_accept",
    discriminator: [218, 1, 39, 54, 53, 67, 142, 34],
    accounts: ["config", "seller", "mint", "tool", "offer", "buyer_refund", "treasury", "seller_token", "buyer_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "offer_cancel",
    discriminator: [243, 115, 206, 248, 38, 241, 122, 53],
    accounts: ["config", "mint", "offer", "buyer"],
    actorIndexes: [3],
    signerIndexes: [3],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "offer_create",
    discriminator: [119, 123, 83, 165, 54, 130, 202, 150],
    accounts: ["config", "buyer", "mint", "offer", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "pack_open_commit",
    discriminator: [119, 24, 174, 81, 188, 146, 76, 40],
    accounts: ["config", "authority", "user", "pack_config", "pack_commit", "vrf_slot", "recent_slothashes", "system_program"],
    actorIndexes: [2],
    signerIndexes: [1, 2],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "pack_open_reveal",
    discriminator: [220, 51, 163, 236, 133, 22, 85, 61],
    accounts: ["config", "cranker", "pack_commit", "user", "treasury", "mint", "user_token", "tool_data", "auth", "vrf_slot", "recent_slothashes", "token_program", "associated_token_program", "system_program", "tool_metadata_registry", "metadata", "token_metadata_program"],
    actorIndexes: [1, 3],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "pack_open_expire",
    discriminator: [8, 126, 131, 194, 12, 202, 159, 29],
    accounts: ["config", "pack_commit", "user", "treasury", "vrf_slot", "recent_slothashes"],
    actorIndexes: [2],
    signerIndexes: [],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "pay_out",
    discriminator: [122, 7, 14, 119, 71, 188, 166, 34],
    accounts: ["config", "authority", "vault", "mint", "vault_token", "user_token", "player", "material_mints", "vault_guard", "token_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "pay_out_with_referral",
    discriminator: [250, 198, 134, 140, 32, 8, 48, 5],
    accounts: ["config", "authority", "vault", "mint", "vault_token", "user_token", "referral_link", "referrer_token", "player", "material_mints", "vault_guard", "token_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "place_buy_order",
    discriminator: [47, 253, 241, 214, 167, 204, 11, 39],
    accounts: ["config", "maker", "mint", "material_mints", "order", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "place_sell_order",
    discriminator: [254, 177, 180, 104, 171, 194, 79, 86],
    accounts: ["config", "maker", "mint", "material_mints", "maker_token", "order", "order_vault", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "plant_neuron",
    discriminator: [103, 210, 21, 145, 72, 189, 198, 133],
    accounts: ["config", "user", "material_mints", "energy_account", "lab_tile", "neuron_mint", "user_neuron", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "purchase_season_pass",
    discriminator: [233, 149, 73, 70, 108, 174, 246, 71],
    accounts: ["config", "user", "treasury", "season", "season_pass", "premium_claims", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "referral_bind",
    discriminator: [94, 97, 178, 7, 104, 89, 66, 85],
    accounts: ["config", "referred", "referrer", "referrer_player", "referrer_stats", "referral_link", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "referral_upgrade",
    discriminator: [13, 103, 189, 82, 214, 68, 106, 15],
    accounts: ["config", "user", "referral_link", "circuit_mint", "user_circuit", "silicon_mint", "user_silicon", "data_mint", "user_data", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "rental_end",
    discriminator: [164, 124, 203, 70, 52, 129, 186, 66],
    accounts: ["config", "caller", "mint", "tool", "rental_agreement", "renter_refund"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "rental_list",
    discriminator: [117, 211, 91, 46, 123, 180, 139, 146],
    accounts: ["config", "owner", "mint", "tool", "rental_listing", "owner_token", "rental_vault", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "rental_revoke",
    discriminator: [102, 156, 111, 193, 139, 106, 44, 46],
    accounts: ["config", "owner", "mint", "tool", "rental_agreement", "renter_refund", "rental_listing", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "repair",
    discriminator: [97, 230, 48, 23, 128, 133, 201, 192],
    accounts: ["config", "user", "tool", "mint", "silicon_mint", "user_silicon", "circuit_mint", "user_circuit", "tool_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "start_mining_delegated",
    discriminator: [104, 124, 111, 44, 33, 234, 134, 159],
    accounts: ["config", "user", "tool", "mint", "player", "rental_listing", "rental_agreement", "rental_vault", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "collect_mining_delegated",
    discriminator: [155, 240, 39, 145, 155, 64, 189, 216],
    accounts: ["config", "user", "tool", "mint", "player", "material_mints", "auth", "payout_mint", "payout_token", "rental_listing", "rental_agreement", "rental_vault", "token_program", "issuance_cap"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "repair_delegated",
    discriminator: [174, 233, 100, 52, 228, 100, 191, 133],
    accounts: ["config", "user", "tool", "mint", "silicon_mint", "user_silicon", "circuit_mint", "user_circuit", "rental_listing", "rental_agreement", "rental_vault", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "reroll",
    discriminator: [19, 251, 26, 108, 113, 68, 194, 142],
    accounts: ["config", "user", "gastank", "tool_a", "mint_a", "token_a", "tool_b", "mint_b", "token_b", "new_mint", "new_token", "new_tool_data", "auth", "rarity_counter", "craft_economy", "circuit_mint", "user_circuit", "silicon_mint", "user_silicon", "data_mint", "user_data", "neuron_mint", "user_neuron", "power_mint", "user_power", "mind_mint", "user_mind", "token_program", "system_program", "tool_metadata_registry", "metadata", "token_metadata_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "reroll_random_commit",
    discriminator: [116, 32, 24, 82, 9, 94, 122, 236],
    accounts: ["config", "authority", "user", "gastank", "reroll_config", "burn_tool", "burn_mint", "burn_token", "reroll_commit", "vrf_slot", "recent_slothashes", "token_program", "system_program"],
    actorIndexes: [2],
    signerIndexes: [1, 2],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "reroll_random_reveal",
    discriminator: [123, 60, 249, 147, 211, 177, 53, 33],
    accounts: ["config", "cranker", "reroll_commit", "user", "treasury", "new_mint", "new_token", "new_tool_data", "auth", "vrf_slot", "recent_slothashes", "token_program", "associated_token_program", "system_program", "tool_metadata_registry", "metadata", "token_metadata_program"],
    actorIndexes: [1, 3],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "set_craft_economy",
    discriminator: [120, 212, 205, 243, 202, 47, 137, 226],
    accounts: ["config", "authority", "craft_economy"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_fees",
    discriminator: [137, 178, 49, 58, 0, 245, 242, 190],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_pack_config",
    discriminator: [184, 55, 219, 28, 73, 225, 169, 241],
    accounts: ["config", "authority", "pack_config"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_paused",
    discriminator: [91, 60, 125, 192, 176, 225, 166, 218],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_reroll_config",
    discriminator: [38, 174, 229, 178, 197, 217, 46, 192],
    accounts: ["config", "authority", "reroll_config"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_resource_mints",
    discriminator: [111, 179, 202, 97, 194, 50, 136, 19],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "stake",
    discriminator: [206, 176, 202, 18, 200, 209, 179, 108],
    accounts: ["config", "user", "tool", "mint", "user_token", "vault", "vault_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "start_model_training",
    discriminator: [197, 238, 165, 167, 191, 219, 156, 230],
    accounts: ["config", "user", "material_mints", "energy_account", "model_state", "signal_mint", "power_mint", "circuit_mint", "compute_mint", "user_signal", "user_power", "user_circuit", "user_compute", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "start_exploration_commit",
    discriminator: [58, 145, 149, 221, 209, 9, 12, 173],
    accounts: ["config", "authority", "material_mints", "user", "exploration_state", "tool_mint", "tool", "auth", "exploration_commit", "data_mint", "user_data", "circuit_mint", "user_circuit", "silicon_mint", "user_silicon", "dataset_mint", "user_dataset", "escrow_data", "escrow_circuit", "escrow_silicon", "escrow_dataset", "vrf_slot", "recent_slothashes", "token_program", "system_program"],
    actorIndexes: [3],
    signerIndexes: [1, 3],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "start_signal_processing",
    discriminator: [110, 224, 122, 194, 231, 136, 134, 202],
    accounts: ["config", "user", "material_mints", "energy_account", "signal_state", "synapse_mint", "silicon_mint", "user_synapse", "user_silicon", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "start_mining",
    discriminator: [108, 28, 69, 67, 54, 120, 245, 196],
    accounts: ["config", "user", "tool", "mint", "player", "vault", "vault_token", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "sweep_gas_fees",
    discriminator: [114, 3, 27, 208, 121, 220, 139, 7],
    accounts: ["config", "authority", "gastank", "treasury", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "unstake",
    discriminator: [90, 95, 107, 42, 205, 124, 50, 225],
    accounts: ["config", "user", "tool", "mint", "user_token", "gastank", "vault", "vault_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "upgrade_exploration_tier",
    discriminator: [36, 77, 217, 211, 252, 176, 30, 108],
    accounts: ["config", "user", "exploration_state", "circuit_mint", "user_circuit", "silicon_mint", "user_silicon", "data_mint", "user_data", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "weather_crank",
    discriminator: [116, 31, 101, 128, 172, 213, 119, 144],
    accounts: ["config", "cranker", "weather_state", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "withdraw_gas",
    discriminator: [35, 60, 150, 196, 226, 110, 54, 45],
    accounts: ["config", "user", "gastank", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "mint_resource_once",
    discriminator: [112, 16, 85, 114, 236, 4, 67, 139],
    accounts: ["config", "material_mints", "authority", "auth", "mint", "token_account", "treasury_token", "payer", "player", "issuance_cap", "token_program", "reward_receipt", "system_program"],
    actorIndexes: [7],
    signerIndexes: [2, 7],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "marketplace_buy_bounded",
    discriminator: [219, 1, 7, 251, 90, 189, 167, 48],
    accounts: ["config", "buyer", "seller", "treasury", "mint", "tool", "listing", "listing_vault", "buyer_token", "token_program", "system_program"],
    actorIndexes: [1, 2],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "init_issuance_cap",
    discriminator: [7, 110, 74, 57, 227, 136, 110, 214],
    accounts: ["config", "authority", "issuance_cap", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_issuance_cap",
    discriminator: [227, 134, 78, 85, 122, 198, 113, 59],
    accounts: ["config", "authority", "issuance_cap"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_pending_authority",
    discriminator: [175, 71, 167, 223, 49, 144, 102, 193],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "accept_authority",
    discriminator: [107, 86, 198, 91, 33, 12, 107, 160],
    accounts: ["config", "new_authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "cancel_pending_authority",
    discriminator: [155, 52, 245, 225, 85, 73, 58, 238],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_mining_enabled",
    discriminator: [240, 237, 205, 117, 79, 7, 125, 116],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "init_vault_guard",
    discriminator: [20, 12, 78, 107, 5, 169, 61, 101],
    accounts: ["config", "authority", "mint", "vault_guard", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_vault_guard",
    discriminator: [188, 146, 45, 181, 231, 183, 48, 53],
    accounts: ["config", "authority", "mint", "vault_guard"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_supply_cap",
    discriminator: [26, 229, 174, 213, 12, 59, 220, 71],
    accounts: ["config", "authority", "material_mints"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "register_collector_mint",
    discriminator: [230, 133, 88, 35, 115, 148, 172, 128],
    accounts: ["config", "authority", "mint", "entry", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "revoke_collector_mint",
    discriminator: [45, 151, 59, 119, 159, 240, 101, 86],
    accounts: ["config", "authority", "mint", "entry"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "refund_lottery_round",
    discriminator: [134, 87, 211, 115, 122, 237, 217, 204],
    accounts: ["config", "payer", "round", "treasury"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "migrate_config_v2",
    discriminator: [21, 39, 88, 172, 254, 205, 30, 141],
    accounts: ["config", "authority", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_roles",
    discriminator: [119, 86, 129, 161, 55, 23, 250, 12],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "emergency_stop",
    discriminator: [179, 143, 200, 137, 108, 245, 248, 35],
    accounts: ["config", "caller"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_cashout_frozen",
    discriminator: [188, 201, 38, 248, 184, 63, 152, 137],
    accounts: ["config", "authority"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "rental_start_bounded",
    discriminator: [254, 53, 210, 91, 122, 245, 9, 4],
    accounts: ["config", "renter", "mint", "tool", "rental_listing", "owner", "treasury", "rental_agreement", "rental_vault", "system_program"],
    actorIndexes: [1, 5],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "rental_delist",
    discriminator: [179, 203, 85, 127, 147, 27, 104, 72],
    accounts: ["config", "caller", "mint", "tool", "rental_listing", "lister", "rental_vault", "owner_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "auction_cancel",
    discriminator: [252, 86, 251, 18, 251, 20, 71, 115],
    accounts: ["config", "seller", "mint", "auction", "auction_vault", "seller_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "vrf_pool_add",
    discriminator: [234, 143, 61, 230, 212, 57, 8, 234],
    accounts: ["config", "operator", "vrf_slot", "token_program", "associated_token_program", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "vrf_pool_set_retired",
    discriminator: [145, 60, 229, 148, 74, 247, 213, 200],
    accounts: ["config", "operator", "vrf_slot"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "vrf_slot_recover",
    discriminator: [4, 108, 67, 220, 83, 132, 241, 108],
    accounts: ["config", "operator", "vrf_slot", "holder"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "reroll_random_expire",
    discriminator: [165, 118, 63, 210, 134, 116, 167, 250],
    accounts: ["config", "cranker", "reroll_commit", "user", "treasury", "vrf_slot", "recent_slothashes", "new_mint", "new_token", "new_tool_data", "auth", "token_program", "associated_token_program", "system_program", "tool_metadata_registry", "metadata", "token_metadata_program"],
    actorIndexes: [1, 3],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "explore_expire",
    discriminator: [95, 254, 71, 97, 162, 245, 109, 180],
    accounts: ["config", "material_mints", "exploration_commit", "user", "vrf_slot", "recent_slothashes", "auth", "data_mint", "user_data", "escrow_data", "circuit_mint", "user_circuit", "escrow_circuit", "silicon_mint", "user_silicon", "escrow_silicon", "dataset_mint", "user_dataset", "escrow_dataset", "token_program"],
    actorIndexes: [3],
    signerIndexes: [],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "expire_lottery_draw",
    discriminator: [194, 243, 73, 116, 68, 189, 235, 166],
    accounts: ["config", "lottery_round", "vrf_slot", "recent_slothashes"],
    actorIndexes: [],
    signerIndexes: [],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "refund_lottery_ticket",
    discriminator: [111, 4, 125, 238, 244, 22, 54, 99],
    accounts: ["config", "lottery_round", "lottery_ticket", "buyer"],
    actorIndexes: [3],
    signerIndexes: [],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "place_buy_order_v2",
    discriminator: [247, 218, 160, 245, 7, 231, 160, 124],
    accounts: ["config", "maker", "mint", "material_mints", "order", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "place_sell_order_v2",
    discriminator: [81, 69, 48, 185, 155, 116, 212, 158],
    accounts: ["config", "maker", "mint", "material_mints", "maker_token", "order", "order_vault", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "cancel_buy_order_v2",
    discriminator: [209, 122, 46, 175, 34, 196, 203, 152],
    accounts: ["config", "maker", "mint", "order"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "cancel_sell_order_v2",
    discriminator: [111, 136, 76, 159, 176, 255, 114, 49],
    accounts: ["config", "maker", "mint", "order", "order_vault", "maker_token", "token_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "match_resource_orders_v2",
    discriminator: [125, 171, 84, 144, 102, 255, 14, 220],
    accounts: ["config", "material_mints", "mint", "buy_order", "sell_order", "seller", "treasury", "sell_vault", "buyer_token", "token_program"],
    actorIndexes: [5],
    signerIndexes: [],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "reset_for_rebirth",
    discriminator: [255, 181, 123, 174, 107, 241, 223, 99],
    accounts: ["config", "operator", "user", "player", "season", "season_pass", "material_mints", "token_program"],
    actorIndexes: [2],
    signerIndexes: [1, 2],
    authorityOnly: false,
    trailingAccounts: "pairs",
  },
  {
    name: "transfer_tool",
    discriminator: [113, 133, 218, 29, 218, 58, 56, 24],
    accounts: ["sender", "mint", "sender_token", "recipient", "recipient_token", "tool_data", "token_program"],
    actorIndexes: [0, 3],
    signerIndexes: [0],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "sync_tool_owner",
    discriminator: [86, 255, 249, 230, 115, 219, 123, 96],
    accounts: ["holder", "mint", "tool", "holder_token"],
    actorIndexes: [0],
    signerIndexes: [0],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "init_season_pass",
    discriminator: [239, 143, 156, 204, 138, 196, 32, 215],
    accounts: ["config", "player", "season", "season_pass", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "init_player",
    discriminator: [114, 27, 219, 144, 50, 15, 228, 66],
    accounts: ["player", "player_profile", "system_program"],
    actorIndexes: [0],
    signerIndexes: [0],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "exchange_data_energy",
    discriminator: [120, 159, 79, 186, 250, 65, 83, 195],
    accounts: ["config", "user", "energy_account", "data_mint", "user_data", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "use_flask",
    discriminator: [195, 18, 130, 61, 57, 11, 101, 135],
    accounts: ["config", "user", "material_mints", "energy_account", "flask_mint", "user_flask", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },
  {
    name: "set_issuance_lifetime_baseline",
    discriminator: [95, 161, 68, 77, 14, 215, 205, 85],
    accounts: ["config", "authority", "material_mints", "issuance_cap", "mint"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "set_tool_metadata_uris",
    discriminator: [198, 98, 41, 32, 64, 50, 152, 170],
    accounts: ["config", "authority", "tool_metadata_registry", "system_program"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "claim_premium_season_reward",
    discriminator: [232, 33, 140, 20, 95, 238, 72, 199],
    accounts: ["config", "authority", "material_mints", "season", "season_pass", "premium_claims", "silicon_mint", "user_silicon", "auth", "token_program", "issuance_cap_silicon"],
    actorIndexes: [],
    signerIndexes: [1],
    authorityOnly: true,
    trailingAccounts: null,
  },
  {
    name: "seal_laboratory",
    discriminator: [45, 254, 248, 15, 161, 154, 213, 105],
    accounts: ["config", "user", "material_mints", "auth", "finale", "model_mint", "user_model", "cryo_fluid_mint", "user_cryo_fluid", "volt_fluid_mint", "user_volt_fluid", "bio_fluid_mint", "user_bio_fluid", "nano_fluid_mint", "user_nano_fluid", "quantum_fluid_mint", "user_quantum_fluid", "amber_quartz_mint", "user_amber_quartz", "soul_core_mint", "user_soul_core", "issuance_cap_soul", "token_program", "system_program"],
    actorIndexes: [1],
    signerIndexes: [1],
    authorityOnly: false,
    trailingAccounts: null,
  },

];

const BY_DISCRIMINATOR: Map<string, CoreInstructionSpec> = new Map(
  CORE_INSTRUCTIONS.map((spec) => [spec.discriminator.join(","), spec]),
);

/** Resolve a raw instruction to its aof-core spec, or undefined when the
 * discriminator is unknown to this build of the program. */
export function coreInstructionSpec(
  programId: string,
  data: Uint8Array,
  coreProgramId: string,
): CoreInstructionSpec | undefined {
  if (programId !== coreProgramId || data.length < 8) return undefined;
  return BY_DISCRIMINATOR.get(Array.from(data.slice(0, 8)).join(","));
}
