import type { Language } from './translations';

type Copy = {
  loading: string; failed: string; retry: string; scope: string;
  filter: string; refresh: string; records: string; noRecords: string; noMatches: string;
  user: string; method: string; status: string; requestBody: (count: number) => string;
  success: string; failure: string; unknown: string;
};

/** Unmounted, admin-only audit screen. Server action IDs and metadata are data, not translated labels. */
export const adminAuditCopy: Record<Language, Copy> = {
  ru: { loading: 'Читаем журнал…', failed: 'Не удалось прочитать журнал. Доступ и состояние записей неизвестны.', retry: 'Повторить запрос', scope: 'Журнал событий сервера; это не полный архив действий в сети.', filter: 'Поиск по пользователю или действию', refresh: 'Обновить', records: 'Записей:', noRecords: 'Записей нет', noMatches: 'Совпадений нет', user: 'Пользователь:', method: 'Метод:', status: 'Статус:', requestBody: count => `Тело запроса (полей: ${count})`, success: 'УСПЕШНО', failure: 'ОШИБКА', unknown: 'НЕИЗВЕСТНО' },
  en: { loading: 'Loading the audit log…', failed: 'Could not read the audit log. Access and record status are unknown.', retry: 'Try again', scope: 'Server event log; not a complete record of on-chain activity.', filter: 'Search by user or action', refresh: 'Refresh', records: 'Records:', noRecords: 'No records', noMatches: 'No matches', user: 'User:', method: 'Method:', status: 'Status:', requestBody: count => `Request body (${count} fields)`, success: 'SUCCESS', failure: 'FAILED', unknown: 'UNKNOWN' },
  pt: { loading: 'A carregar o registo de auditoria…', failed: 'Não foi possível ler o registo. O acesso e o estado dos registos são desconhecidos.', retry: 'Tentar novamente', scope: 'Registo de eventos do servidor; não é um histórico completo das ações na rede.', filter: 'Pesquisar por utilizador ou ação', refresh: 'Atualizar', records: 'Registos:', noRecords: 'Não há registos', noMatches: 'Sem resultados', user: 'Utilizador:', method: 'Método:', status: 'Estado:', requestBody: count => `Corpo do pedido (${count} campos)`, success: 'SUCESSO', failure: 'FALHA', unknown: 'DESCONHECIDO' },
  es: { loading: 'Cargando el registro de auditoría…', failed: 'No se pudo leer el registro. Se desconoce el acceso y el estado de las entradas.', retry: 'Volver a intentar', scope: 'Registro de eventos del servidor; no es un historial completo de las acciones en la cadena.', filter: 'Buscar por usuario o acción', refresh: 'Actualizar', records: 'Entradas:', noRecords: 'No hay entradas', noMatches: 'Sin coincidencias', user: 'Usuario:', method: 'Método:', status: 'Estado:', requestBody: count => `Cuerpo de la solicitud (${count} campos)`, success: 'ÉXITO', failure: 'FALLO', unknown: 'DESCONOCIDO' },
  vi: { loading: 'Đang tải nhật ký kiểm tra…', failed: 'Không thể đọc nhật ký. Chưa rõ quyền truy cập và trạng thái bản ghi.', retry: 'Thử lại', scope: 'Nhật ký sự kiện máy chủ; không phải toàn bộ lịch sử hoạt động trên chuỗi.', filter: 'Tìm theo người dùng hoặc thao tác', refresh: 'Làm mới', records: 'Bản ghi:', noRecords: 'Chưa có bản ghi', noMatches: 'Không có kết quả', user: 'Người dùng:', method: 'Phương thức:', status: 'Trạng thái:', requestBody: count => `Nội dung yêu cầu (${count} trường)`, success: 'THÀNH CÔNG', failure: 'THẤT BẠI', unknown: 'CHƯA RÕ' },
  id: { loading: 'Memuat log audit…', failed: 'Log audit tidak dapat dibaca. Akses dan status catatan belum diketahui.', retry: 'Coba lagi', scope: 'Log peristiwa server; bukan riwayat lengkap aktivitas di blockchain.', filter: 'Cari berdasarkan pengguna atau tindakan', refresh: 'Segarkan', records: 'Catatan:', noRecords: 'Belum ada catatan', noMatches: 'Tidak ada hasil', user: 'Pengguna:', method: 'Metode:', status: 'Status:', requestBody: count => `Isi permintaan (${count} kolom)`, success: 'BERHASIL', failure: 'GAGAL', unknown: 'BELUM DIKETAHUI' },
  fil: { loading: 'Kinukuha ang talaan ng audit…', failed: 'Hindi mabasa ang talaan. Hindi pa alam ang access at katayuan ng mga entry.', retry: 'Subukan muli', scope: 'Talaan ng mga event sa server; hindi ito kumpletong kasaysayan ng mga gawaing on-chain.', filter: 'Hanapin ayon sa user o gawain', refresh: 'I-refresh', records: 'Mga entry:', noRecords: 'Wala pang entry', noMatches: 'Walang tugma', user: 'Gumagamit:', method: 'Paraan:', status: 'Katayuan:', requestBody: count => `Laman ng request (${count} field)`, success: 'NAGTAGUMPAY', failure: 'NABIGO', unknown: 'HINDI ALAM' },
};
