import type { Language } from './translations';

type Copy = { heading: string; summary: string; hash: string; secret: string; idle: string; committed: string; valid: string; invalid: string; seal: string; reveal: string; again: string; section: string };
export const commitLabels: Record<Language, Copy> = {
  ru: { heading: 'Запечатай запись. Затем проверь.', summary: 'Локальное демо SHA-256, без транзакции.', hash: 'Хеш', secret: 'Секрет', idle: 'Готово к проверке.', committed: 'Запись запечатана.', valid: 'Хеш совпал.', invalid: 'Хеш не совпал.', seal: 'Запечатать', reveal: 'Раскрыть и сверить', again: 'Ещё раз', section: 'Проверь обещание' },
  en: { heading: 'Seal the record. Then verify it.', summary: 'A local SHA-256 demonstration. No transaction.', hash: 'Hash', secret: 'Secret', idle: 'Ready to verify.', committed: 'Record sealed.', valid: 'The hashes match.', invalid: 'The hashes do not match.', seal: 'Seal', reveal: 'Reveal and verify', again: 'Try again', section: 'Verify the promise' },
  pt: { heading: 'Sele o registro. Depois, confira.', summary: 'Uma demonstração local de SHA-256. Sem transação.', hash: 'Hash', secret: 'Segredo', idle: 'Pronto para conferir.', committed: 'Registro selado.', valid: 'Os hashes coincidem.', invalid: 'Os hashes não coincidem.', seal: 'Selar', reveal: 'Revelar e conferir', again: 'Tentar novamente', section: 'Confira a promessa' },
  es: { heading: 'Sella el registro. Después, compruébalo.', summary: 'Una demostración local de SHA-256. Sin transacción.', hash: 'Hash', secret: 'Secreto', idle: 'Listo para verificar.', committed: 'Registro sellado.', valid: 'Los hashes coinciden.', invalid: 'Los hashes no coinciden.', seal: 'Sellar', reveal: 'Revelar y comprobar', again: 'Otra vez', section: 'Comprueba la promesa' },
  vi: { heading: 'Niêm phong bản ghi, rồi tự kiểm chứng.', summary: 'Bản minh họa SHA-256 chạy trên thiết bị. Không có giao dịch.', hash: 'Mã băm', secret: 'Giá trị bí mật', idle: 'Sẵn sàng kiểm chứng.', committed: 'Đã niêm phong bản ghi.', valid: 'Hai mã băm khớp nhau.', invalid: 'Hai mã băm không khớp.', seal: 'Niêm phong', reveal: 'Mở và kiểm chứng', again: 'Thử lại', section: 'Kiểm chứng lời hứa' },
  id: { heading: 'Segel catatannya, lalu verifikasi.', summary: 'Demonstrasi SHA-256 secara lokal. Tanpa transaksi.', hash: 'Hash', secret: 'Rahasia', idle: 'Siap diverifikasi.', committed: 'Catatan telah disegel.', valid: 'Kedua hash cocok.', invalid: 'Kedua hash tidak cocok.', seal: 'Segel', reveal: 'Buka dan verifikasi', again: 'Coba lagi', section: 'Verifikasi janjinya' },
  fil: { heading: 'Selyuhan ang tala. Saka ito beripikahin.', summary: 'Lokal na pagpapakita ng SHA-256. Walang transaksyon.', hash: 'Hash', secret: 'Lihim', idle: 'Handa nang beripikahin.', committed: 'Naselyuhan ang tala.', valid: 'Magkatugma ang mga hash.', invalid: 'Hindi magkatugma ang mga hash.', seal: 'Selyuhan', reveal: 'Buksan at beripikahin', again: 'Subukan muli', section: 'Beripikahin ang pangako' },
};
