import type { Language } from './translations';

type Building = 'plasma_cutter' | 'silicon_extractor' | 'data_harvester' | 'quantum_transmitter' | 'neural_seeder';
type Copy = {
  title: string; lead: string; disabled: string; connectWallet: string; failed: string; starting: string;
  opening: string; completed: string; building: string; tool: string;
  legendBuilding: string; mining: string; expansion: string; emptySlot: string;
  unknownLoad: string; powerStopped: string; powerGain: (rate: number) => string;
  structures: string; toolsUnknown: string; toolsLoading: string; freeTools: string;
  durability: string; collect: string; collectDisabled: string; miningInProgress: string;
  start: string; startDisabled: string; disabledNote: string; fineTuning: string;
  close: string; buildings: Record<Building, string>;
};
export const farmPlotCopy: Record<Language, Copy> = {
  ru: { title: 'Мой участок', lead: 'Инструменты в стойке становятся постройками на участке.', disabled: 'Добыча на участке ещё не включена — идёт проверка правил сети', connectWallet: 'Подключите кошелёк', failed: 'Операция не выполнена', starting: 'Экстрактор запущен…', opening: 'Открываем контейнер…', completed: 'Готово', building: 'Постройка', tool: 'Инструмент', legendBuilding: 'постройка из инструмента в стойке', mining: 'майнит', expansion: 'расширение', emptySlot: 'пустая лунка', unknownLoad: 'Нагрузка сети неизвестна', powerStopped: 'Накопление энергопотока остановлено', powerGain: rate => `Накопление энергопотока: ${rate}/час`, structures: 'Построек на участке', toolsUnknown: 'Инструменты недоступны из сети — счётчики неизвестны', toolsLoading: 'Читаем инструменты…', freeTools: 'В инвентаре (не в стойке)', durability: 'прочность', collect: 'Забрать добычу', collectDisabled: 'Сбор ещё не включён', miningInProgress: 'Идёт добыча — вернись, когда экстрактор закончит', start: 'Начать добычу', startDisabled: 'Добыча ещё не включена', disabledNote: 'Добыча включится после проверки контракта в тестовой сети. Инструменты и постройки уже сохранены.', fineTuning: 'Тонкая настройка — во вкладке «Инструменты»', close: 'Закрыть', buildings: { plasma_cutter: 'Плазменный цех', silicon_extractor: 'Кремниевая шахта', data_harvester: 'Пост сбора данных', quantum_transmitter: 'Квантовая вышка', neural_seeder: 'Станция засева' } },
  en: { title: 'My plot', lead: 'Tools on the rack become structures on your plot.', disabled: 'Plot mining is not available yet: the on-chain rules are still being verified', connectWallet: 'Connect your wallet', failed: 'Operation failed', starting: 'Starting the extractor…', opening: 'Opening the container…', completed: 'Done', building: 'Structure', tool: 'Tool', legendBuilding: 'structure built from a racked tool', mining: 'mining', expansion: 'expansion', emptySlot: 'empty slot', unknownLoad: 'Network load unknown', powerStopped: 'Power flow accumulation paused', powerGain: rate => `Power flow accumulation: ${rate}/hour`, structures: 'Structures on plot', toolsUnknown: 'Tools are unavailable from the network; counts are unknown', toolsLoading: 'Loading tools…', freeTools: 'In inventory (not on rack)', durability: 'durability', collect: 'Collect output', collectDisabled: 'Collection is not available yet', miningInProgress: 'Mining in progress: return when the extractor finishes', start: 'Start mining', startDisabled: 'Mining is not available yet', disabledNote: 'Mining will be enabled after the contract passes testnet verification. Your tools and structures are already saved.', fineTuning: 'Adjust your setup on the Tools tab', close: 'Close', buildings: { plasma_cutter: 'Plasma workshop', silicon_extractor: 'Silicon mine', data_harvester: 'Data collection post', quantum_transmitter: 'Quantum tower', neural_seeder: 'Cultivation station' } },
  pt: { title: 'Meu terreno', lead: 'Ferramentas na estante viram estruturas no terreno.', disabled: 'A extração no terreno ainda não está disponível: as regras da rede estão em verificação', connectWallet: 'Conecte sua carteira', failed: 'A operação falhou', starting: 'Iniciando o extrator…', opening: 'Abrindo o recipiente…', completed: 'Concluído', building: 'Estrutura', tool: 'Ferramenta', legendBuilding: 'estrutura de ferramenta na estante', mining: 'extraindo', expansion: 'expansão', emptySlot: 'espaço livre', unknownLoad: 'Carga da rede desconhecida', powerStopped: 'Acúmulo de energia interrompido', powerGain: rate => `Acúmulo de energia: ${rate}/hora`, structures: 'Estruturas no terreno', toolsUnknown: 'Ferramentas indisponíveis na rede; quantidades desconhecidas', toolsLoading: 'Carregando ferramentas…', freeTools: 'No inventário (fora da estante)', durability: 'durabilidade', collect: 'Coletar produção', collectDisabled: 'Coleta ainda indisponível', miningInProgress: 'Extração em andamento: volte quando o extrator terminar', start: 'Iniciar extração', startDisabled: 'Extração ainda indisponível', disabledNote: 'A extração será ativada após a verificação do contrato na rede de testes. Ferramentas e estruturas já estão salvas.', fineTuning: 'Ajuste os detalhes na aba Ferramentas', close: 'Fechar', buildings: { plasma_cutter: 'Oficina de plasma', silicon_extractor: 'Mina de silício', data_harvester: 'Posto de coleta de dados', quantum_transmitter: 'Torre quântica', neural_seeder: 'Estação de cultivo' } },
  es: { title: 'Mi parcela', lead: 'Las herramientas del estante se convierten en estructuras en la parcela.', disabled: 'La extracción en la parcela aún no está disponible: se están verificando las reglas de la red', connectWallet: 'Conecta tu cartera', failed: 'La operación falló', starting: 'Iniciando el extractor…', opening: 'Abriendo el recipiente…', completed: 'Listo', building: 'Estructura', tool: 'Herramienta', legendBuilding: 'estructura de una herramienta del estante', mining: 'extrayendo', expansion: 'ampliación', emptySlot: 'espacio libre', unknownLoad: 'Carga de la red desconocida', powerStopped: 'Acumulación de energía detenida', powerGain: rate => `Acumulación de energía: ${rate}/hora`, structures: 'Estructuras en la parcela', toolsUnknown: 'Herramientas no disponibles en la red; cantidades desconocidas', toolsLoading: 'Cargando herramientas…', freeTools: 'En el inventario (fuera del estante)', durability: 'durabilidad', collect: 'Recoger producción', collectDisabled: 'La recolección aún no está disponible', miningInProgress: 'Extracción en curso: vuelve cuando termine el extractor', start: 'Iniciar extracción', startDisabled: 'La extracción aún no está disponible', disabledNote: 'La extracción se activará cuando el contrato supere las pruebas en testnet. Las herramientas y estructuras ya están guardadas.', fineTuning: 'Ajusta los detalles en la pestaña Herramientas', close: 'Cerrar', buildings: { plasma_cutter: 'Taller de plasma', silicon_extractor: 'Mina de silicio', data_harvester: 'Puesto de recogida de datos', quantum_transmitter: 'Torre cuántica', neural_seeder: 'Estación de cultivo' } },
  vi: { title: 'Khu đất của tôi', lead: 'Công cụ đặt trên giá trở thành công trình trong khu đất.', disabled: 'Chưa bật khai thác trong khu đất: quy tắc trên chuỗi vẫn đang được kiểm tra', connectWallet: 'Kết nối ví', failed: 'Thao tác thất bại', starting: 'Đang khởi động máy chiết…', opening: 'Đang mở kho chứa…', completed: 'Hoàn tất', building: 'Công trình', tool: 'Công cụ', legendBuilding: 'công trình từ công cụ trên giá', mining: 'đang khai thác', expansion: 'mở rộng', emptySlot: 'ô trống', unknownLoad: 'Chưa rõ tải mạng', powerStopped: 'Đã dừng tích lũy dòng năng lượng', powerGain: rate => `Tích lũy dòng năng lượng: ${rate}/giờ`, structures: 'Công trình trong khu đất', toolsUnknown: 'Không thể tải công cụ từ mạng; chưa rõ số lượng', toolsLoading: 'Đang tải công cụ…', freeTools: 'Trong kho (không ở trên giá)', durability: 'độ bền', collect: 'Thu sản lượng', collectDisabled: 'Chưa bật thu sản lượng', miningInProgress: 'Đang khai thác: quay lại khi máy chiết hoàn thành', start: 'Bắt đầu khai thác', startDisabled: 'Chưa bật khai thác', disabledNote: 'Khai thác sẽ được bật sau khi hợp đồng được kiểm tra trên mạng thử nghiệm. Công cụ và công trình đã được lưu.', fineTuning: 'Điều chỉnh trong thẻ Công cụ', close: 'Đóng', buildings: { plasma_cutter: 'Xưởng plasma', silicon_extractor: 'Mỏ silic', data_harvester: 'Trạm thu thập dữ liệu', quantum_transmitter: 'Tháp lượng tử', neural_seeder: 'Trạm nuôi cấy' } },
  id: { title: 'Lahanku', lead: 'Peralatan di rak menjadi bangunan di lahanmu.', disabled: 'Penambangan di lahan belum tersedia: aturan di blockchain masih diverifikasi', connectWallet: 'Hubungkan dompet', failed: 'Tindakan gagal', starting: 'Menjalankan ekstraktor…', opening: 'Membuka wadah…', completed: 'Selesai', building: 'Bangunan', tool: 'Peralatan', legendBuilding: 'bangunan dari peralatan di rak', mining: 'menambang', expansion: 'perluasan', emptySlot: 'slot kosong', unknownLoad: 'Beban jaringan belum diketahui', powerStopped: 'Akumulasi aliran daya berhenti', powerGain: rate => `Akumulasi aliran daya: ${rate}/jam`, structures: 'Bangunan di lahan', toolsUnknown: 'Peralatan tidak tersedia dari jaringan; jumlah belum diketahui', toolsLoading: 'Memuat peralatan…', freeTools: 'Di inventaris (bukan di rak)', durability: 'daya tahan', collect: 'Ambil hasil', collectDisabled: 'Pengambilan belum tersedia', miningInProgress: 'Penambangan berlangsung: kembali setelah ekstraktor selesai', start: 'Mulai menambang', startDisabled: 'Penambangan belum tersedia', disabledNote: 'Penambangan akan diaktifkan setelah kontrak lolos pemeriksaan di testnet. Peralatan dan bangunanmu sudah tersimpan.', fineTuning: 'Atur selengkapnya di tab Peralatan', close: 'Tutup', buildings: { plasma_cutter: 'Bengkel plasma', silicon_extractor: 'Tambang silikon', data_harvester: 'Pos pengumpulan data', quantum_transmitter: 'Menara kuantum', neural_seeder: 'Stasiun kultivasi' } },
  fil: { title: 'Aking lote', lead: 'Nagiging istruktura sa lote ang mga kagamitan sa istante.', disabled: 'Hindi pa puwedeng magmina sa lote: sinusuri pa ang mga patakaran sa blockchain', connectWallet: 'Ikonekta ang wallet', failed: 'Nabigo ang gawain', starting: 'Sinisimulan ang pangkuha…', opening: 'Binubuksan ang lalagyan…', completed: 'Tapos na', building: 'Istruktura', tool: 'Kagamitan', legendBuilding: 'istruktura mula sa kagamitang nasa istante', mining: 'nagmimina', expansion: 'pagpapalawak', emptySlot: 'bakanteng puwesto', unknownLoad: 'Hindi alam ang pasan ng network', powerStopped: 'Huminto ang pag-ipon ng daloy ng enerhiya', powerGain: rate => `Pag-ipon ng daloy ng enerhiya: ${rate}/oras`, structures: 'Istruktura sa lote', toolsUnknown: 'Hindi makuha ang kagamitan mula sa network; hindi alam ang bilang', toolsLoading: 'Kinukuha ang mga kagamitan…', freeTools: 'Sa imbentaryo (wala sa istante)', durability: 'tibay', collect: 'Kunin ang ani', collectDisabled: 'Hindi pa puwedeng kunin ang ani', miningInProgress: 'Nagpapatuloy ang pagmimina: bumalik kapag tapos na ang pangkuha', start: 'Magsimulang magmina', startDisabled: 'Hindi pa puwedeng magmina', disabledNote: 'Pahihintulutan ang pagmimina kapag nasuri ang kontrata sa testnet. Naka-save na ang kagamitan at istruktura.', fineTuning: 'Ayusin ang detalye sa tab na Mga Kagamitan', close: 'Isara', buildings: { plasma_cutter: 'Pagawaang plasma', silicon_extractor: 'Minahan ng silikon', data_harvester: 'Himpilan ng pagkolekta ng datos', quantum_transmitter: 'Toreng quantum', neural_seeder: 'Istasyon ng pagtatanim' } },
};

// Current tool ids only.
export const buildingKeys: Record<string, Building> = {
  plasma_cutter: 'plasma_cutter',
  silicon_extractor: 'silicon_extractor',
  data_harvester: 'data_harvester',
  quantum_transmitter: 'quantum_transmitter',
  neural_seeder: 'neural_seeder',
};
