import type { Language } from './translations';

const keys = ['back','privileges','friends','activity','curatorQuests','trust','tools','lottery','rating','economyMonitor','seasonPass','economySandbox','portfolio','leaderboard','inbox','trader','exploration','capsules','craft','repair','collection','market','listing','auction','offers','rentals','orderbook','fluids','hotMarket','finale'] as const;
export type GameHeaderId = typeof keys[number];
const row = (labels: readonly string[]): Record<GameHeaderId, string> => {
  if (labels.length !== keys.length) throw new Error('Incomplete game screen translation');
  return Object.fromEntries(keys.map((key, i) => [key, labels[i]])) as Record<GameHeaderId, string>;
};
export const gameHeaders: Record<Language, Record<GameHeaderId, string>> = {
  ru: row(['Назад','Все привилегии','Друзья','Журнал действий','Задания куратора','Индекс доверия','Инструменты','Лотерея','Мой рейтинг','Монитор экономики','Пасс эпохи','Песочница экономики','Портфель','Рейтинг игроков','Сообщения','Торговый агент','Экспедиция','Паки','Крафт','Ремонт','Коллекция','Рынок','Листинг','Аукцион','Офферы','Аренда','Ордербук','Флюиды','Хот-маркет','Печать']),
  en: row(['Back','All privileges','Friends','Activity log','Curator quests','Trust score','Tools','Lottery','My rating','Economy monitor','Season pass','Economy sandbox','Portfolio','Player rankings','Messages','Trading agent','Expedition','Capsules','Craft','Repair','Collection','Market','Listings','Auction','Offers','Rentals','Order book','Fluids','Event market','Seal']),
  pt: row(['Voltar','Todos os privilégios','Amigos','Histórico de ações','Missões do curador','Índice de confiança','Ferramentas','Loteria','Minha classificação','Monitor da economia','Passe da época','Simulador de economia','Portfólio','Classificação dos jogadores','Mensagens','Agente comercial','Expedição','Cápsulas','Criação','Reparo','Coleção','Mercado','Anúncios','Leilão','Propostas','Aluguel','Livro de ofertas','Fluidos','Mercado de eventos','Selo']),
  es: row(['Volver','Todos los privilegios','Amigos','Registro de actividad','Misiones del curador','Índice de confianza','Herramientas','Lotería','Mi clasificación','Monitor económico','Pase de temporada','Simulador económico','Cartera','Clasificación de jugadores','Mensajes','Agente comercial','Expedición','Cápsulas','Fabricación','Reparación','Colección','Mercado','Anuncios','Subasta','Ofertas','Alquiler','Libro de órdenes','Fluidos','Mercado de eventos','Sello']),
  vi: row(['Quay lại','Tất cả đặc quyền','Bạn bè','Nhật ký hoạt động','Nhiệm vụ quản lý','Chỉ số tin cậy','Công cụ','Xổ số','Thứ hạng của tôi','Theo dõi kinh tế','Vé mùa','Mô phỏng kinh tế','Danh mục','Bảng xếp hạng','Tin nhắn','Đại lý giao dịch','Thám hiểm','Hộp vật phẩm','Chế tạo','Sửa chữa','Bộ sưu tập','Chợ','Rao bán','Đấu giá','Đề nghị','Cho thuê','Sổ lệnh','Dung dịch','Chợ sự kiện','Niêm phong']),
  id: row(['Kembali','Semua hak istimewa','Teman','Riwayat aktivitas','Misi kurator','Skor kepercayaan','Peralatan','Lotre','Peringkat saya','Pemantau ekonomi','Tiket musim','Simulasi ekonomi','Portofolio','Peringkat pemain','Pesan','Agen perdagangan','Ekspedisi','Kapsul','Perakitan','Perbaikan','Koleksi','Pasar','Lapak','Lelang','Penawaran','Sewa','Buku pesanan','Cairan','Pasar acara','Segel']),
  fil: row(['Bumalik','Lahat ng pribilehiyo','Mga kaibigan','Talaan ng gawain','Mga gawain ng tagapangalaga','Antas ng tiwala','Mga kagamitan','Loterya','Aking ranggo','Tagasubaybay ng ekonomiya','Pases ng panahon','Simulasyon ng ekonomiya','Portpolyo','Ranggo ng mga manlalaro','Mga mensahe','Ahente sa kalakalan','Ekspedisyon','Mga kapsula','Paggawa','Pagkukumpuni','Koleksiyon','Pamilihan','Listahan','Subasta','Mga alok','Paupahan','Talaan ng order','Mga likido','Pamilihan ng mga kaganapan','Tatak']),
};
