import type { Language } from './translations';

const resourceIds = ['data','circuit','silicon','compute','dataset','neuron','synapse','signal','model','power','blueCore','purpleCore','redCore','clearQuartz','roseQuartz','amberQuartz','quantumBit','neuralChip','photonBit','bioChip','cryoFluid','voltFluid','bioFluid','nanoFluid','quantumFluid','mind','soulCore'] as const;
export type ResourceId = typeof resourceIds[number];
const names = (values: readonly string[]): Record<ResourceId, string> => {
  if (values.length !== resourceIds.length) throw new Error('Resource names missing');
  return Object.fromEntries(resourceIds.map((id, i) => [id, values[i]])) as Record<ResourceId, string>;
};
export const homeResourceNames: Record<Language, Record<ResourceId, string>> = {
  ru: names(['Данные','Схема','Кремний','Вычислительный цикл','Датасет','Нейрон','Синапс','Сигнал','Модель','Энергопоток','Синее ядро','Фиолетовое ядро','Красное ядро','Чистый кварц','Розовый кварц','Янтарный кварц','Квантовый бит','Нейрочип','Фотонный бит','Биочип','Крио-флюид','Вольт-флюид','Био-флюид','Нано-флюид','Квантовый флюид','MIND','Ядро-душа']),
  en: names(['Data','Circuit','Silicon','Compute cycle','Dataset','Neuron','Synapse','Signal','Model','Power flow','Blue core','Purple core','Red core','Clear quartz','Rose quartz','Amber quartz','Quantum bit','Neural chip','Photon bit','Biochip','Cryo fluid','Volt fluid','Bio fluid','Nano fluid','Quantum fluid','MIND','Soul core']),
  pt: names(['Dados','Circuito','Silício','Ciclo de computação','Conjunto de dados','Neurônio','Sinapse','Sinal','Modelo','Fluxo de energia','Núcleo azul','Núcleo roxo','Núcleo vermelho','Quartzo transparente','Quartzo rosa','Quartzo âmbar','Bit quântico','Chip neural','Bit fotônico','Biochip','Fluido criogênico','Fluido elétrico','Biofluido','Nanofluido','Fluido quântico','MIND','Núcleo da alma']),
  es: names(['Datos','Circuito','Silicio','Ciclo de cálculo','Conjunto de datos','Neurona','Sinapsis','Señal','Modelo','Flujo de energía','Núcleo azul','Núcleo violeta','Núcleo rojo','Cuarzo transparente','Cuarzo rosa','Cuarzo ámbar','Bit cuántico','Chip neuronal','Bit fotónico','Biochip','Fluido criogénico','Fluido eléctrico','Biofluido','Nanofluido','Fluido cuántico','MIND','Núcleo del alma']),
  vi: names(['Dữ liệu','Mạch','Silic','Chu kỳ tính toán','Tập dữ liệu','Nơron','Khớp thần kinh','Tín hiệu','Mô hình','Dòng năng lượng','Lõi xanh lam','Lõi tím','Lõi đỏ','Thạch anh trong','Thạch anh hồng','Thạch anh hổ phách','Bit lượng tử','Chip thần kinh','Bit photon','Chip sinh học','Dung dịch làm lạnh','Dung dịch điện','Dung dịch sinh học','Dung dịch nano','Dung dịch lượng tử','MIND','Lõi linh hồn']),
  id: names(['Data','Sirkuit','Silikon','Siklus komputasi','Kumpulan data','Neuron','Sinapsis','Sinyal','Model','Aliran daya','Inti biru','Inti ungu','Inti merah','Kuarsa bening','Kuarsa mawar','Kuarsa amber','Bit kuantum','Chip saraf','Bit foton','Biochip','Cairan kriogenik','Cairan volt','Cairan bio','Cairan nano','Cairan kuantum','MIND','Inti jiwa']),
  fil: names(['Data','Sirkito','Silikon','Siklo ng pagkukuwenta','Kalipunan ng datos','Neuron','Sinapsis','Senyal','Modelo','Daloy ng enerhiya','Asul na core','Lilang core','Pulang core','Malinaw na kuwarts','Rosas na kuwarts','Amber na kuwarts','Kuwantum na bit','Neural na chip','Bit ng foton','Biochip','Likidong kriyo','Likidong boltahe','Likidong biyolohikal','Likidong nano','Likidong kuwantum','MIND','Core ng kaluluwa']),
};

export type HomeDetail = { chainTitle: string; samplesTitle: string; material: string; allResources: string; chainCaption: string; leads: readonly string[] };
export const homeDetail: Record<Language, HomeDetail> = {
  ru: { chainTitle: 'Цепочка труда', samplesTitle: 'Потрогай материал', material: 'Материал', allResources: 'Все ресурсы', chainCaption: 'Культивируй → разделяй → обучай. Схема качественная, без норм расхода.', leads: ['Фундамент всех операций.','Конструкционный материал и топливо.','Основа конструкций и чипов.','Топливо для обучения моделей.','Сырьё для продвинутых операций.','Точка входа в производственный цикл.','Следующее звено после культивации.','Основа для обучения модели.'] },
  en: { chainTitle: 'The production chain', samplesTitle: 'Explore the materials', material: 'Material', allResources: 'All resources', chainCaption: 'Cultivate → separate → train. This diagram shows the process, not the required quantities.', leads: ['The foundation of every operation.','A building material and a source of fuel.','The basis of structures and chips.','Fuel for training models.','Raw material for advanced operations.','The beginning of the production cycle.','The next stage after cultivation.','The foundation for training a model.'] },
  pt: { chainTitle: 'Cadeia de produção', samplesTitle: 'Explore os materiais', material: 'Material', allResources: 'Todos os recursos', chainCaption: 'Cultivar → separar → treinar. O diagrama mostra o processo, não as quantidades necessárias.', leads: ['A base de todas as operações.','Material de construção e combustível.','A base das estruturas e dos chips.','Combustível para treinar modelos.','Matéria-prima para operações avançadas.','O início do ciclo de produção.','A próxima etapa após o cultivo.','A base para treinar um modelo.'] },
  es: { chainTitle: 'Cadena de producción', samplesTitle: 'Explora los materiales', material: 'Material', allResources: 'Todos los recursos', chainCaption: 'Cultivar → separar → entrenar. El esquema muestra el proceso, no las cantidades necesarias.', leads: ['La base de todas las operaciones.','Material de construcción y combustible.','La base de estructuras y chips.','Combustible para entrenar modelos.','Materia prima para operaciones avanzadas.','El comienzo del ciclo de producción.','La siguiente etapa tras el cultivo.','La base para entrenar un modelo.'] },
  vi: { chainTitle: 'Chuỗi sản xuất', samplesTitle: 'Khám phá vật liệu', material: 'Vật liệu', allResources: 'Tất cả tài nguyên', chainCaption: 'Nuôi cấy → tách mẫu → huấn luyện. Sơ đồ mô tả quy trình, không thể hiện lượng tiêu hao.', leads: ['Nền tảng của mọi hoạt động.','Vật liệu xây dựng kiêm nhiên liệu.','Nền tảng cho kết cấu và vi mạch.','Nhiên liệu để huấn luyện mô hình.','Nguyên liệu cho hoạt động nâng cao.','Điểm khởi đầu của chu kỳ sản xuất.','Giai đoạn tiếp theo sau khi nuôi cấy.','Nền tảng để huấn luyện mô hình.'] },
  id: { chainTitle: 'Rangkaian produksi', samplesTitle: 'Jelajahi bahan', material: 'Bahan', allResources: 'Semua sumber daya', chainCaption: 'Kultivasi → pemisahan → pelatihan. Diagram ini menunjukkan proses, bukan jumlah yang dibutuhkan.', leads: ['Dasar dari setiap operasi.','Bahan konstruksi sekaligus bahan bakar.','Dasar untuk struktur dan chip.','Bahan bakar untuk melatih model.','Bahan mentah untuk operasi lanjutan.','Awal dari siklus produksi.','Tahap berikutnya setelah kultivasi.','Dasar untuk melatih sebuah model.'] },
  fil: { chainTitle: 'Daloy ng paggawa', samplesTitle: 'Kilalanin ang mga materyales', material: 'Materyal', allResources: 'Lahat ng yaman', chainCaption: 'Magpalago → maghiwalay → magsanay. Daloy ng proseso ito, hindi talaan ng mga kailangang dami.', leads: ['Batayan ng bawat gawain.','Materyales sa paggawa at panggatong.','Pundasyon ng mga estruktura at chip.','Panggatong sa pagsasanay ng mga modelo.','Hilaw na materyales para sa mas masalimuot na gawain.','Simula ng siklo ng paggawa.','Susunod na hakbang matapos magpalago.','Batayan sa pagsasanay ng isang modelo.'] },
};
