import type { Language } from './translations';

export type LabHeroCopy = {
  title: string; sticker: string; connectedMeta: string; disconnectedMeta: string; subtitle: string;
  disconnected: string; networkLost: string; connected: string; pressure: string; noEnergy: string;
  rackA: string; rackB: string; normal: string; noData: string; monitoring: string;
  energy: string; energyMissing: string; gas: string; gasMissing: string; rack: string;
  toolsUnavailable: string; readingTools: string; toolsInRack: string;
  networkLoad: string; weatherMissing: string; powerMultiplier: string;
  connectWallet: string; balancesUnavailable: string;
  load: { sunny: string; rain: string; drought: string; festival: string };
};
export const labHeroCopy: Record<Language, LabHeroCopy> = {
  ru: { title: 'Твоя лаборатория', sticker: 'ЛАБОРАТОРИЯ', connectedMeta: 'КРИОБАНК ОБРАЗЦОВ', disconnectedMeta: 'КОШЕЛЁК НЕ ПОДКЛЮЧЁН', subtitle: 'стойка A · глубокий холод', disconnected: 'кошелёк не подключён', networkLost: 'связь с сетью потеряна', connected: 'связь с сетью', pressure: 'сосуд под давлением', noEnergy: 'энергии в сети нет', rackA: 'Стойка A · базовые', rackB: 'Стойка B · модельная цепочка', normal: 'норма', noData: 'нет данных', monitoring: 'контроль', energy: 'Энергия', energyMissing: 'аккаунта энергии ещё нет в сети', gas: 'Газ', gasMissing: 'газ-бак ещё не создан', rack: 'Стойка', toolsUnavailable: 'инструменты недоступны из сети', readingTools: 'читаем инструменты', toolsInRack: 'инструментов в стойке', networkLoad: 'Нагрузка сети', weatherMissing: 'нет WeatherState', powerMultiplier: 'множитель энергопотока', connectWallet: 'Подключи кошелёк — покажем балансы из сети.', balancesUnavailable: 'Балансы недоступны из сети. Повтори обновление позже.', load: { sunny: 'Номинал', rain: 'Скачок', drought: 'Блэкаут', festival: 'Френзи' } },
  en: { title: 'Your laboratory', sticker: 'LABORATORY', connectedMeta: 'SAMPLE CRYOBANK', disconnectedMeta: 'WALLET NOT CONNECTED', subtitle: 'rack A · deep freeze', disconnected: 'wallet not connected', networkLost: 'network connection lost', connected: 'network connected', pressure: 'vessel pressurized', noEnergy: 'no energy data on-chain', rackA: 'Rack A · base materials', rackB: 'Rack B · model chain', normal: 'normal', noData: 'no data', monitoring: 'monitoring', energy: 'Energy', energyMissing: 'no energy account found on-chain', gas: 'Gas', gasMissing: 'gas tank not created yet', rack: 'Rack', toolsUnavailable: 'tools unavailable from the network', readingTools: 'loading tools', toolsInRack: 'tools in rack', networkLoad: 'Network load', weatherMissing: 'no WeatherState', powerMultiplier: 'power flow multiplier', connectWallet: 'Connect a wallet to see your on-chain balances.', balancesUnavailable: 'On-chain balances are unavailable. Try refreshing later.', load: { sunny: 'Nominal', rain: 'Surge', drought: 'Blackout', festival: 'Frenzy' } },
  pt: { title: 'Seu laboratório', sticker: 'LABORATÓRIO', connectedMeta: 'CRIOBANCO DE AMOSTRAS', disconnectedMeta: 'CARTEIRA DESCONECTADA', subtitle: 'estante A · frio extremo', disconnected: 'carteira desconectada', networkLost: 'conexão com a rede perdida', connected: 'rede conectada', pressure: 'recipiente pressurizado', noEnergy: 'sem dados de energia na rede', rackA: 'Estante A · materiais básicos', rackB: 'Estante B · cadeia de modelos', normal: 'normal', noData: 'sem dados', monitoring: 'monitoramento', energy: 'Energia', energyMissing: 'conta de energia ainda não encontrada na rede', gas: 'Gás', gasMissing: 'tanque de gás ainda não criado', rack: 'Estante', toolsUnavailable: 'ferramentas indisponíveis na rede', readingTools: 'carregando ferramentas', toolsInRack: 'ferramentas na estante', networkLoad: 'Carga da rede', weatherMissing: 'sem WeatherState', powerMultiplier: 'multiplicador do fluxo de energia', connectWallet: 'Conecte sua carteira para ver os saldos na rede.', balancesUnavailable: 'Saldos indisponíveis na rede. Tente atualizar mais tarde.', load: { sunny: 'Nominal', rain: 'Pico', drought: 'Apagão', festival: 'Frenesi' } },
  es: { title: 'Tu laboratorio', sticker: 'LABORATORIO', connectedMeta: 'CRIOBANCO DE MUESTRAS', disconnectedMeta: 'CARTERA DESCONECTADA', subtitle: 'estante A · frío extremo', disconnected: 'cartera desconectada', networkLost: 'se perdió la conexión con la red', connected: 'red conectada', pressure: 'recipiente presurizado', noEnergy: 'sin datos de energía en la red', rackA: 'Estante A · materiales básicos', rackB: 'Estante B · cadena de modelos', normal: 'normal', noData: 'sin datos', monitoring: 'seguimiento', energy: 'Energía', energyMissing: 'aún no hay una cuenta de energía en la red', gas: 'Gas', gasMissing: 'el depósito de gas aún no existe', rack: 'Estante', toolsUnavailable: 'herramientas no disponibles en la red', readingTools: 'cargando herramientas', toolsInRack: 'herramientas en el estante', networkLoad: 'Carga de la red', weatherMissing: 'sin WeatherState', powerMultiplier: 'multiplicador del flujo de energía', connectWallet: 'Conecta tu cartera para ver tus saldos en la red.', balancesUnavailable: 'Los saldos no están disponibles en la red. Vuelve a actualizar más tarde.', load: { sunny: 'Nominal', rain: 'Pico', drought: 'Apagón', festival: 'Frenesí' } },
  vi: { title: 'Phòng thí nghiệm của bạn', sticker: 'PHÒNG THÍ NGHIỆM', connectedMeta: 'KHO LẠNH LƯU MẪU', disconnectedMeta: 'CHƯA KẾT NỐI VÍ', subtitle: 'giá A · đông lạnh sâu', disconnected: 'chưa kết nối ví', networkLost: 'mất kết nối mạng', connected: 'đã kết nối mạng', pressure: 'bình đã tăng áp', noEnergy: 'chưa có dữ liệu năng lượng trên chuỗi', rackA: 'Giá A · vật liệu cơ bản', rackB: 'Giá B · chuỗi mô hình', normal: 'bình thường', noData: 'chưa có dữ liệu', monitoring: 'đang theo dõi', energy: 'Năng lượng', energyMissing: 'chưa tìm thấy tài khoản năng lượng trên chuỗi', gas: 'Gas', gasMissing: 'chưa tạo bình gas', rack: 'Giá', toolsUnavailable: 'không thể tải công cụ từ mạng', readingTools: 'đang tải công cụ', toolsInRack: 'công cụ trên giá', networkLoad: 'Tải mạng', weatherMissing: 'chưa có WeatherState', powerMultiplier: 'hệ số dòng năng lượng', connectWallet: 'Kết nối ví để xem số dư trên chuỗi.', balancesUnavailable: 'Không thể tải số dư trên chuỗi. Hãy thử cập nhật sau.', load: { sunny: 'Thông thường', rain: 'Tăng vọt', drought: 'Mất điện', festival: 'Cực đại' } },
  id: { title: 'Laboratoriummu', sticker: 'LABORATORIUM', connectedMeta: 'BANK KRIO SAMPEL', disconnectedMeta: 'DOMPET BELUM TERHUBUNG', subtitle: 'rak A · pembekuan dalam', disconnected: 'dompet belum terhubung', networkLost: 'koneksi jaringan terputus', connected: 'jaringan terhubung', pressure: 'tabung bertekanan', noEnergy: 'belum ada data energi di blockchain', rackA: 'Rak A · bahan dasar', rackB: 'Rak B · rangkaian model', normal: 'normal', noData: 'tidak ada data', monitoring: 'dipantau', energy: 'Energi', energyMissing: 'akun energi belum ditemukan di blockchain', gas: 'Gas', gasMissing: 'tangki gas belum dibuat', rack: 'Rak', toolsUnavailable: 'peralatan tidak tersedia dari jaringan', readingTools: 'memuat peralatan', toolsInRack: 'peralatan di rak', networkLoad: 'Beban jaringan', weatherMissing: 'WeatherState belum ada', powerMultiplier: 'pengali aliran daya', connectWallet: 'Hubungkan dompet untuk melihat saldomu di blockchain.', balancesUnavailable: 'Saldo di blockchain tidak tersedia. Coba muat ulang nanti.', load: { sunny: 'Normal', rain: 'Lonjakan', drought: 'Pemadaman', festival: 'Puncak' } },
  fil: { title: 'Iyong laboratoryo', sticker: 'LABORATORYO', connectedMeta: 'CRYOBANK NG MGA SAMPLE', disconnectedMeta: 'HINDI NAKAKONEKTA ANG WALLET', subtitle: 'istante A · malamig na imbakan', disconnected: 'hindi nakakonekta ang wallet', networkLost: 'naputol ang koneksyon sa network', connected: 'nakakonekta sa network', pressure: 'may presyon ang sisidlan', noEnergy: 'walang datos ng enerhiya sa blockchain', rackA: 'Istante A · pangunahing materyales', rackB: 'Istante B · daloy ng modelo', normal: 'karaniwan', noData: 'walang datos', monitoring: 'binabantayan', energy: 'Enerhiya', energyMissing: 'wala pang energy account sa blockchain', gas: 'Gas', gasMissing: 'wala pang gas tank', rack: 'Istante', toolsUnavailable: 'hindi makuha ang kagamitan mula sa network', readingTools: 'kinukuha ang mga kagamitan', toolsInRack: 'kagamitan sa istante', networkLoad: 'Pasanin ng network', weatherMissing: 'walang WeatherState', powerMultiplier: 'multiplier ng daloy ng enerhiya', connectWallet: 'Ikonekta ang wallet upang makita ang iyong balanse sa blockchain.', balancesUnavailable: 'Hindi makuha ang balanse sa blockchain. Subukang i-refresh mamaya.', load: { sunny: 'Karaniwan', rain: 'Pagtaas', drought: 'Walang suplay', festival: 'Kasukdulan' } },
};
