import type { Language } from './translations';

export const labLabels: Record<Language, { overview: string; station: string; cultivation: string; separation: string; training: string; expedition: string; fluids: string; capsules: string; craft: string; finale: string; drum: string; lottery: string }> = {
  ru: { overview: 'Обзор', station: 'Сетевая станция', cultivation: 'Культивация', separation: 'Сепарация', training: 'Обучение', expedition: 'Экспедиция', fluids: 'Флюиды', capsules: 'Капсулы', craft: 'Крафт', finale: 'Печать', drum: 'Барабан', lottery: 'Лотерея' },
  en: { overview: 'Overview', station: 'Network station', cultivation: 'Cultivation', separation: 'Separation', training: 'Training', expedition: 'Expedition', fluids: 'Fluids', capsules: 'Capsules', craft: 'Craft', finale: 'Seal', drum: 'Drum', lottery: 'Lottery' },
  pt: { overview: 'Visão geral', station: 'Estação de rede', cultivation: 'Cultivo', separation: 'Separação', training: 'Treinamento', expedition: 'Expedição', fluids: 'Fluidos', capsules: 'Cápsulas', craft: 'Criação', finale: 'Selo', drum: 'Tambor', lottery: 'Loteria' },
  es: { overview: 'Resumen', station: 'Estación de red', cultivation: 'Cultivo', separation: 'Separación', training: 'Entrenamiento', expedition: 'Expedición', fluids: 'Fluidos', capsules: 'Cápsulas', craft: 'Fabricación', finale: 'Sello', drum: 'Tambor', lottery: 'Lotería' },
  vi: { overview: 'Tổng quan', station: 'Trạm mạng', cultivation: 'Nuôi cấy', separation: 'Tách mẫu', training: 'Huấn luyện', expedition: 'Thám hiểm', fluids: 'Dung dịch', capsules: 'Hộp vật phẩm', craft: 'Chế tạo', finale: 'Niêm phong', drum: 'Vòng quay', lottery: 'Xổ số' },
  id: { overview: 'Ringkasan', station: 'Stasiun jaringan', cultivation: 'Kultivasi', separation: 'Pemisahan', training: 'Pelatihan', expedition: 'Ekspedisi', fluids: 'Cairan', capsules: 'Kapsul', craft: 'Perakitan', finale: 'Segel', drum: 'Undian', lottery: 'Lotre' },
  fil: { overview: 'Pangkalahatan', station: 'Istasyon ng network', cultivation: 'Pagpapalago', separation: 'Paghihiwalay', training: 'Pagsasanay', expedition: 'Ekspedisyon', fluids: 'Mga likido', capsules: 'Mga kapsula', craft: 'Paggawa', finale: 'Tatak', drum: 'Tambol', lottery: 'Loterya' },
};
