import type { Language } from './translations';

type Copy = {
  title: string; refresh: string; loading: string; intro: string; listingsUnavailable: string;
  sticker: string; sonarMeta: string; sonarTitle: string; sonarSub: string;
  count: string; cheapest: string; median: string; highest: string;
  yours: string; onMarket: string; signedByYou: string;
  empty: string; emptyHint: string;
  seller: string; you: string; buy: string; cancel: string;
  connect: string; treasuryLoading: string; treasuryUnavailable: string; preparingBuy: string; bought: string;
  preparingCancel: string; cancelled: string; selectTool: string;
  preparingList: string; listed: string; actionFailed: string; walletChanged: string;
  listTitle: string; fixedPrice: string; connectTools: string; readingTools: string;
  toolsUnavailable: string; noTools: string; price: string; invalidPrice: string; list: string;
  toolUnavailable: string;
  categoryLabel: string;
  allTools: string;
  categoryEmpty: string;
};
export const listingCopy: Record<Language, Copy> = {
  ru: {
    title: 'Листинги', refresh: 'Обновить', loading: 'Читаем прилавки из сети…', intro: 'Инструменты продаются за SOL по фиксированной цене. Проверьте сумму перед подтверждением в кошельке.', listingsUnavailable: 'Не удалось прочитать листинги из сети. Пустой прилавок не означает ошибку чтения.',
    sticker: 'ВИТРИНА', sonarMeta: 'ЭХОЛОТ ЦЕН', sonarTitle: 'Развёртка прилавков', sonarSub: 'ближе к центру — дешевле', count: 'Лотов', cheapest: 'Самый дешёвый', median: 'Средний по порядку', highest: 'Самый дорогой', yours: 'Ваших', onMarket: 'на прилавках сейчас', signedByYou: 'с вашей подписью',
    empty: 'Прилавки пусты', emptyHint: 'Пока нет выставленных инструментов', seller: 'Продавец', you: 'вы', buy: 'Купить', cancel: 'Снять',
    connect: 'Сначала подключите кошелёк', treasuryLoading: 'Читаем адрес казны из сети…', treasuryUnavailable: 'Адрес казны недоступен из сети; покупка заблокирована', preparingBuy: 'Готовим покупку…', bought: 'Инструмент куплен', preparingCancel: 'Снимаем с продажи…', cancelled: 'Лот снят', selectTool: 'Выберите инструмент', preparingList: 'Готовим листинг…', listed: 'Инструмент выставлен', actionFailed: 'Операция не выполнена', walletChanged: 'Кошелёк изменился. Повторите действие с новым кошельком.',
    listTitle: 'Выставить инструмент', fixedPrice: 'Цена в SOL фиксирована для этого лота', connectTools: 'Подключите кошелёк, чтобы увидеть свои инструменты', readingTools: 'Читаем инструменты из сети…', toolsUnavailable: 'Не удалось прочитать инструменты из сети — нельзя выбрать предмет', noTools: 'Свободных инструментов нет', price: 'Цена, SOL', invalidPrice: 'Укажите положительную цену в SOL, не более девяти знаков после точки', list: 'Выставить на продажу', toolUnavailable: 'Выбранный инструмент больше не доступен в инвентаре', categoryLabel: 'Категории инструментов', allTools: 'Все инструменты', categoryEmpty: 'В этой категории сейчас нет предложений.',
  },
  en: {
    title: 'Listings', refresh: 'Refresh', loading: 'Loading listings from the network…', intro: 'Tools are sold at a fixed price in SOL. Check the amount before confirming in your wallet.', listingsUnavailable: 'Listings could not be read from the network. An empty market and a failed read are not the same.',
    sticker: 'STALLS', sonarMeta: 'PRICE SONAR', sonarTitle: 'Market sweep', sonarSub: 'closer to the center means cheaper', count: 'Listings', cheapest: 'Lowest price', median: 'Middle price', highest: 'Highest price', yours: 'Yours', onMarket: 'on the market now', signedByYou: 'listed by you',
    empty: 'No listings yet', emptyHint: 'No tools have been listed for sale', seller: 'Seller', you: 'you', buy: 'Buy', cancel: 'Remove',
    connect: 'Connect your wallet first', treasuryLoading: 'Reading the treasury address from the network…', treasuryUnavailable: 'The treasury address is unavailable from the network; purchases are blocked', preparingBuy: 'Preparing purchase…', bought: 'Tool purchased', preparingCancel: 'Removing listing…', cancelled: 'Listing removed', selectTool: 'Select a tool', preparingList: 'Preparing listing…', listed: 'Tool listed', actionFailed: 'Operation failed', walletChanged: 'The wallet changed. Please try again with the new wallet.',
    listTitle: 'List a tool', fixedPrice: 'This listing has a fixed price in SOL', connectTools: 'Connect your wallet to view your tools', readingTools: 'Loading tools from the network…', toolsUnavailable: 'Tools could not be read from the network; selection is unavailable', noTools: 'No tools available to list', price: 'Price, SOL', invalidPrice: 'Enter a positive SOL price with at most nine decimal places', list: 'List for sale', toolUnavailable: 'The selected tool is no longer available in your inventory', categoryLabel: 'Tool categories', allTools: 'All tools', categoryEmpty: 'There are no offers in this category right now.',
  },
  pt: {
    title: 'Anúncios', refresh: 'Atualizar', loading: 'Carregando anúncios da rede…', intro: 'As ferramentas são vendidas por um preço fixo em SOL. Confira o valor antes de confirmar na carteira.', listingsUnavailable: 'Não foi possível ler os anúncios na rede. Um mercado vazio não é o mesmo que uma falha na consulta.',
    sticker: 'BANCAS', sonarMeta: 'RADAR DE PREÇOS', sonarTitle: 'Varredura das bancas', sonarSub: 'mais perto do centro significa mais barato', count: 'Anúncios', cheapest: 'Menor preço', median: 'Preço central', highest: 'Maior preço', yours: 'Seus', onMarket: 'no mercado agora', signedByYou: 'anunciados por você',
    empty: 'Nenhum anúncio', emptyHint: 'Nenhuma ferramenta foi posta à venda', seller: 'Vendedor', you: 'você', buy: 'Comprar', cancel: 'Retirar',
    connect: 'Conecte a carteira primeiro', treasuryLoading: 'Consultando o endereço do tesouro na rede…', treasuryUnavailable: 'O endereço do tesouro está indisponível na rede; compras bloqueadas', preparingBuy: 'Preparando compra…', bought: 'Ferramenta comprada', preparingCancel: 'Retirando anúncio…', cancelled: 'Anúncio retirado', selectTool: 'Selecione uma ferramenta', preparingList: 'Preparando anúncio…', listed: 'Ferramenta anunciada', actionFailed: 'A operação falhou', walletChanged: 'A carteira mudou. Tente novamente com a nova carteira.',
    listTitle: 'Anunciar ferramenta', fixedPrice: 'Este anúncio tem preço fixo em SOL', connectTools: 'Conecte a carteira para ver suas ferramentas', readingTools: 'Carregando ferramentas da rede…', toolsUnavailable: 'Não foi possível ler as ferramentas na rede; seleção indisponível', noTools: 'Nenhuma ferramenta disponível para anunciar', price: 'Preço, SOL', invalidPrice: 'Informe um preço positivo em SOL com até nove casas decimais', list: 'Anunciar para venda', toolUnavailable: 'A ferramenta selecionada já não está disponível no inventário', categoryLabel: 'Categorias de ferramentas', allTools: 'Todas as ferramentas', categoryEmpty: 'Não há ofertas nesta categoria agora.',
  },
  es: {
    title: 'Anuncios', refresh: 'Actualizar', loading: 'Cargando anuncios de la red…', intro: 'Las herramientas se venden a un precio fijo en SOL. Comprueba el importe antes de confirmarlo en tu cartera.', listingsUnavailable: 'No se pudieron leer los anuncios de la red. Un mercado vacío no equivale a un error de lectura.',
    sticker: 'PUESTOS', sonarMeta: 'RADAR DE PRECIOS', sonarTitle: 'Barrido del mercado', sonarSub: 'más cerca del centro significa más barato', count: 'Anuncios', cheapest: 'Precio más bajo', median: 'Precio central', highest: 'Precio más alto', yours: 'Tuyos', onMarket: 'en el mercado ahora', signedByYou: 'anunciados por ti',
    empty: 'Todavía no hay anuncios', emptyHint: 'No se ha puesto ninguna herramienta a la venta', seller: 'Vendedor', you: 'tú', buy: 'Comprar', cancel: 'Retirar',
    connect: 'Conecta tu cartera primero', treasuryLoading: 'Consultando la dirección de la tesorería en la red…', treasuryUnavailable: 'La dirección de la tesorería no está disponible en la red; las compras están bloqueadas', preparingBuy: 'Preparando compra…', bought: 'Herramienta comprada', preparingCancel: 'Retirando anuncio…', cancelled: 'Anuncio retirado', selectTool: 'Elige una herramienta', preparingList: 'Preparando anuncio…', listed: 'Herramienta anunciada', actionFailed: 'No se pudo completar la operación', walletChanged: 'La cartera cambió. Inténtalo de nuevo con la nueva cartera.',
    listTitle: 'Anunciar herramienta', fixedPrice: 'Este anuncio tiene un precio fijo en SOL', connectTools: 'Conecta tu cartera para ver tus herramientas', readingTools: 'Cargando herramientas de la red…', toolsUnavailable: 'No se pudieron leer las herramientas de la red; no puedes elegir una', noTools: 'No hay herramientas disponibles para anunciar', price: 'Precio, SOL', invalidPrice: 'Introduce un precio positivo en SOL con un máximo de nueve decimales', list: 'Poner a la venta', toolUnavailable: 'La herramienta elegida ya no está disponible en tu inventario', categoryLabel: 'Categorías de herramientas', allTools: 'Todas las herramientas', categoryEmpty: 'Ahora no hay ofertas en esta categoría.',
  },
  vi: {
    title: 'Tin rao bán', refresh: 'Làm mới', loading: 'Đang tải tin rao bán từ mạng…', intro: 'Công cụ được bán theo giá cố định bằng SOL. Hãy kiểm tra số tiền trước khi xác nhận trong ví.', listingsUnavailable: 'Không thể đọc tin rao bán từ mạng. Chợ vắng hàng không đồng nghĩa với lỗi tải dữ liệu.',
    sticker: 'GIAN HÀNG', sonarMeta: 'RA-ĐA GIÁ', sonarTitle: 'Quét gian hàng', sonarSub: 'càng gần tâm, giá càng rẻ', count: 'Tin rao bán', cheapest: 'Giá thấp nhất', median: 'Giá ở giữa', highest: 'Giá cao nhất', yours: 'Của bạn', onMarket: 'đang được rao bán', signedByYou: 'do bạn đăng',
    empty: 'Chưa có tin rao bán', emptyHint: 'Chưa có công cụ nào được đăng bán', seller: 'Người bán', you: 'bạn', buy: 'Mua', cancel: 'Gỡ tin',
    connect: 'Hãy kết nối ví trước', treasuryLoading: 'Đang đọc địa chỉ kho quỹ từ mạng…', treasuryUnavailable: 'Không thể đọc địa chỉ kho quỹ từ mạng; không thể mua', preparingBuy: 'Đang chuẩn bị mua…', bought: 'Đã mua công cụ', preparingCancel: 'Đang gỡ tin…', cancelled: 'Đã gỡ tin', selectTool: 'Chọn công cụ', preparingList: 'Đang chuẩn bị tin rao…', listed: 'Đã đăng bán công cụ', actionFailed: 'Thao tác thất bại', walletChanged: 'Ví đã thay đổi. Hãy thử lại với ví mới.',
    listTitle: 'Đăng bán công cụ', fixedPrice: 'Tin rao này có giá cố định bằng SOL', connectTools: 'Kết nối ví để xem công cụ của bạn', readingTools: 'Đang tải công cụ từ mạng…', toolsUnavailable: 'Không thể đọc công cụ từ mạng; chưa thể chọn công cụ', noTools: 'Không có công cụ nào có thể đăng bán', price: 'Giá, SOL', invalidPrice: 'Nhập giá SOL dương, tối đa chín chữ số thập phân', list: 'Đăng bán', toolUnavailable: 'Công cụ đã chọn không còn trong kho của bạn', categoryLabel: 'Nhóm công cụ', allTools: 'Mọi công cụ', categoryEmpty: 'Hiện không có tin rao trong nhóm này.',
  },
  id: {
    title: 'Lapak', refresh: 'Muat ulang', loading: 'Memuat lapak dari jaringan…', intro: 'Peralatan dijual dengan harga tetap dalam SOL. Periksa jumlahnya sebelum mengonfirmasi di dompet.', listingsUnavailable: 'Lapak tidak dapat dibaca dari jaringan. Pasar kosong dan kegagalan membaca adalah dua hal berbeda.',
    sticker: 'LAPAK', sonarMeta: 'RADAR HARGA', sonarTitle: 'Pindai lapak', sonarSub: 'makin dekat ke pusat, makin murah', count: 'Lapak', cheapest: 'Harga terendah', median: 'Harga tengah', highest: 'Harga tertinggi', yours: 'Milikmu', onMarket: 'sedang dijual', signedByYou: 'dipasang olehmu',
    empty: 'Belum ada lapak', emptyHint: 'Belum ada peralatan yang dijual', seller: 'Penjual', you: 'kamu', buy: 'Beli', cancel: 'Hapus',
    connect: 'Hubungkan dompet terlebih dahulu', treasuryLoading: 'Membaca alamat kas dari jaringan…', treasuryUnavailable: 'Alamat kas tidak tersedia dari jaringan; pembelian diblokir', preparingBuy: 'Menyiapkan pembelian…', bought: 'Peralatan dibeli', preparingCancel: 'Menghapus lapak…', cancelled: 'Lapak dihapus', selectTool: 'Pilih peralatan', preparingList: 'Menyiapkan lapak…', listed: 'Peralatan dipasang', actionFailed: 'Operasi gagal', walletChanged: 'Dompet berubah. Coba lagi dengan dompet yang baru.',
    listTitle: 'Jual peralatan', fixedPrice: 'Lapak ini berharga tetap dalam SOL', connectTools: 'Hubungkan dompet untuk melihat peralatanmu', readingTools: 'Memuat peralatan dari jaringan…', toolsUnavailable: 'Peralatan tidak dapat dibaca dari jaringan; tidak dapat memilih', noTools: 'Tidak ada peralatan yang dapat dijual', price: 'Harga, SOL', invalidPrice: 'Masukkan harga SOL positif dengan maksimal sembilan angka desimal', list: 'Pasang untuk dijual', toolUnavailable: 'Peralatan yang dipilih tidak lagi ada di inventarismu', categoryLabel: 'Kategori peralatan', allTools: 'Semua peralatan', categoryEmpty: 'Belum ada penawaran di kategori ini.',
  },
  fil: {
    title: 'Mga listahan', refresh: 'I-refresh', loading: 'Kinukuha ang mga listahan sa network…', intro: 'Ibinebenta ang kagamitan sa nakatakdang presyo sa SOL. Suriin ang halaga bago magkumpirma sa wallet.', listingsUnavailable: 'Hindi mabasa ang mga listahan sa network. Magkaiba ang walang paninda at ang nabigong pagbasa.',
    sticker: 'MGA PUWESTO', sonarMeta: 'RADAR NG PRESYO', sonarTitle: 'Pag-scan sa mga puwesto', sonarSub: 'mas malapit sa gitna, mas mura', count: 'Mga listahan', cheapest: 'Pinakamababang presyo', median: 'Gitnang presyo', highest: 'Pinakamataas na presyo', yours: 'Iyo', onMarket: 'nasa pamilihan ngayon', signedByYou: 'inilista mo',
    empty: 'Wala pang listahan', emptyHint: 'Wala pang kagamitang inilagay sa bentahan', seller: 'Nagbebenta', you: 'ikaw', buy: 'Bilhin', cancel: 'Alisin',
    connect: 'Ikonekta muna ang wallet', treasuryLoading: 'Kinukuha ang address ng kabang-yaman sa network…', treasuryUnavailable: 'Hindi makuha sa network ang address ng kabang-yaman; hindi maaaring bumili', preparingBuy: 'Inihahanda ang pagbili…', bought: 'Nabili ang kagamitan', preparingCancel: 'Inaalis ang listahan…', cancelled: 'Inalis ang listahan', selectTool: 'Pumili ng kagamitan', preparingList: 'Inihahanda ang listahan…', listed: 'Nailista ang kagamitan', actionFailed: 'Hindi nagawa ang operasyon', walletChanged: 'Nagbago ang wallet. Subukan muli gamit ang bagong wallet.',
    listTitle: 'Ilista ang kagamitan', fixedPrice: 'Nakatakda ang presyo ng listahang ito sa SOL', connectTools: 'Ikonekta ang wallet para makita ang kagamitan mo', readingTools: 'Kinukuha ang kagamitan sa network…', toolsUnavailable: 'Hindi mabasa sa network ang kagamitan; hindi pa makakapili', noTools: 'Walang kagamitang maaaring ilista', price: 'Presyo, SOL', invalidPrice: 'Maglagay ng positibong presyo sa SOL na may hanggang siyam na decimal', list: 'Ilagay sa bentahan', toolUnavailable: 'Wala na sa iyong imbentaryo ang napiling kagamitan', categoryLabel: 'Mga kategorya ng kagamitan', allTools: 'Lahat ng kagamitan', categoryEmpty: 'Walang alok sa kategoryang ito ngayon.',
  },
};
