import type { Language } from './translations';

type Copy = {
  title: string; intro: string; paused: string; unitWarning: string; select: string; selected: string;
  registryUnavailable: string; loading: string; unavailable: string; refresh: string; empty: string;
  bestBid: string; bestAsk: string; depth: string; orders: string; noAsks: string; noBids: string;
  asks: string; bids: string; spread: string; priceUnit: string; amountUnit: string;
  you: string; cancel: string; exhausted: string; exhaustedInfo: string; noWallet: string;
  cancelling: string; cancelled: string; uncertain: string; retry: string;
};
/** Trades stay paused until atomic price semantics and wallet-bound quote checks are implemented. Existing maker orders can still be cancelled. */
export const orderbookCopy: Record<Language, Copy> = {
  ru: {
    title: 'Книга заявок', intro: 'Заявки на ресурсы, прочитанные из сети. Исполнение заявки не гарантировано.',
    paused: 'Новые заявки и сведение приостановлены: контракт умножает цену на количество в атомарных единицах, а прежняя форма показывала цену за целый ресурс. До исправления нельзя безопасно подтвердить расход.',
    unitWarning: 'Показанная цена — SOL за один целый ресурс (10⁹ атомарных единиц), а не за одну атомарную единицу. Это пересчёт записи контракта, не рыночная оценка.',
    select: 'Ресурс', selected: 'Выбран', registryUnavailable: 'Не удалось проверить реестр ресурсов в сети. Заявки недоступны.', loading: 'Загружаем заявки…', unavailable: 'Не удалось проверить заявки в сети. Пустой стакан не подтверждён.', refresh: 'Обновить', empty: 'Подтверждено: активных заявок нет.',
    bestBid: 'Лучшая покупка', bestAsk: 'Лучшая продажа', depth: 'Глубина заявок', orders: 'Активные заявки', noAsks: 'Нет предложений о продаже', noBids: 'Нет предложений о покупке', asks: 'Продажа', bids: 'Покупка', spread: 'спред', priceUnit: 'SOL / ресурс', amountUnit: 'рес.', you: 'вы', cancel: 'Отменить', exhausted: 'Заявки без остатка', exhaustedInfo: 'Закройте свою исполненную заявку, чтобы вернуть остаток залога и аренду аккаунта.', noWallet: 'Подключите кошелёк для отмены собственных заявок.', cancelling: 'Отменяем заявку…', cancelled: 'Отмена подтверждена. Обновляем книгу заявок.', uncertain: 'Отмену нельзя подтвердить. Проверьте историю кошелька и обновите книгу перед повторной попыткой.', retry: 'Отмена не отправлена; проверьте кошелёк и попробуйте позже.',
  },
  en: {
    title: 'Order book', intro: 'On-chain resource orders. An order is not guaranteed to fill.',
    paused: 'New orders and matching are paused: the contract multiplies price by the atomic token quantity, but the old form quoted a whole resource. Spending cannot be confirmed safely until this is fixed.',
    unitWarning: 'Displayed prices are SOL per full resource (10⁹ atomic units), not per atomic unit. This is a conversion of the contract record, not a market valuation.',
    select: 'Resource', selected: 'Selected', registryUnavailable: 'Could not verify the resource registry on-chain. Orders are unavailable.', loading: 'Loading orders…', unavailable: 'Could not verify orders on-chain. An empty book has not been confirmed.', refresh: 'Refresh', empty: 'Confirmed: no active orders.',
    bestBid: 'Best bid', bestAsk: 'Best ask', depth: 'Order depth', orders: 'Active orders', noAsks: 'No sell orders', noBids: 'No buy orders', asks: 'Sell', bids: 'Buy', spread: 'spread', priceUnit: 'SOL / resource', amountUnit: 'units', you: 'you', cancel: 'Cancel', exhausted: 'Exhausted orders', exhaustedInfo: 'Close your filled order to reclaim the remaining escrow and account rent.', noWallet: 'Connect your wallet to cancel your own orders.', cancelling: 'Cancelling order…', cancelled: 'Cancellation confirmed. Refreshing the book.', uncertain: 'Could not confirm cancellation. Check your wallet history and refresh the book before trying again.', retry: 'Cancellation was not submitted. Check your wallet and try later.',
  },
  pt: {
    title: 'Livro de ofertas', intro: 'Ordens de recursos registradas na rede. Não há garantia de execução.',
    paused: 'Novas ordens e cruzamentos estão suspensos: o contrato multiplica o preço pela quantidade atômica, mas o formulário antigo mostrava o preço por recurso inteiro. Não é seguro confirmar gastos até corrigirmos isso.',
    unitWarning: 'Os preços são em SOL por recurso inteiro (10⁹ unidades atômicas), não por unidade atômica. É uma conversão do registro do contrato, não uma avaliação de mercado.',
    select: 'Recurso', selected: 'Selecionado', registryUnavailable: 'Não foi possível verificar o registro de recursos na rede. Ordens indisponíveis.', loading: 'Carregando ordens…', unavailable: 'Não foi possível verificar as ordens na rede. O livro vazio não foi confirmado.', refresh: 'Atualizar', empty: 'Confirmado: não há ordens ativas.',
    bestBid: 'Melhor compra', bestAsk: 'Melhor venda', depth: 'Profundidade das ordens', orders: 'Ordens ativas', noAsks: 'Sem ordens de venda', noBids: 'Sem ordens de compra', asks: 'Venda', bids: 'Compra', spread: 'diferença', priceUnit: 'SOL / recurso', amountUnit: 'unid.', you: 'você', cancel: 'Cancelar', exhausted: 'Ordens esgotadas', exhaustedInfo: 'Feche sua ordem executada para recuperar o saldo do depósito e o aluguel da conta.', noWallet: 'Conecte a carteira para cancelar suas ordens.', cancelling: 'Cancelando ordem…', cancelled: 'Cancelamento confirmado. Atualizando o livro.', uncertain: 'Não foi possível confirmar o cancelamento. Confira o histórico da carteira e atualize o livro antes de tentar novamente.', retry: 'Cancelamento não enviado. Verifique a carteira e tente mais tarde.',
  },
  es: {
    title: 'Libro de órdenes', intro: 'Órdenes de recursos leídas de la cadena. No se garantiza su ejecución.',
    paused: 'Se han pausado las órdenes nuevas y el cruce: el contrato multiplica el precio por la cantidad atómica, pero el formulario anterior mostraba el precio por recurso entero. No se puede confirmar el gasto con seguridad hasta corregirlo.',
    unitWarning: 'Los precios mostrados son SOL por recurso entero (10⁹ unidades atómicas), no por unidad atómica. Es una conversión del registro del contrato, no una valoración de mercado.',
    select: 'Recurso', selected: 'Elegido', registryUnavailable: 'No se pudo verificar el registro de recursos en la cadena. Órdenes no disponibles.', loading: 'Cargando órdenes…', unavailable: 'No se pudieron verificar las órdenes en la cadena. No se ha confirmado un libro vacío.', refresh: 'Actualizar', empty: 'Confirmado: no hay órdenes activas.',
    bestBid: 'Mejor compra', bestAsk: 'Mejor venta', depth: 'Profundidad de órdenes', orders: 'Órdenes activas', noAsks: 'Sin órdenes de venta', noBids: 'Sin órdenes de compra', asks: 'Venta', bids: 'Compra', spread: 'diferencia', priceUnit: 'SOL / recurso', amountUnit: 'unid.', you: 'tú', cancel: 'Cancelar', exhausted: 'Órdenes agotadas', exhaustedInfo: 'Cierra tu orden ejecutada para recuperar el depósito restante y el alquiler de la cuenta.', noWallet: 'Conecta tu cartera para cancelar tus órdenes.', cancelling: 'Cancelando orden…', cancelled: 'Cancelación confirmada. Actualizando el libro.', uncertain: 'No se pudo confirmar la cancelación. Revisa el historial de tu cartera y actualiza el libro antes de reintentarlo.', retry: 'No se envió la cancelación. Revisa tu cartera e inténtalo más tarde.',
  },
  vi: {
    title: 'Sổ lệnh', intro: 'Lệnh tài nguyên được đọc từ chuỗi. Không đảm bảo lệnh sẽ khớp.',
    paused: 'Tạm dừng tạo lệnh và khớp lệnh: hợp đồng nhân giá với số đơn vị nguyên tử, trong khi biểu mẫu cũ báo giá cho cả một tài nguyên. Chưa thể xác nhận chi phí an toàn trước khi khắc phục.',
    unitWarning: 'Giá hiển thị là SOL cho một tài nguyên hoàn chỉnh (10⁹ đơn vị nguyên tử), không phải một đơn vị nguyên tử. Đây là phép quy đổi bản ghi hợp đồng, không phải định giá thị trường.',
    select: 'Tài nguyên', selected: 'Đã chọn', registryUnavailable: 'Không thể xác minh danh mục tài nguyên trên chuỗi. Không có lệnh để xem.', loading: 'Đang tải lệnh…', unavailable: 'Không thể xác minh lệnh trên chuỗi. Chưa thể kết luận sổ lệnh trống.', refresh: 'Tải lại', empty: 'Đã xác nhận: không có lệnh đang hoạt động.',
    bestBid: 'Giá mua cao nhất', bestAsk: 'Giá bán thấp nhất', depth: 'Độ sâu lệnh', orders: 'Lệnh đang hoạt động', noAsks: 'Không có lệnh bán', noBids: 'Không có lệnh mua', asks: 'Bán', bids: 'Mua', spread: 'chênh lệch', priceUnit: 'SOL / tài nguyên', amountUnit: 'đơn vị', you: 'bạn', cancel: 'Hủy', exhausted: 'Lệnh đã hết', exhaustedInfo: 'Đóng lệnh đã khớp để nhận lại tiền ký quỹ còn dư và phí thuê tài khoản.', noWallet: 'Kết nối ví để hủy lệnh của bạn.', cancelling: 'Đang hủy lệnh…', cancelled: 'Đã xác nhận hủy. Đang tải lại sổ lệnh.', uncertain: 'Không thể xác nhận việc hủy. Kiểm tra lịch sử ví và tải lại sổ lệnh trước khi thử tiếp.', retry: 'Chưa gửi yêu cầu hủy. Kiểm tra ví rồi thử lại sau.',
  },
  id: {
    title: 'Buku pesanan', intro: 'Pesanan sumber daya yang dibaca dari blockchain. Eksekusi tidak dijamin.',
    paused: 'Pesanan baru dan pencocokan ditunda: kontrak mengalikan harga dengan jumlah unit atom, sementara formulir lama menampilkan harga per sumber daya utuh. Pengeluaran belum dapat dikonfirmasi dengan aman sebelum diperbaiki.',
    unitWarning: 'Harga ditampilkan dalam SOL per sumber daya utuh (10⁹ unit atom), bukan per unit atom. Ini konversi catatan kontrak, bukan penilaian pasar.',
    select: 'Sumber daya', selected: 'Dipilih', registryUnavailable: 'Daftar sumber daya tidak dapat diverifikasi di blockchain. Pesanan tidak tersedia.', loading: 'Memuat pesanan…', unavailable: 'Pesanan tidak dapat diverifikasi di blockchain. Buku kosong belum terkonfirmasi.', refresh: 'Muat ulang', empty: 'Terkonfirmasi: tidak ada pesanan aktif.',
    bestBid: 'Harga beli tertinggi', bestAsk: 'Harga jual terendah', depth: 'Kedalaman pesanan', orders: 'Pesanan aktif', noAsks: 'Tidak ada pesanan jual', noBids: 'Tidak ada pesanan beli', asks: 'Jual', bids: 'Beli', spread: 'selisih', priceUnit: 'SOL / sumber daya', amountUnit: 'unit', you: 'kamu', cancel: 'Batalkan', exhausted: 'Pesanan habis', exhaustedInfo: 'Tutup pesanan yang sudah cocok untuk menarik sisa dana titipan dan sewa akun.', noWallet: 'Hubungkan dompet untuk membatalkan pesanan sendiri.', cancelling: 'Membatalkan pesanan…', cancelled: 'Pembatalan dikonfirmasi. Memperbarui buku.', uncertain: 'Tidak dapat mengonfirmasi pembatalan. Periksa riwayat dompet dan muat ulang buku sebelum mencoba lagi.', retry: 'Pembatalan belum dikirim. Periksa dompet dan coba lagi nanti.',
  },
  fil: {
    title: 'Talaan ng order', intro: 'Mga order sa yaman na nabasa sa blockchain. Hindi tiyak na matutupad ang order.',
    paused: 'Pansamantalang hindi maaaring gumawa o magtugma ng order: minumultiply ng kontrata ang presyo sa bilang ng maliliit na yunit, ngunit ipinapakita ng lumang form ang presyo para sa isang buong yaman. Hindi pa ligtas na kumpirmahin ang gastos hangga’t hindi ito naaayos.',
    unitWarning: 'SOL kada buong yaman (10⁹ maliliit na yunit) ang ipinapakitang presyo, hindi kada maliit na yunit. Pagkuwenta lamang ito mula sa tala ng kontrata, hindi pagtataya ng presyo sa merkado.',
    select: 'Yaman', selected: 'Napili', registryUnavailable: 'Hindi ma-verify sa blockchain ang talaan ng yaman. Hindi makuha ang mga order.', loading: 'Kinukuha ang mga order…', unavailable: 'Hindi ma-verify sa blockchain ang mga order. Hindi kumpirmadong walang laman ang talaan.', refresh: 'I-refresh', empty: 'Kumpirmado: walang aktibong order.',
    bestBid: 'Pinakamataas na bili', bestAsk: 'Pinakamababang benta', depth: 'Lalim ng mga order', orders: 'Aktibong mga order', noAsks: 'Walang nagbebenta', noBids: 'Walang bumibili', asks: 'Benta', bids: 'Bili', spread: 'agwat', priceUnit: 'SOL / yaman', amountUnit: 'yunit', you: 'ikaw', cancel: 'Kanselahin', exhausted: 'Naubos na mga order', exhaustedInfo: 'Isara ang natupad mong order upang mabawi ang natirang nakalagak na halaga at upa sa account.', noWallet: 'Ikonekta ang wallet para makansela ang sarili mong order.', cancelling: 'Kinakansela ang order…', cancelled: 'Kumpirmado ang pagkansela. Ina-update ang talaan.', uncertain: 'Hindi makumpirma ang pagkansela. Suriin ang kasaysayan ng wallet at i-refresh ang talaan bago subukan muli.', retry: 'Hindi naipadala ang pagkansela. Suriin ang wallet at subukan muli mamaya.',
  },
};
