import type { Language } from './translations';
import type { ResourceCategory } from '../site/content/schema';

type Copy = { resources: string; categories: string; search: string; category: string; all: string; found: string; live: string; soon: string; labels: Record<ResourceCategory, string> };
export const resourceCatalogCopy: Record<Language, Copy> = {
  ru: { resources: 'ресурсов', categories: 'категорий: от базовых материалов до гостевых токенов.', search: 'Поиск', category: 'Категория', all: 'Все', found: 'Найдено', live: 'Описано в спецификации', soon: 'Запланировано', labels: { base: 'Базовые', chain: 'Модельная цепочка', material: 'Материалы', rare: 'Ядра и чипы', consumable: 'Флюиды', token: 'Токены', collab: 'Коллаборации', social: 'Особые' } },
  en: { resources: 'resources', categories: 'categories: from base materials to event tokens.', search: 'Search', category: 'Category', all: 'All', found: 'Found', live: 'Documented in the specification', soon: 'Planned', labels: { base: 'Base', chain: 'Model chain', material: 'Materials', rare: 'Cores & chips', consumable: 'Fluids', token: 'Tokens', collab: 'Collaborations', social: 'Special' } },
  pt: { resources: 'recursos', categories: 'categorias: de materiais básicos a tokens de eventos.', search: 'Buscar', category: 'Categoria', all: 'Todas', found: 'Encontrados', live: 'Descrito na especificação', soon: 'Planejado', labels: { base: 'Básicos', chain: 'Cadeia de produção', material: 'Materiais', rare: 'Raros', consumable: 'Consumíveis', token: 'Tokens', collab: 'Colaborativos', social: 'Sociais' } },
  es: { resources: 'recursos', categories: 'categorías: desde materiales básicos hasta tokens de eventos.', search: 'Buscar', category: 'Categoría', all: 'Todas', found: 'Encontrados', live: 'Descrito en la especificación', soon: 'Previsto', labels: { base: 'Básicos', chain: 'Cadena de producción', material: 'Materiales', rare: 'Raros', consumable: 'Consumibles', token: 'Tokens', collab: 'Colaborativos', social: 'Sociales' } },
  vi: { resources: 'tài nguyên', categories: 'nhóm: từ vật liệu cơ bản đến token sự kiện.', search: 'Tìm kiếm', category: 'Nhóm', all: 'Tất cả', found: 'Tìm thấy', live: 'Có trong đặc tả', soon: 'Dự kiến', labels: { base: 'Cơ bản', chain: 'Chuỗi sản xuất', material: 'Vật liệu', rare: 'Hiếm', consumable: 'Vật phẩm tiêu hao', token: 'Token', collab: 'Hợp tác', social: 'Cộng đồng' } },
  id: { resources: 'sumber daya', categories: 'kategori: dari bahan dasar hingga token acara.', search: 'Cari', category: 'Kategori', all: 'Semua', found: 'Ditemukan', live: 'Tercantum dalam spesifikasi', soon: 'Direncanakan', labels: { base: 'Dasar', chain: 'Rangkaian produksi', material: 'Bahan', rare: 'Langka', consumable: 'Sekali pakai', token: 'Token', collab: 'Kolaborasi', social: 'Sosial' } },
  fil: { resources: 'yaman', categories: 'kategorya: mula pangunahing materyales hanggang token ng event.', search: 'Maghanap', category: 'Kategorya', all: 'Lahat', found: 'Natagpuan', live: 'Nasa espesipikasyon', soon: 'Nakaplano', labels: { base: 'Pangunahin', chain: 'Daloy ng paggawa', material: 'Materyales', rare: 'Bihira', consumable: 'Nagagamit', token: 'Token', collab: 'Sama-sama', social: 'Panlipunan' } },
};
