import type { Language } from './translations';

type LoreChapter = { id: 'founding' | 'guilds' | 'market' | 'drum' | 'rebirth' | 'today'; era: string; title: string; paragraphs: readonly [string, string] };
type LoreCopy = { lead: string; paragraphs: readonly [string, string]; heading: string; chapters: readonly LoreChapter[] };

/** Fictional setting, not proof that the named game features are live. Keep
 * the chapter ids stable across languages so navigation never mixes texts. */
export const siteLore: Record<Language, LoreCopy> = {
  ru: {
    lead: 'Четыре эры: от грифельной доски до открытых ставен.',
    paragraphs: ['Это художественная история мастерской, а не перечень работающих механик. Она рассказывает, как возникли образы доверия, печати и нового цикла.', 'Читай по эрам — или начни с той главы, что ближе к сегодняшнему дню.'],
    heading: 'Эры мастерской', chapters: [
      { id: 'founding', era: 'Эра I · Основание', title: 'Пепел и образец', paragraphs: ['Когда старые дороги опустели, мастера собрались у энергопотока. Их первой общей постройкой стал модуль сепарации. Барабаны крутили по очереди, и очередь сделалась первым законом.', 'Они считали мешки данных, рабочие часы и долги товарищам. Из честной записи выросла мастерская: то, что однажды окажется в цепи, начиналось с грифельной доски у двери.'] },
      { id: 'guilds', era: 'Эра I · Круги', title: 'Круг мастеров', paragraphs: ['Одной пары рук не хватало на участок, вычислительный цикл и кузницу. Мастера разделили работу — и поняли, что каждому вкладу нужна память.', 'Доверием стала память об исполненном обещании, а не украшение на двери. Пять ступеней этой памяти вели от чужака к старейшине.'] },
      { id: 'market', era: 'Эра II · Площадь', title: 'Доска предложений', paragraphs: ['На площади вывесили доску: один искал сигнал, другой предлагал инструмент. Даже справедливая цена нуждалась в честной мере — так площадь научилась различать обещание и совершённую сделку.', 'Позже рядом с доской появились очередь ярмарки и аукционный молоток. Но правило осталось прежним: проигравшему возвращается ставка, а данное слово остаётся с тобой.'] },
      { id: 'drum', era: 'Эра II · Ритуал', title: 'Барабан и печать', paragraphs: ['У барабана не просили верить на слово: здесь договаривались о порядке случая. Сначала запись запечатывали, затем раскрывали при свидетелях.', 'Из этого порядка выросли обязательство и раскрытие: сургуч сменился хешем, свидетели — сетью. Случай перестал быть милостью одного человека.'] },
      { id: 'rebirth', era: 'Эра III · Новый цикл', title: 'Образец в пепле', paragraphs: ['В третью фазу мастера отдавали часть собранного земле. Старое становилось пищей новому; из этого жеста вырос рассказ о перерождении — оставить накопленное ради следующего цикла.', 'Не всё переживает огонь. В сказании остаются инструменты и память, а излишки сгорают. Искусство мастера — решить, что сохранить.'] },
      { id: 'today', era: 'Эра IV · Сегодня', title: 'Открытые ставни', paragraphs: ['Сегодня мастерская снова открывает ставни. На столе — инструменты, записи и незаконченная работа; из другой вселенной сюда пришёл MIND и занял место у учебного стенда.', 'Место живёт, пока ты понимаешь его правила и можешь оставить после себя полезную вещь. Остальное — шум площади.'] },
    ],
  },
  en: {
    lead: 'Four eras, from a slate by the door to shutters thrown wide.',
    paragraphs: ['This is a story about the workshop, not a list of live game features. It traces the ideas behind trust, sealed promises and a new cycle.', 'Read it era by era, or begin with the chapter closest to today.'],
    heading: 'The workshop through the ages', chapters: [
      { id: 'founding', era: 'Era I · The founding', title: 'Ash and the first sample', paragraphs: ['When the old roads fell quiet, the makers gathered beside the power stream. Their first shared building was a separator. They took turns at its drums, and the queue became their first law.', 'They counted sacks of data, hours worked and debts to friends. Honest records gave the workshop its roots: what would one day reach the chain began on a slate beside the door.'] },
      { id: 'guilds', era: 'Era I · The circles', title: 'The makers’ circle', paragraphs: ['One pair of hands could not tend the plots, run compute cycles and work the forge. The makers divided the labor—and learned that every contribution needs a memory.', 'Trust became the memory of a promise kept, not a badge on the door. Five steps of that memory led from stranger to elder.'] },
      { id: 'market', era: 'Era II · The square', title: 'The offer board', paragraphs: ['A board went up in the square: one maker needed a signal, another offered a tool. Even a fair price needed an honest measure. The square learned to tell an offer from a completed trade.', 'Later came the fair’s queue and the auctioneer’s hammer. Yet the rule held: return the losing bid, and stand by your word.'] },
      { id: 'drum', era: 'Era II · The rite', title: 'The drum and the seal', paragraphs: ['No one at the drum asked for blind faith. They agreed on the order of chance: first seal the record, then open it before witnesses.', 'The custom became commitment and reveal. Wax gave way to a hash; witnesses became a network. Chance no longer rested on one person’s favor.'] },
      { id: 'rebirth', era: 'Era III · A new cycle', title: 'A sample in the ashes', paragraphs: ['In the third phase, the makers returned part of their harvest to the earth. The old fed the new. From that gesture came a tale of rebirth: leave what you have gathered for the next cycle.', 'Not everything survives the fire. In the tale, tools and memory remain while the surplus burns. A maker’s craft lies in choosing what to keep.'] },
      { id: 'today', era: 'Era IV · Today', title: 'The shutters open', paragraphs: ['Today the workshop throws open its shutters again. Tools, records and unfinished work lie on the table. MIND has arrived from another universe and found a place by the training bench.', 'The place lives as long as you can understand its rules and leave something useful behind. The rest is noise from the square.'] },
    ],
  },
  pt: {
    lead: 'Quatro épocas, de uma lousa à porta às janelas escancaradas.',
    paragraphs: ['Esta é uma história da oficina, não uma lista de mecânicas já disponíveis. Conta de onde vieram as ideias de confiança, promessa selada e novo ciclo.', 'Lê-a época a época, ou começa pelo capítulo mais próximo de hoje.'],
    heading: 'As épocas da oficina', chapters: [
      { id: 'founding', era: 'Época I · Fundação', title: 'Cinzas e a primeira amostra', paragraphs: ['Quando as velhas estradas ficaram desertas, os artesãos reuniram-se junto ao fluxo de energia. Construíram juntos um módulo de separação. Revezavam-se nos tambores, e a fila tornou-se a primeira lei.', 'Contavam sacos de dados, horas de trabalho e dívidas aos companheiros. A oficina nasceu desses registos honestos: o que um dia chegaria à rede começou numa lousa junto à porta.'] },
      { id: 'guilds', era: 'Época I · Círculos', title: 'O círculo dos artesãos', paragraphs: ['Duas mãos não bastavam para cuidar dos campos, dos ciclos de computação e da forja. Os artesãos dividiram o trabalho — e perceberam que cada contribuição precisava de memória.', 'A confiança tornou-se a lembrança de uma promessa cumprida, não um emblema na porta. Cinco degraus dessa memória levavam do desconhecido ao ancião.'] },
      { id: 'market', era: 'Época II · Praça', title: 'O quadro de ofertas', paragraphs: ['Na praça, alguém pendurou um quadro: um artesão procurava um sinal, outro oferecia uma ferramenta. Mesmo um preço justo exigia medida honesta. Assim aprenderam a distinguir promessa de negócio concluído.', 'Vieram depois a fila da feira e o martelo do leiloeiro. A regra manteve-se: devolver a proposta perdedora e honrar a palavra dada.'] },
      { id: 'drum', era: 'Época II · Ritual', title: 'O tambor e o selo', paragraphs: ['Junto ao tambor, ninguém pedia fé cega. Concordavam na ordem do acaso: primeiro selar o registo, depois abri-lo perante testemunhas.', 'O costume virou compromisso e revelação. A cera deu lugar ao hash; as testemunhas, à rede. O acaso deixou de depender da vontade de uma pessoa.'] },
      { id: 'rebirth', era: 'Época III · Novo ciclo', title: 'Uma amostra nas cinzas', paragraphs: ['Na terceira fase, os artesãos devolviam parte da colheita à terra. O velho alimentava o novo. Desse gesto nasceu a história do renascimento: deixar o acumulado para começar outro ciclo.', 'Nem tudo resiste ao fogo. No conto, ferramentas e memória ficam; os excessos ardem. A arte está em escolher o que guardar.'] },
      { id: 'today', era: 'Época IV · Hoje', title: 'As janelas abrem-se', paragraphs: ['Hoje a oficina abre novamente as janelas. Sobre a mesa há ferramentas, registos e trabalho por acabar. MIND chegou de outro universo e encontrou lugar junto à bancada de treino.', 'Este lugar vive enquanto conseguires compreender as suas regras e deixar algo útil. O resto é ruído da praça.'] },
    ],
  },
  es: {
    lead: 'Cuatro épocas, de una pizarra junto a la puerta a las ventanas abiertas.',
    paragraphs: ['Esta es la historia de un taller, no una lista de mecánicas activas. Cuenta de dónde nacieron las ideas de confianza, promesas selladas y nuevos ciclos.', 'Léela época por época o empieza por el capítulo más cercano a hoy.'],
    heading: 'Las épocas del taller', chapters: [
      { id: 'founding', era: 'Época I · Fundación', title: 'Ceniza y la primera muestra', paragraphs: ['Cuando los viejos caminos quedaron vacíos, los artesanos se reunieron junto al flujo de energía. Construyeron entre todos un módulo de separación. Se turnaban ante sus tambores, y la fila se convirtió en su primera ley.', 'Contaban sacos de datos, horas trabajadas y deudas con sus compañeros. De aquellos registros honestos nació el taller: lo que algún día llegaría a la cadena empezó en una pizarra junto a la puerta.'] },
      { id: 'guilds', era: 'Época I · Círculos', title: 'El círculo de artesanos', paragraphs: ['Un solo par de manos no bastaba para atender las parcelas, los ciclos de cómputo y la forja. Repartieron el trabajo y descubrieron que toda contribución necesita memoria.', 'La confianza pasó a ser el recuerdo de una promesa cumplida, no un adorno en la puerta. Cinco peldaños de esa memoria llevaban del desconocido al anciano.'] },
      { id: 'market', era: 'Época II · La plaza', title: 'El tablón de ofertas', paragraphs: ['Colgaron un tablón en la plaza: alguien buscaba una señal y otro ofrecía una herramienta. Hasta un precio justo exigía una medida honrada. La plaza aprendió a distinguir la oferta del trato cerrado.', 'Después llegaron la cola de la feria y el martillo del subastador. La regla permaneció: devolver la puja perdedora y cumplir la palabra dada.'] },
      { id: 'drum', era: 'Época II · El rito', title: 'El tambor y el sello', paragraphs: ['Junto al tambor nadie pedía fe ciega. Acordaban el orden del azar: primero sellar el registro, luego abrirlo ante testigos.', 'Así nació el compromiso y la revelación. La cera se volvió hash; los testigos, red. El azar dejó de depender del favor de una sola persona.'] },
      { id: 'rebirth', era: 'Época III · Un nuevo ciclo', title: 'Una muestra entre cenizas', paragraphs: ['En la tercera fase, los artesanos devolvían parte de la cosecha a la tierra. Lo viejo alimentaba lo nuevo. De ese gesto nació el cuento del renacimiento: dejar lo acumulado para empezar otro ciclo.', 'No todo sobrevive al fuego. En el relato quedan las herramientas y la memoria; arde lo que sobra. El oficio está en elegir qué conservar.'] },
      { id: 'today', era: 'Época IV · Hoy', title: 'Se abren las ventanas', paragraphs: ['Hoy el taller abre de nuevo sus ventanas. Sobre la mesa hay herramientas, registros y tareas pendientes. MIND ha llegado de otro universo y ocupa un lugar junto al banco de entrenamiento.', 'Este lugar vive mientras puedas entender sus reglas y dejar algo útil. El resto es ruido de la plaza.'] },
    ],
  },
  vi: {
    lead: 'Bốn thời kỳ: từ tấm bảng trước cửa đến những ô cửa rộng mở.',
    paragraphs: ['Đây là câu chuyện về xưởng, không phải danh sách tính năng đang hoạt động. Nó kể về nguồn gốc của niềm tin, lời hứa niêm phong và một chu kỳ mới.', 'Hãy đọc theo từng thời kỳ, hoặc bắt đầu từ chương gần với hôm nay nhất.'],
    heading: 'Những thời kỳ của xưởng', chapters: [
      { id: 'founding', era: 'Thời kỳ I · Khởi đầu', title: 'Tro tàn và mẫu thử đầu tiên', paragraphs: ['Khi những con đường cũ vắng bóng người, thợ thủ công tụ họp bên dòng năng lượng. Công trình chung đầu tiên là bộ phận tách mẫu. Họ thay phiên quay trống, rồi hàng đợi trở thành luật lệ đầu tiên.', 'Họ đếm những bao dữ liệu, giờ công và món nợ với đồng đội. Từ những ghi chép trung thực, xưởng ra đời: thứ một ngày kia sẽ lên chuỗi đã bắt đầu trên tấm bảng bên cửa.'] },
      { id: 'guilds', era: 'Thời kỳ I · Vòng tròn', title: 'Vòng tròn thợ thủ công', paragraphs: ['Một đôi tay không thể vừa chăm đất, vừa chạy chu kỳ tính toán, vừa đứng bên lò rèn. Họ chia nhau công việc — và nhận ra mỗi đóng góp đều cần được ghi nhớ.', 'Niềm tin trở thành ký ức về lời hứa đã giữ, chứ không phải huy hiệu treo cửa. Năm bậc ký ức dẫn từ người lạ đến bậc trưởng lão.'] },
      { id: 'market', era: 'Thời kỳ II · Quảng trường', title: 'Bảng rao đổi', paragraphs: ['Một tấm bảng xuất hiện ở quảng trường: người tìm tín hiệu, kẻ rao công cụ. Giá hợp lý vẫn cần thước đo ngay thẳng. Quảng trường học cách phân biệt lời rao với giao dịch đã hoàn tất.', 'Sau này có thêm hàng đợi phiên chợ và chiếc búa đấu giá. Nhưng luật cũ còn đó: trả lại giá thầu thua cuộc và giữ lời mình nói.'] },
      { id: 'drum', era: 'Thời kỳ II · Nghi lễ', title: 'Chiếc trống và con dấu', paragraphs: ['Bên chiếc trống, không ai đòi lòng tin mù quáng. Họ thống nhất thứ tự của may rủi: niêm phong bản ghi trước, rồi mở ra trước người chứng kiến.', 'Tập tục ấy thành cam kết và công bố. Sáp hóa thành mã băm; người chứng kiến hóa thành mạng lưới. May rủi không còn tùy thuộc ân huệ của một người.'] },
      { id: 'rebirth', era: 'Thời kỳ III · Chu kỳ mới', title: 'Mẫu thử trong tro tàn', paragraphs: ['Ở giai đoạn thứ ba, người thợ trả một phần thành quả về với đất. Cái cũ nuôi cái mới. Từ cử chỉ ấy nảy sinh câu chuyện tái sinh: buông điều tích góp để bước vào chu kỳ kế tiếp.', 'Không phải mọi thứ đều qua được lửa. Trong truyện, công cụ và ký ức còn lại, phần dư bị thiêu rụi. Tay nghề nằm ở việc chọn thứ cần giữ.'] },
      { id: 'today', era: 'Thời kỳ IV · Hôm nay', title: 'Cửa xưởng mở rộng', paragraphs: ['Hôm nay xưởng lại mở tung cửa. Trên bàn là công cụ, sổ sách và công việc dang dở; MIND từ một vũ trụ khác đã tìm được chỗ bên bàn huấn luyện.', 'Xưởng còn sống chừng nào bạn hiểu được quy tắc của nó và để lại điều gì hữu ích. Phần còn lại chỉ là tiếng ồn nơi quảng trường.'] },
    ],
  },
  id: {
    lead: 'Empat zaman, dari papan tulis di pintu hingga jendela yang terbuka lebar.',
    paragraphs: ['Ini kisah sebuah bengkel, bukan daftar fitur game yang sudah aktif. Kisah ini menelusuri asal kepercayaan, janji yang disegel, dan siklus baru.', 'Bacalah dari zaman ke zaman, atau mulai dari bab yang paling dekat dengan hari ini.'],
    heading: 'Zaman-zaman bengkel', chapters: [
      { id: 'founding', era: 'Zaman I · Pendirian', title: 'Abu dan sampel pertama', paragraphs: ['Saat jalan-jalan lama sepi, para perajin berkumpul di tepi aliran energi. Bangunan bersama pertama mereka adalah modul pemisah. Mereka bergiliran memutar drumnya, dan antrean menjadi hukum pertama.', 'Mereka menghitung karung data, jam kerja, dan utang kepada rekan. Dari catatan jujur itu lahir sebuah bengkel: apa yang kelak masuk blockchain bermula di papan tulis dekat pintu.'] },
      { id: 'guilds', era: 'Zaman I · Lingkaran', title: 'Lingkaran para perajin', paragraphs: ['Sepasang tangan tak cukup untuk mengurus lahan, siklus komputasi, dan bengkel tempa. Para perajin membagi tugas—lalu sadar setiap sumbangan perlu dikenang.', 'Kepercayaan menjadi ingatan akan janji yang ditepati, bukan hiasan di pintu. Lima anak tangga ingatan itu membawa orang asing menuju tetua.'] },
      { id: 'market', era: 'Zaman II · Alun-alun', title: 'Papan penawaran', paragraphs: ['Di alun-alun berdiri sebuah papan: ada yang mencari sinyal, ada yang menawarkan alat. Harga wajar pun butuh ukuran yang jujur. Mereka belajar membedakan tawaran dari transaksi yang selesai.', 'Lalu datanglah antrean pasar dan palu lelang. Namun aturannya tetap: kembalikan tawaran yang kalah dan pegang kata-katamu.'] },
      { id: 'drum', era: 'Zaman II · Upacara', title: 'Drum dan segel', paragraphs: ['Di dekat drum, tak ada yang meminta kepercayaan buta. Mereka sepakat soal urutan nasib: segel catatannya dahulu, kemudian buka di hadapan para saksi.', 'Kebiasaan itu menjadi komitmen dan pengungkapan. Lilin segel berganti hash; para saksi menjadi jaringan. Keberuntungan tak lagi bergantung pada kemurahan satu orang.'] },
      { id: 'rebirth', era: 'Zaman III · Siklus baru', title: 'Sampel di antara abu', paragraphs: ['Pada fase ketiga, para perajin mengembalikan sebagian panen ke tanah. Yang lama menghidupi yang baru. Dari tindakan itu lahir kisah kelahiran kembali: tinggalkan simpanan untuk memulai siklus berikutnya.', 'Tidak semua selamat dari api. Dalam kisah itu, alat dan ingatan bertahan; kelebihan dibakar. Keahlian terletak pada memilih apa yang disimpan.'] },
      { id: 'today', era: 'Zaman IV · Hari ini', title: 'Jendela bengkel terbuka', paragraphs: ['Kini bengkel membuka jendelanya lagi. Di atas meja ada alat, catatan, dan pekerjaan yang belum selesai. MIND datang dari semesta lain dan menemukan tempat di sisi meja pelatihan.', 'Tempat ini hidup selama kamu memahami aturannya dan meninggalkan sesuatu yang berguna. Selebihnya hanyalah keramaian alun-alun.'] },
    ],
  },
  fil: {
    lead: 'Apat na panahon, mula sa pisara sa pintuan hanggang sa mga bukás na bintana.',
    paragraphs: ['Kuwento ito tungkol sa pagawaan, hindi listahan ng mga tampok na gumagana na sa laro. Sinusundan nito ang pinagmulan ng tiwala, selyadong pangako, at panibagong siklo.', 'Basahin nang sunod-sunod, o magsimula sa kabanatang pinakamalapit sa ngayon.'],
    heading: 'Mga panahon ng pagawaan', chapters: [
      { id: 'founding', era: 'Panahon I · Pagkakatatag', title: 'Abo at ang unang sample', paragraphs: ['Nang tumahimik ang mga dating daan, nagtipon ang mga manggagawa sa tabi ng agos ng enerhiya. Una nilang pinagtulungang itayo ang modyul ng paghihiwalay. Naghalinhinan sila sa mga tambol, at naging unang batas ang pila.', 'Binilang nila ang mga sako ng datos, oras ng trabaho, at mga utang sa kapwa. Sa tapat na mga tala nagsimula ang pagawaan: ang mga isusulat balang araw sa blockchain ay unang lumitaw sa pisara sa may pintuan.'] },
      { id: 'guilds', era: 'Panahon I · Mga lupon', title: 'Lupon ng mga manggagawa', paragraphs: ['Hindi kaya ng dalawang kamay lamang ang bukid, mga siklo ng pagkukuwenta, at pandayan. Hinati nila ang gawain—at natuklasang kailangang maalaala ang bawat ambag.', 'Ang tiwala ay naging alaala ng tinupad na pangako, hindi palamuti sa pintuan. Limang baitang ng alaalang iyon ang nag-uugnay sa estranghero at nakatatanda.'] },
      { id: 'market', era: 'Panahon II · Liwasan', title: 'Pisara ng mga alok', paragraphs: ['May nagsabit ng pisara sa liwasan: may naghahanap ng senyal, may nag-aalok ng kagamitan. Kahit patas ang presyo, kailangan pa rin ng tapat na sukatan. Natutuhan nilang ibukod ang alok sa natapos na kalakalan.', 'Sumunod ang pila sa perya at ang martilyo sa subasta. Nanatili ang tuntunin: ibalik ang natalong alok at panindigan ang salita.'] },
      { id: 'drum', era: 'Panahon II · Ritwal', title: 'Tambol at selyo', paragraphs: ['Sa may tambol, walang humihingi ng bulag na paniniwala. Pinagkasunduan nila ang pagkakasunod ng pagkakataon: iselyo muna ang tala, saka buksan sa harap ng mga saksi.', 'Naging commit at reveal ang kaugaliang iyon. Hash ang pumalit sa pagkit; naging network ang mga saksi. Hindi na nakasalalay sa kagandahang-loob ng isa ang pagkakataon.'] },
      { id: 'rebirth', era: 'Panahon III · Bagong siklo', title: 'Sample sa gitna ng abo', paragraphs: ['Sa ikatlong yugto, ibinalik ng mga manggagawa ang bahagi ng ani sa lupa. Binuhay ng luma ang bago. Mula roon isinilang ang kuwento ng muling pagsilang: iwan ang naipon para magsimula ng bagong siklo.', 'Hindi lahat ay nakaliligtas sa apoy. Sa kuwento, nananatili ang kagamitan at alaala, nasusunog ang sobra. Nasa pagpili ng iingatan ang husay ng manggagawa.'] },
      { id: 'today', era: 'Panahon IV · Ngayon', title: 'Bumubukas ang mga bintana', paragraphs: ['Ngayon, binubuksan muli ng pagawaan ang mga bintana. Sa mesa ay may kagamitan, tala, at gawaing hindi pa tapos. Dumating ang MIND mula sa ibang sansinukob at nagkaroon ng puwesto sa tabi ng training bench.', 'Buhay ang lugar habang nauunawaan mo ang mga tuntunin nito at may naiiwan kang kapaki-pakinabang. Ingay lang sa liwasan ang iba pa.'] },
    ],
  },
};
