import type { Language } from './translations';

export const ruleIds = ['keys', 'cost', 'ai', 'support', 'devices', 'coercion', 'fair', 'risk', 'terms'] as const;
export type RuleId = typeof ruleIds[number];
export type RuleItem = { id: RuleId; title: string; paragraphs: readonly [string, string] };
type Copy = { lead: string; paragraphs: readonly [string, string]; heading: string; note: string; items: readonly RuleItem[] };

/** Editorial safety reminders, not the site's legal terms or a guarantee of transaction safety. */
export const siteRulesCopy: Record<Language, Copy> = {
  ru: {
    lead: 'Сначала проверь условия, потом действуй.',
    paragraphs: ['Осторожность начинается до подписи: читай адреса, суммы и состояние сети. Эта памятка не заменяет условия игры или проверку транзакции в кошельке.', 'Не раскрывай чужие секреты и не используй ошибки для присвоения активов. Если сомневаешься в действии, остановись и проверь его ещё раз.'],
    heading: 'Девять правил мастерской', note: 'Это советы по безопасности, не юридические условия и не подтверждение доступности функций.',
    items: [
      { id: 'keys', title: 'Береги ключи', paragraphs: ['Никому не передавай фразу восстановления, приватный или сессионный ключ. Вводи их только в доверенном интерфейсе своего кошелька; сайт игры не должен их запрашивать.', 'Храни резервную фразу вне скриншотов и облака. Если ключ утрачен или раскрыт, никто не может гарантировать восстановление средств.'] },
      { id: 'cost', title: 'Проверяй расход', paragraphs: ['Перед подписью сравни адреса, получателя, сумму, комиссии и разрешения с тем действием, которое выбрал. Не полагайся только на кнопку или текст сайта.', 'Если кошелёк показывает лишний перевод, неясную инструкцию или неограниченный расход, откажись и разберись. Отправка транзакции ещё не подтверждает результат.'] },
      { id: 'ai', title: 'Перепроверяй советы ИИ', paragraphs: ['Ответ ассистента или сообщение в чате не подтверждают адрес программы, цену, доступность функции или право на награду. Проверяй сведения в официальных источниках и в сети.', 'Не подписывай «проверочную» транзакцию по чьей-либо просьбе. Если содержимое подписи непонятно, остановись: убедительная формулировка не делает запрос безопасным.'] },
      { id: 'support', title: 'Остерегайся самозваной поддержки', paragraphs: ['Не переходи по ссылке из личного сообщения, выдающего себя за поддержку. Никому из команды не нужна твоя фраза восстановления или приватный ключ.', 'Проверь официальный канал самостоятельно через сайт. Даже знакомый логотип, аватар или история переписки не доказывают подлинность собеседника.'] },
      { id: 'devices', title: 'Защищай устройство', paragraphs: ['Обновляй браузер, систему и кошелёк из проверенных источников. Не устанавливай «специальный кошелёк» по ссылке из чата.', 'Для больших сумм рассмотри отдельный кошелёк или аппаратное устройство. Сверяй адрес и сумму на экране устройства и не соглашайся на слепую подпись.'] },
      { id: 'coercion', title: 'Не поддавайся давлению', paragraphs: ['Срочная просьба перевести активы «для разблокировки» или «проверки» — повод остановиться, а не спешить.', 'Если тебя принуждают или угрожают тебе, прежде всего заботься о своей безопасности и обращайся за помощью к людям или службам, которым доверяешь.'] },
      { id: 'fair', title: 'Не используй чужую ошибку', paragraphs: ['Нашёл уязвимость? Сообщи о ней через проверенный канал команды, не эксплуатируя ошибку и не раскрывая чужие данные.', 'Честная игра требует уважать чужие активы. Не считай сбой интерфейса разрешением забрать то, что тебе не принадлежит.'] },
      { id: 'risk', title: 'Не ищи гарантированной прибыли', paragraphs: ['Торговля, ставки и пулы сопряжены с рисками. Цена, ликвидность и условия могут меняться; сайт не гарантирует доход или возврат.', 'Проверь текущую доступность действия и параметры транзакции в игре и кошельке. Описание токена не устанавливает его правовой статус.'] },
      { id: 'terms', title: 'Сверяй действующие условия', paragraphs: ['Юридические и региональные ограничения узнавай из официальных условий опубликованной игры; эта памятка их не заменяет.', 'Экономические параметры могут измениться. Доверяй проверенному текущему состоянию сети, а не архиву статьи или снимку экрана.'] },
    ],
  },
  en: {
    lead: 'Check the terms before you act.',
    paragraphs: ['Care begins before you sign: inspect addresses, amounts and network status. This guide does not replace the game terms or a transaction review in your wallet.', 'Do not expose someone else’s secrets or exploit errors to take their assets. If an action feels uncertain, stop and check it again.'],
    heading: 'Nine workshop rules', note: 'These are safety tips, not legal terms or confirmation that a feature is available.',
    items: [
      { id: 'keys', title: 'Protect your keys', paragraphs: ['Never share your recovery phrase, private key or session key. Enter them only in your trusted wallet interface; the game website should not ask for them.', 'Keep your recovery phrase out of screenshots and cloud storage. If a key is lost or exposed, no one can guarantee recovery of your funds.'] },
      { id: 'cost', title: 'Check what you spend', paragraphs: ['Before signing, compare the addresses, recipient, amount, fees and permissions with the action you chose. Do not rely on a button or the site text alone.', 'If your wallet shows an extra transfer, an unclear instruction or unlimited spending, decline and investigate. Submitting a transaction does not yet confirm the outcome.'] },
      { id: 'ai', title: 'Double-check AI advice', paragraphs: ['An assistant’s answer or a chat message cannot verify a program address, price, feature or reward. Check official sources and the network instead.', 'Do not sign a “test” transaction at someone else’s request. If you cannot understand what you are signing, stop: persuasive wording cannot make it safe.'] },
      { id: 'support', title: 'Watch for fake support', paragraphs: ['Avoid links in direct messages claiming to be from support. No team member needs your recovery phrase or private key.', 'Find the official channel yourself through the website. A familiar logo, avatar or chat history is not proof of identity.'] },
      { id: 'devices', title: 'Secure your device', paragraphs: ['Update your browser, operating system and wallet from trusted sources. Do not install a “special wallet” from a chat link.', 'For larger amounts, consider a separate wallet or hardware device. Check the address and amount on the device screen, and avoid blind signing.'] },
      { id: 'coercion', title: 'Resist pressure', paragraphs: ['An urgent demand to transfer assets for “unlocking” or “verification” is a reason to stop, not to rush.', 'If you are threatened or coerced, prioritize your safety and seek help from people or services you trust.'] },
      { id: 'fair', title: 'Do not exploit mistakes', paragraphs: ['Found a vulnerability? Report it through a verified team channel without exploiting it or exposing other people’s data.', 'Fair play means respecting other people’s assets. A UI glitch is not permission to take what is not yours.'] },
      { id: 'risk', title: 'Do not expect guaranteed returns', paragraphs: ['Trades, wagers and pools carry risks. Prices, liquidity and terms may change; the site does not guarantee profit or refunds.', 'Check current availability and transaction details in the game and wallet. A token description does not determine its legal status.'] },
      { id: 'terms', title: 'Read the current terms', paragraphs: ['Consult the published game terms for legal and regional restrictions; this guide does not replace them.', 'Economic parameters can change. Rely on verified current network state, not an old article or screenshot.'] },
    ],
  },
  pt: {
    lead: 'Confere as condições antes de agir.',
    paragraphs: ['O cuidado começa antes de assinar: confere os endereços, os montantes e o estado da rede. Este guia não substitui os termos do jogo nem a verificação da transação na carteira.', 'Não reveles segredos alheios nem explores falhas para tomar ativos de terceiros. Se tens dúvidas, para e verifica de novo.'],
    heading: 'Nove regras da oficina', note: 'São conselhos de segurança, não termos legais nem confirmação de que uma função está disponível.',
    items: [
      { id: 'keys', title: 'Protege as tuas chaves', paragraphs: ['Nunca partilhes a frase de recuperação, a chave privada ou a chave de sessão. Introduz esses dados apenas na interface de uma carteira de confiança; o site do jogo não os deve pedir.', 'Guarda a frase de recuperação longe de capturas de ecrã e da nuvem. Se perderes ou expores a chave, ninguém pode garantir a recuperação dos fundos.'] },
      { id: 'cost', title: 'Confere o que vais gastar', paragraphs: ['Antes de assinar, compara endereços, destinatário, montante, taxas e permissões com a ação que escolheste. Não te fies só no botão ou no texto do site.', 'Se a carteira mostrar uma transferência extra, uma instrução pouco clara ou gastos sem limite, recusa e investiga. Enviar uma transação ainda não confirma o resultado.'] },
      { id: 'ai', title: 'Confirma os conselhos da IA', paragraphs: ['Uma resposta de IA ou mensagem de chat não verifica endereços de programas, preços, funções ou recompensas. Consulta as fontes oficiais e a rede.', 'Não assines uma transação de “teste” a pedido de alguém. Se não percebes o que assinas, para: palavras convincentes não tornam um pedido seguro.'] },
      { id: 'support', title: 'Desconfia do falso suporte', paragraphs: ['Evita links em mensagens privadas que se façam passar pelo suporte. Ninguém da equipa precisa da tua frase de recuperação ou chave privada.', 'Encontra o canal oficial por ti próprio no site. Um logótipo, avatar ou histórico de conversa conhecido não prova a identidade de ninguém.'] },
      { id: 'devices', title: 'Protege o dispositivo', paragraphs: ['Atualiza o navegador, o sistema e a carteira a partir de fontes fidedignas. Não instales uma “carteira especial” através de links de chat.', 'Para montantes maiores, considera uma carteira separada ou um dispositivo físico. Confere o endereço e o montante no ecrã do dispositivo; evita assinaturas às cegas.'] },
      { id: 'coercion', title: 'Não cedas à pressão', paragraphs: ['Um pedido urgente de transferência para “desbloquear” ou “verificar” ativos é motivo para parar, não para acelerar.', 'Se fores ameaçado ou coagido, põe a tua segurança em primeiro lugar e procura ajuda junto de pessoas ou serviços em quem confias.'] },
      { id: 'fair', title: 'Não explores erros alheios', paragraphs: ['Encontraste uma vulnerabilidade? Comunica-a por um canal verificado da equipa, sem a explorar nem divulgar dados de terceiros.', 'Jogar limpo é respeitar os ativos dos outros. Uma falha na interface não dá direito a tomar o que não é teu.'] },
      { id: 'risk', title: 'Não contes com lucros garantidos', paragraphs: ['Negociações, apostas e pools têm riscos. Preços, liquidez e condições podem mudar; o site não garante lucros nem reembolsos.', 'Verifica a disponibilidade e os detalhes da transação no jogo e na carteira. A descrição de um token não determina a sua situação jurídica.'] },
      { id: 'terms', title: 'Lê os termos em vigor', paragraphs: ['Consulta os termos oficiais do jogo para saber as restrições legais e regionais; este guia não os substitui.', 'Os parâmetros económicos podem mudar. Confia no estado atual e verificado da rede, não num artigo antigo ou captura de ecrã.'] },
    ],
  },
  es: {
    lead: 'Comprueba las condiciones antes de actuar.',
    paragraphs: ['La prudencia empieza antes de firmar: comprueba direcciones, importes y estado de la red. Esta guía no sustituye los términos del juego ni la revisión de la transacción en tu cartera.', 'No reveles secretos ajenos ni aproveches errores para apropiarte de activos de otros. Si dudas de una acción, detente y compruébala de nuevo.'],
    heading: 'Nueve reglas del taller', note: 'Son consejos de seguridad, no términos legales ni confirmación de que una función esté disponible.',
    items: [
      { id: 'keys', title: 'Protege tus claves', paragraphs: ['Nunca compartas tu frase de recuperación, clave privada o clave de sesión. Introdúcelas solo en la interfaz de una cartera de confianza; la web del juego no debe solicitarlas.', 'Guarda la frase de recuperación fuera de capturas de pantalla y de la nube. Si una clave se pierde o queda expuesta, nadie puede garantizar la recuperación de los fondos.'] },
      { id: 'cost', title: 'Comprueba lo que gastas', paragraphs: ['Antes de firmar, compara las direcciones, el destinatario, el importe, las comisiones y los permisos con la acción que elegiste. No te fíes solo de un botón o del texto de la web.', 'Si tu cartera muestra otra transferencia, una instrucción confusa o gastos ilimitados, recházala e investiga. Enviar una transacción aún no confirma el resultado.'] },
      { id: 'ai', title: 'Contrasta los consejos de la IA', paragraphs: ['La respuesta de un asistente o un mensaje de chat no verifica una dirección de programa, un precio, una función ni una recompensa. Contrasta la información con fuentes oficiales y con la red.', 'No firmes una transacción de “prueba” a petición de otra persona. Si no entiendes qué firmas, detente: una petición convincente no es necesariamente segura.'] },
      { id: 'support', title: 'Cuidado con el falso soporte', paragraphs: ['Evita los enlaces de mensajes privados que se presenten como soporte. Nadie del equipo necesita tu frase de recuperación o clave privada.', 'Busca por tu cuenta el canal oficial en la web. Un logotipo, avatar o historial de conversación conocidos no demuestran la identidad de nadie.'] },
      { id: 'devices', title: 'Protege tu dispositivo', paragraphs: ['Actualiza el navegador, el sistema y la cartera desde fuentes de confianza. No instales una “cartera especial” a través de un enlace de chat.', 'Para importes mayores, considera una cartera independiente o un dispositivo físico. Comprueba la dirección y el importe en su pantalla y evita firmar a ciegas.'] },
      { id: 'coercion', title: 'No cedas a la presión', paragraphs: ['Una petición urgente de transferir activos para “desbloquearlos” o “verificarlos” es motivo para parar, no para correr.', 'Si te amenazan o coaccionan, prioriza tu seguridad y pide ayuda a personas o servicios de confianza.'] },
      { id: 'fair', title: 'No aproveches errores ajenos', paragraphs: ['¿Has encontrado una vulnerabilidad? Comunícala por un canal verificado del equipo, sin explotarla ni divulgar datos de terceros.', 'Jugar limpio exige respetar los activos de otros. Un fallo de la interfaz no te autoriza a tomar lo que no es tuyo.'] },
      { id: 'risk', title: 'No esperes beneficios garantizados', paragraphs: ['Las operaciones, apuestas y pools conllevan riesgos. Precios, liquidez y condiciones pueden cambiar; la web no garantiza beneficios ni reembolsos.', 'Comprueba la disponibilidad y los detalles de la transacción en el juego y la cartera. La descripción de un token no determina su situación jurídica.'] },
      { id: 'terms', title: 'Lee las condiciones vigentes', paragraphs: ['Consulta las condiciones oficiales del juego para conocer restricciones legales y regionales; esta guía no las sustituye.', 'Los parámetros económicos pueden cambiar. Confía en el estado actual y verificado de la red, no en un artículo antiguo o una captura de pantalla.'] },
    ],
  },
  vi: {
    lead: 'Kiểm tra điều kiện trước khi hành động.',
    paragraphs: ['Cẩn trọng trước khi ký: kiểm tra địa chỉ, số tiền và trạng thái mạng. Hướng dẫn này không thay thế điều khoản trò chơi hay việc kiểm tra giao dịch trong ví.', 'Đừng tiết lộ bí mật của người khác hoặc lợi dụng lỗi để chiếm tài sản. Nếu chưa chắc chắn, hãy dừng lại và kiểm tra lần nữa.'],
    heading: 'Chín quy tắc của xưởng', note: 'Đây là lời khuyên an toàn, không phải điều khoản pháp lý hay xác nhận một tính năng đang hoạt động.',
    items: [
      { id: 'keys', title: 'Bảo vệ khóa của bạn', paragraphs: ['Không chia sẻ cụm từ khôi phục, khóa riêng hay khóa phiên với bất kỳ ai. Chỉ nhập chúng vào giao diện ví đáng tin cậy; trang trò chơi không được yêu cầu các thông tin đó.', 'Không lưu cụm từ khôi phục trong ảnh chụp màn hình hay trên đám mây. Nếu mất hoặc lộ khóa, không ai đảm bảo có thể lấy lại tài sản.'] },
      { id: 'cost', title: 'Kiểm tra khoản chi', paragraphs: ['Trước khi ký, đối chiếu địa chỉ, người nhận, số tiền, phí và quyền truy cập với hành động bạn đã chọn. Đừng chỉ tin vào nút bấm hoặc lời giới thiệu trên trang.', 'Nếu ví hiển thị thêm khoản chuyển, lệnh không rõ ràng hoặc quyền chi tiêu vô hạn, hãy từ chối và tìm hiểu. Gửi giao dịch chưa phải là xác nhận kết quả.'] },
      { id: 'ai', title: 'Kiểm chứng lời khuyên của AI', paragraphs: ['Câu trả lời của AI hay tin nhắn không thể xác minh địa chỉ chương trình, giá, tính năng hoặc phần thưởng. Hãy đối chiếu với nguồn chính thức và dữ liệu trên chuỗi.', 'Đừng ký giao dịch “thử” theo yêu cầu của người khác. Nếu không hiểu mình đang ký gì, hãy dừng lại; lời lẽ thuyết phục không khiến yêu cầu trở nên an toàn.'] },
      { id: 'support', title: 'Cảnh giác hỗ trợ giả mạo', paragraphs: ['Tránh các đường dẫn trong tin nhắn riêng tự nhận là hỗ trợ. Không ai trong đội ngũ cần cụm từ khôi phục hoặc khóa riêng của bạn.', 'Tự tìm kênh chính thức qua trang web. Logo, ảnh đại diện hay lịch sử trò chuyện quen thuộc không chứng minh danh tính.'] },
      { id: 'devices', title: 'Bảo vệ thiết bị', paragraphs: ['Cập nhật trình duyệt, hệ điều hành và ví từ nguồn đáng tin cậy. Đừng cài “ví đặc biệt” qua đường dẫn trong tin nhắn.', 'Với số tiền lớn, hãy cân nhắc ví riêng hoặc thiết bị phần cứng. Kiểm tra địa chỉ và số tiền trên màn hình thiết bị; tránh ký khi không xem được nội dung.'] },
      { id: 'coercion', title: 'Đừng để bị thúc ép', paragraphs: ['Yêu cầu chuyển tài sản gấp để “mở khóa” hay “xác minh” là lý do để dừng lại, không phải để vội vàng.', 'Nếu bị đe dọa hay ép buộc, hãy ưu tiên an toàn cá nhân và tìm sự giúp đỡ từ người hoặc dịch vụ bạn tin tưởng.'] },
      { id: 'fair', title: 'Đừng lợi dụng lỗi của người khác', paragraphs: ['Tìm thấy lỗ hổng? Hãy báo qua kênh đã xác minh của đội ngũ, không khai thác lỗi hay tiết lộ dữ liệu của người khác.', 'Chơi công bằng là tôn trọng tài sản của người khác. Lỗi giao diện không cho phép bạn lấy thứ không thuộc về mình.'] },
      { id: 'risk', title: 'Đừng mong lợi nhuận bảo đảm', paragraphs: ['Giao dịch, cược và nhóm thanh khoản đều có rủi ro. Giá, thanh khoản và điều kiện có thể thay đổi; trang này không đảm bảo lãi hay hoàn tiền.', 'Kiểm tra tính khả dụng và chi tiết giao dịch trong trò chơi và ví. Phần mô tả token không quyết định địa vị pháp lý của nó.'] },
      { id: 'terms', title: 'Đọc điều khoản hiện hành', paragraphs: ['Xem điều khoản chính thức của trò chơi để biết giới hạn pháp lý và khu vực; hướng dẫn này không thay thế chúng.', 'Thông số kinh tế có thể thay đổi. Hãy dựa vào trạng thái mạng hiện tại đã xác minh, không dựa vào bài viết cũ hay ảnh chụp màn hình.'] },
    ],
  },
  id: {
    lead: 'Periksa ketentuan sebelum bertindak.',
    paragraphs: ['Berhati-hatilah sebelum menandatangani: periksa alamat, jumlah, dan status jaringan. Panduan ini tidak menggantikan ketentuan permainan atau pemeriksaan transaksi di dompet.', 'Jangan ungkap rahasia orang lain atau manfaatkan kesalahan untuk mengambil aset mereka. Jika ragu, berhenti dan periksa kembali.'],
    heading: 'Sembilan aturan bengkel', note: 'Ini saran keselamatan, bukan ketentuan hukum atau konfirmasi bahwa suatu fitur tersedia.',
    items: [
      { id: 'keys', title: 'Lindungi kuncimu', paragraphs: ['Jangan bagikan frasa pemulihan, kunci pribadi, atau kunci sesi kepada siapa pun. Masukkan hanya di antarmuka dompet tepercaya; situs permainan tidak seharusnya memintanya.', 'Simpan frasa pemulihan di luar tangkapan layar dan penyimpanan awan. Jika kunci hilang atau bocor, tidak ada yang dapat menjamin danamu kembali.'] },
      { id: 'cost', title: 'Periksa pengeluaran', paragraphs: ['Sebelum menandatangani, cocokkan alamat, penerima, jumlah, biaya, dan izin dengan tindakan yang kamu pilih. Jangan hanya mengandalkan tombol atau tulisan di situs.', 'Jika dompet menampilkan transfer tambahan, instruksi yang tidak jelas, atau pengeluaran tanpa batas, tolak dan periksa. Mengirim transaksi belum memastikan hasilnya.'] },
      { id: 'ai', title: 'Periksa lagi saran AI', paragraphs: ['Jawaban asisten atau pesan obrolan tidak dapat memverifikasi alamat program, harga, fitur, atau hadiah. Bandingkan dengan sumber resmi dan data jaringan.', 'Jangan tanda tangani transaksi “uji coba” atas permintaan orang lain. Jika tidak paham apa yang kamu tanda tangani, berhenti: kata-kata meyakinkan tidak menjadikannya aman.'] },
      { id: 'support', title: 'Waspadai dukungan palsu', paragraphs: ['Hindari tautan dalam pesan pribadi yang mengaku dari dukungan. Anggota tim tidak memerlukan frasa pemulihan atau kunci pribadimu.', 'Cari sendiri kanal resmi melalui situs. Logo, avatar, atau riwayat percakapan yang tampak akrab tidak membuktikan identitas siapa pun.'] },
      { id: 'devices', title: 'Amankan perangkat', paragraphs: ['Perbarui peramban, sistem, dan dompet dari sumber tepercaya. Jangan pasang “dompet khusus” dari tautan obrolan.', 'Untuk jumlah besar, pertimbangkan dompet terpisah atau perangkat keras. Cocokkan alamat dan jumlah di layar perangkat; hindari menandatangani tanpa melihat rinciannya.'] },
      { id: 'coercion', title: 'Jangan tunduk pada tekanan', paragraphs: ['Permintaan mendesak untuk memindahkan aset demi “membuka kunci” atau “verifikasi” adalah alasan untuk berhenti, bukan terburu-buru.', 'Jika diancam atau dipaksa, utamakan keselamatanmu dan cari bantuan dari orang atau layanan yang kamu percayai.'] },
      { id: 'fair', title: 'Jangan manfaatkan kesalahan orang lain', paragraphs: ['Menemukan celah? Laporkan melalui kanal tim yang terverifikasi tanpa memanfaatkannya atau membocorkan data orang lain.', 'Bermain adil berarti menghormati aset orang lain. Gangguan antarmuka bukan izin untuk mengambil yang bukan milikmu.'] },
      { id: 'risk', title: 'Jangan mengharapkan untung pasti', paragraphs: ['Perdagangan, taruhan, dan pool memiliki risiko. Harga, likuiditas, dan ketentuan dapat berubah; situs tidak menjamin keuntungan atau pengembalian dana.', 'Periksa ketersediaan dan rincian transaksi dalam permainan dan dompet. Deskripsi token tidak menentukan status hukumnya.'] },
      { id: 'terms', title: 'Baca ketentuan terkini', paragraphs: ['Lihat ketentuan resmi permainan untuk batasan hukum dan wilayah; panduan ini tidak menggantikannya.', 'Parameter ekonomi dapat berubah. Andalkan keadaan jaringan terkini yang telah diverifikasi, bukan artikel lama atau tangkapan layar.'] },
    ],
  },
  fil: {
    lead: 'Suriin ang mga kundisyon bago kumilos.',
    paragraphs: ['Nagsisimula ang pag-iingat bago pumirma: tingnan ang mga address, halaga, at katayuan ng network. Hindi kapalit ng mga tuntunin ng laro o ng pagsusuri sa wallet ang gabay na ito.', 'Huwag ilantad ang lihim ng iba o samantalahin ang pagkakamali para kunin ang kanilang asset. Kung nag-aalinlangan, huminto at suriing muli.'],
    heading: 'Siyam na tuntunin ng pagawaan', note: 'Mga payong pangkaligtasan ito, hindi legal na tuntunin o patunay na magagamit ang isang tampok.',
    items: [
      { id: 'keys', title: 'Ingatan ang iyong mga key', paragraphs: ['Huwag ibahagi ang recovery phrase, private key, o session key sa sinuman. Ilagay lamang ang mga ito sa pinagkakatiwalaang wallet interface; hindi ito dapat hingin ng site ng laro.', 'Huwag itago ang recovery phrase sa screenshot o cloud. Kapag nawala o nalantad ang key, walang makagagarantiya na mababawi ang pondo.'] },
      { id: 'cost', title: 'Suriin ang gagastusin', paragraphs: ['Bago pumirma, itugma ang mga address, tatanggap, halaga, bayarin, at pahintulot sa pinili mong gawain. Huwag umasa lang sa buton o teksto ng site.', 'Kung may dagdag na transfer, hindi malinaw na instruksiyon, o walang limitasyong paggastos sa wallet, tanggihan at siyasatin ito. Hindi pa kumpirmasyon ng resulta ang pagpapadala ng transaksyon.'] },
      { id: 'ai', title: 'Suriin ang payo ng AI', paragraphs: ['Hindi napapatunayan ng sagot ng AI o mensahe sa chat ang address ng programa, presyo, tampok, o gantimpala. Ihambing sa mga opisyal na sanggunian at datos ng network.', 'Huwag pumirma ng “test” na transaksyon dahil lang may humiling. Kung hindi mo nauunawaan ang pipirmahan, huminto: hindi sapat ang kapani-paniwalang pananalita para maging ligtas ito.'] },
      { id: 'support', title: 'Mag-ingat sa pekeng suporta', paragraphs: ['Iwasan ang link sa pribadong mensaheng nagpapakilalang suporta. Hindi kailangan ng sinuman sa pangkat ang iyong recovery phrase o private key.', 'Hanapin mismo ang opisyal na channel sa site. Hindi patunay ng pagkakakilanlan ang pamilyar na logo, avatar, o kasaysayan ng usapan.'] },
      { id: 'devices', title: 'Protektahan ang device', paragraphs: ['I-update ang browser, system, at wallet mula sa mapagkakatiwalaang sanggunian. Huwag mag-install ng “espesyal na wallet” mula sa link sa chat.', 'Para sa malaking halaga, isaalang-alang ang hiwalay na wallet o hardware device. Suriin ang address at halaga sa screen ng device; iwasan ang pagpirma nang hindi nababasa ang detalye.'] },
      { id: 'coercion', title: 'Huwag magpadala sa pamimilit', paragraphs: ['Ang agarang hiling na maglipat ng asset para “i-unlock” o “i-verify” ito ay dahilan para huminto, hindi para magmadali.', 'Kung pinagbabantaan o pinipilit ka, unahin ang kaligtasan mo at humingi ng tulong sa mga tao o serbisyong pinagkakatiwalaan mo.'] },
      { id: 'fair', title: 'Huwag samantalahin ang pagkakamali', paragraphs: ['May natagpuang kahinaan? Iulat ito sa beripikadong channel ng pangkat nang hindi inaabuso o inilalantad ang datos ng iba.', 'Ang patas na laro ay paggalang sa asset ng iba. Hindi pahintulot ang error sa interface na kunin ang hindi sa iyo.'] },
      { id: 'risk', title: 'Walang garantisadong kita', paragraphs: ['May panganib ang kalakalan, pustahan, at mga pool. Maaaring magbago ang presyo, liquidity, at kundisyon; hindi ginagarantiya ng site ang kita o refund.', 'Suriin ang availability at detalye ng transaksyon sa laro at wallet. Hindi tinutukoy ng paglalarawan ng token ang legal na katayuan nito.'] },
      { id: 'terms', title: 'Basahin ang kasalukuyang tuntunin', paragraphs: ['Tingnan ang opisyal na tuntunin ng laro para sa mga limitasyong legal at panrehiyon; hindi ito mapapalitan ng gabay na ito.', 'Maaaring magbago ang mga parametro ng ekonomiya. Umasa sa kasalukuyang beripikadong estado ng network, hindi sa lumang artikulo o screenshot.'] },
    ],
  },
};
