import type { Language } from './translations';

export const shiftIds = ['wallet', 'garden', 'model', 'tool', 'market', 'season'] as const;
export type ShiftId = typeof shiftIds[number];
type Shift = { id: ShiftId; title: string; action: string; caution: string; image: string };
type Guide = { lead: string; paragraphs: readonly [string, string]; heading: string; steps: readonly Shift[]; note: string };

/** Editorial first-shift guide. No fixed duration, price, reward or enabled feature is presumed. */
export const siteGuide: Record<Language, Guide> = {
  ru: {
    lead: 'Шесть смен — от знакомства с кошельком до внимательного чтения сети.',
    paragraphs: ['Эта дорожная карта не запускает действия и не обещает заданий или наград. Перед каждым шагом смотри состояние игры, сети и запрос подписи в кошельке.', 'Путь можно прервать и вернуться позже. Неподтверждённые данные — причина остановиться, а не повод угадывать сумму, срок или результат.'],
    heading: 'Шесть смен мастера',
    steps: [
      { id: 'wallet', title: 'Вход в мастерскую', action: 'Подключи свой кошелёк через игру и проверь сеть и адрес сайта. Фразу восстановления никогда не вводи на странице игры.', caution: 'Подключение не требует подписи неожиданного платежа. Не подтверждай запрос, если не понимаешь его содержание.', image: 'Мастер сначала проверяет ключ, а уже потом открывает дверь мастерской.' },
      { id: 'garden', title: 'Сад образцов', action: 'Прочитай запас энергии и состояние лунок из сети. Если культивация доступна, сравни стоимость и результат до подписи, а съём проверяй лишь после подтверждения срока.', caution: 'Сбой чтения лунки — не свободное место. Повторное нажатие не ускоряет созревание.', image: 'У каждой лунки свой час; терпение здесь тоже инструмент.' },
      { id: 'model', title: 'От сигнала к модели', action: 'Сверь рецепт, ресурсный баланс и состояние сепарации перед запуском. После подтверждённого сбора сигнала отдельно проверь условия обучения модели.', caution: 'Начало цикла и получение результата — разные записи. Неполные данные не повод тратить материалы.', image: 'Сигнал не становится моделью от одного обещания: каждый этап оставляет след.' },
      { id: 'tool', title: 'Верный инструмент', action: 'Посмотри инвентарь и прочность собственного инструмента. Перед сборкой или ремонтом запроси свежую стоимость и сверяй её с тем, что подписывает кошелёк.', caution: 'Изображение каталога не доказывает владение NFT; цена в старом тексте не заменяет сетевую смету.', image: 'Хороший мастер слушает, как меняется металл, и чинит его не вслепую.' },
      { id: 'market', title: 'Площадь обмена', action: 'Смотри только проверенные листинги и сумму конкретной сделки. Сверь владельца, предмет, получателя и комиссию в кошельке.', caution: 'Новые заявки и сведение в книге заявок приостановлены. Не подписывай их по старой форме цены.', image: 'На площади шумно, но последняя цифра должна прозвучать ясно.' },
      { id: 'season', title: 'Долгое дыхание эпохи', action: 'Проверь статус сезона и пропуска по текущим данным сети. Ищи подтверждение прогресса, прежде чем считать какую-либо награду полученной.', caution: 'Индекс заданий и наград ещё недоступен. Перерождение берёт цену, сбрасывает прогресс сезона и сжигает излишки одной транзакцией — проверь цену и список излишков на панели перед подписью.', image: 'Длинный путь строится из подтверждённых шагов, а не из нарисованного финиша.' },
    ],
    note: 'Это путеводитель по возможным действиям, не предложение транзакций. Если сеть недоступна, не считай прогресс, стоимость или награду подтверждёнными.',
  },
  en: {
    lead: 'Six shifts, from meeting your wallet to reading the network with care.',
    paragraphs: ['This guide starts no actions and promises no quests or rewards. At every step, inspect the game, network state and wallet signature request.', 'Pause whenever you need to. Unverified data is a reason to stop, not to guess a price, deadline or outcome.'],
    heading: 'Six workshop shifts',
    steps: [
      { id: 'wallet', title: 'Enter the workshop', action: 'Connect your wallet through the game and check the network and site address. Never enter your recovery phrase on the game page.', caution: 'Connecting should not require signing an unexpected payment. Decline a request you do not understand.', image: 'The maker checks the key before opening the workshop door.' },
      { id: 'garden', title: 'The sample garden', action: 'Read your energy and well status from the network. If cultivation is available, check cost and output before signing; harvest only after the time is confirmed.', caution: 'A failed well read is not an empty well. Clicking again cannot speed up growth.', image: 'Every well keeps its own hour; patience is a tool too.' },
      { id: 'model', title: 'From signal to model', action: 'Check the recipe, resource balance and separator status before starting. After a confirmed signal collection, review the model-training terms separately.', caution: 'Starting a cycle and receiving its result are different records. Do not spend on incomplete data.', image: 'A signal cannot become a model on a promise alone: each stage leaves a trace.' },
      { id: 'tool', title: 'A trusty tool', action: 'Inspect the inventory and durability of a tool you own. Before crafting or repairing, get a fresh quote and compare it with the wallet request.', caution: 'Catalog art does not prove NFT ownership; an old article price is not a live quote.', image: 'A careful maker listens to the metal and never repairs blind.' },
      { id: 'market', title: 'The trading square', action: 'Look at verified listings and the amount for the particular trade. Check the owner, item, recipient and fees in your wallet.', caution: 'New order-book placement and matching are paused. Do not sign them using the old price form.', image: 'The square is noisy, but the final number should ring clear.' },
      { id: 'season', title: 'The long breath of a season', action: 'Check the season and pass status against current network data. Look for verified progress before counting any reward as received.', caution: 'The quest/reward index is unavailable. Rebirth charges a price, resets season progress and burns the surplus in one transaction — check the price and the surplus list on the panel before signing.', image: 'A long path is built from confirmed steps, not a painted finish line.' },
    ],
    note: 'This is a guide to possible actions, not a transaction offer. If the network is unavailable, progress, cost and rewards are unconfirmed.',
  },
  pt: {
    lead: 'Seis turnos: da primeira ligação da carteira à leitura atenta da rede.',
    paragraphs: ['Este guia não inicia ações nem promete missões ou recompensas. Em cada passo, confere o jogo, o estado da rede e o pedido de assinatura da carteira.', 'Podes parar e voltar mais tarde. Dados não verificados são motivo para parar, não para adivinhar preços, prazos ou resultados.'],
    heading: 'Seis turnos na oficina',
    steps: [
      { id: 'wallet', title: 'Entra na oficina', action: 'Liga a carteira pelo jogo e confere a rede e o endereço do site. Nunca introduzas a frase de recuperação na página do jogo.', caution: 'Ligar a carteira não deve exigir um pagamento inesperado. Recusa um pedido que não compreendas.', image: 'O mestre confere a chave antes de abrir a porta da oficina.' },
      { id: 'garden', title: 'O jardim das amostras', action: 'Consulta energia e estado dos poços na rede. Se o cultivo estiver disponível, verifica custo e resultado antes de assinar; colhe só depois de confirmar o prazo.', caution: 'Uma falha na leitura do poço não significa que esteja vazio. Clicar de novo não acelera o crescimento.', image: 'Cada poço tem a sua hora; a paciência também é uma ferramenta.' },
      { id: 'model', title: 'Do sinal ao modelo', action: 'Verifica receita, saldo de recursos e estado da separação antes de começar. Depois de recolher o sinal com confirmação, confere em separado as condições de treino.', caution: 'Iniciar um ciclo e receber o resultado são registos distintos. Não gastes materiais com dados incompletos.', image: 'O sinal não vira modelo por uma promessa: cada etapa deixa uma marca.' },
      { id: 'tool', title: 'Uma ferramenta fiel', action: 'Consulta o inventário e a durabilidade de uma ferramenta tua. Antes de criar ou reparar, pede um orçamento atualizado e compara-o com o pedido da carteira.', caution: 'A imagem do catálogo não prova que tens o NFT; o preço de um artigo antigo não substitui um orçamento atual.', image: 'O mestre ouve o metal mudar e não o repara às cegas.' },
      { id: 'market', title: 'A praça das trocas', action: 'Consulta anúncios verificados e o montante da operação concreta. Confere proprietário, objeto, destinatário e taxas na carteira.', caution: 'Novas ordens e cruzamentos no livro estão suspensos. Não assines pelo formulário de preços antigo.', image: 'A praça é ruidosa, mas o número final deve soar claro.' },
      { id: 'season', title: 'O longo fôlego da época', action: 'Confere o estado da época e do passe nos dados atuais da rede. Procura progresso verificado antes de contar recompensas como recebidas.', caution: 'O índice de missões e recompensas está indisponível. O renascimento cobra um preço, reinicia o progresso da temporada e queima o excedente numa transação — confere o preço e a lista na painel antes de assinar.', image: 'O caminho comprido faz-se de passos confirmados, não de uma chegada pintada.' },
    ],
    note: 'É um guia de ações possíveis, não uma oferta de transações. Sem rede, progresso, custo e recompensas não estão confirmados.',
  },
  es: {
    lead: 'Seis turnos, desde conocer tu cartera hasta leer la cadena con atención.',
    paragraphs: ['Esta guía no inicia acciones ni promete misiones o recompensas. En cada paso, comprueba el juego, el estado de la red y la petición de firma de tu cartera.', 'Puedes detenerte y regresar después. Los datos sin verificar son motivo para parar, no para adivinar precios, plazos o resultados.'],
    heading: 'Seis turnos en el taller',
    steps: [
      { id: 'wallet', title: 'Entra en el taller', action: 'Conecta tu cartera a través del juego y comprueba la red y la dirección de la web. Nunca introduzcas la frase de recuperación en la página del juego.', caution: 'Conectar no debería exigir firmar un pago inesperado. Rechaza las peticiones que no comprendas.', image: 'El artesano comprueba la llave antes de abrir la puerta del taller.' },
      { id: 'garden', title: 'El jardín de muestras', action: 'Consulta tu energía y el estado de los pozos en la red. Si puedes cultivar, revisa coste y resultado antes de firmar; cosecha solo tras confirmar el plazo.', caution: 'Un fallo al leer un pozo no significa que esté libre. Pulsar de nuevo no acelera el crecimiento.', image: 'Cada pozo guarda su hora; la paciencia también es herramienta.' },
      { id: 'model', title: 'De la señal al modelo', action: 'Comprueba la receta, el saldo y el estado del separador antes de empezar. Tras recoger una señal confirmada, revisa por separado las condiciones de entrenamiento.', caution: 'Iniciar un ciclo y recibir su resultado son registros diferentes. No gastes con datos incompletos.', image: 'Una señal no se vuelve modelo por una promesa: cada etapa deja huella.' },
      { id: 'tool', title: 'Una herramienta fiel', action: 'Consulta el inventario y la durabilidad de tu herramienta. Antes de fabricar o reparar, pide un presupuesto nuevo y compáralo con lo que solicita tu cartera.', caution: 'El arte del catálogo no demuestra que poseas el NFT; un precio antiguo no sustituye el presupuesto actual.', image: 'El artesano atento escucha el metal y nunca repara a ciegas.' },
      { id: 'market', title: 'La plaza del intercambio', action: 'Consulta anuncios verificados y el importe de la operación concreta. Comprueba propietario, objeto, destinatario y tasas en tu cartera.', caution: 'Nuevas órdenes y cruces del libro están suspendidos. No firmes órdenes con el formulario de precios antiguo.', image: 'La plaza es ruidosa, pero la cifra final debe sonar clara.' },
      { id: 'season', title: 'El largo aliento de una época', action: 'Consulta el estado de la época y del pase en los datos actuales de la cadena. Busca progreso confirmado antes de contar una recompensa como recibida.', caution: 'El índice de misiones y recompensas no está disponible. El renacimiento cobra un precio, reinicia el progreso de la temporada y quema el excedente en una transacción: revisa el precio y la lista en el panel antes de firmar.', image: 'El camino largo se traza con pasos confirmados, no con una meta pintada.' },
    ],
    note: 'Es una guía de acciones posibles, no una oferta de transacciones. Sin red, ni el progreso ni los costes ni las recompensas están confirmados.',
  },
  vi: {
    lead: 'Sáu ca làm việc, từ kết nối ví đến đọc dữ liệu mạng một cách cẩn trọng.',
    paragraphs: ['Hướng dẫn này không bắt đầu hành động hay hứa hẹn nhiệm vụ, phần thưởng. Ở mỗi bước, hãy kiểm tra trò chơi, trạng thái mạng và yêu cầu ký trong ví.', 'Bạn có thể dừng rồi quay lại sau. Dữ liệu chưa xác minh là lý do để dừng, không phải để đoán giá, thời hạn hay kết quả.'],
    heading: 'Sáu ca trong xưởng',
    steps: [
      { id: 'wallet', title: 'Bước vào xưởng', action: 'Kết nối ví qua trò chơi và kiểm tra mạng cùng địa chỉ trang web. Không bao giờ nhập cụm từ khôi phục trên trang trò chơi.', caution: 'Kết nối ví không được yêu cầu ký khoản thanh toán bất ngờ. Từ chối yêu cầu bạn không hiểu.', image: 'Người thợ kiểm tra chìa khóa trước khi mở cửa xưởng.' },
      { id: 'garden', title: 'Vườn mẫu vật', action: 'Đọc năng lượng và trạng thái ô nuôi cấy từ mạng. Nếu được nuôi cấy, hãy kiểm tra chi phí và sản lượng trước khi ký; chỉ thu hoạch khi đã xác nhận thời điểm.', caution: 'Không đọc được trạng thái ô không có nghĩa ô đang trống. Nhấn lần nữa không làm mẫu lớn nhanh hơn.', image: 'Mỗi ô giữ nhịp giờ riêng; kiên nhẫn cũng là một công cụ.' },
      { id: 'model', title: 'Từ tín hiệu đến mô hình', action: 'Kiểm tra công thức, số dư và trạng thái tách mẫu trước khi bắt đầu. Sau khi thu tín hiệu đã xác nhận, hãy xem riêng điều kiện huấn luyện mô hình.', caution: 'Bắt đầu chu kỳ và nhận kết quả là hai bản ghi khác nhau. Đừng tiêu vật liệu khi thiếu dữ liệu.', image: 'Tín hiệu không thể thành mô hình chỉ nhờ lời hứa: mỗi bước đều để lại dấu vết.' },
      { id: 'tool', title: 'Công cụ đáng tin', action: 'Xem kho đồ và độ bền của công cụ thuộc về bạn. Trước khi chế tạo hoặc sửa chữa, lấy báo giá mới rồi đối chiếu với yêu cầu trong ví.', caution: 'Hình trong danh mục không chứng minh bạn sở hữu NFT; giá trong bài cũ không thay thế báo giá hiện tại.', image: 'Người thợ giỏi lắng nghe kim loại thay đổi, không sửa chữa mù quáng.' },
      { id: 'market', title: 'Quảng trường trao đổi', action: 'Chỉ xem tin rao đã xác minh và số tiền của giao dịch cụ thể. Kiểm tra chủ sở hữu, vật phẩm, người nhận và phí trong ví.', caution: 'Lệnh mới và khớp lệnh trong sổ lệnh đang tạm dừng. Đừng ký qua biểu mẫu giá cũ.', image: 'Quảng trường ồn ào, nhưng con số cuối cùng phải rõ ràng.' },
      { id: 'season', title: 'Hơi thở dài của mùa giải', action: 'Xem trạng thái mùa giải và thẻ từ dữ liệu mạng hiện tại. Tìm tiến độ đã xác minh trước khi coi phần thưởng là đã nhận.', caution: 'Chưa có chỉ mục nhiệm vụ và phần thưởng. Tái sinh thu phí, đặt lại tiến trình mùa và đốt phần dư trong một giao dịch — hãy kiểm tra giá và danh sách phần dư trên bảng trước khi ký.', image: 'Đường dài được dựng từ bước chân đã xác nhận, không phải đích đến vẽ sẵn.' },
    ],
    note: 'Đây là hướng dẫn các hành động có thể thực hiện, không phải lời mời giao dịch. Khi mạng không hoạt động, tiến độ, chi phí và phần thưởng đều chưa được xác nhận.',
  },
  id: {
    lead: 'Enam giliran, dari mengenal dompet hingga membaca jaringan dengan cermat.',
    paragraphs: ['Panduan ini tidak memulai tindakan atau menjanjikan misi maupun hadiah. Di setiap tahap, periksa permainan, status jaringan, dan permintaan tanda tangan di dompet.', 'Kamu boleh berhenti dan kembali nanti. Data yang belum diverifikasi adalah alasan untuk berhenti, bukan menebak harga, tenggat, atau hasil.'],
    heading: 'Enam giliran di bengkel',
    steps: [
      { id: 'wallet', title: 'Masuk ke bengkel', action: 'Hubungkan dompet lewat permainan dan periksa jaringan serta alamat situs. Jangan pernah memasukkan frasa pemulihan di halaman permainan.', caution: 'Menghubungkan dompet tidak boleh meminta tanda tangan pembayaran tak terduga. Tolak permintaan yang tidak kamu pahami.', image: 'Perajin memeriksa kunci sebelum membuka pintu bengkel.' },
      { id: 'garden', title: 'Kebun sampel', action: 'Baca energi dan status wadah dari jaringan. Jika kultivasi tersedia, periksa biaya dan hasil sebelum tanda tangan; panen setelah waktunya terkonfirmasi.', caution: 'Gagal membaca wadah bukan berarti wadah kosong. Menekan tombol lagi tidak mempercepat pertumbuhan.', image: 'Setiap wadah punya waktunya sendiri; kesabaran juga sebuah peralatan.' },
      { id: 'model', title: 'Dari sinyal ke model', action: 'Periksa resep, saldo, dan status pemisahan sebelum memulai. Setelah mengambil sinyal yang terkonfirmasi, periksa ketentuan pelatihan model secara terpisah.', caution: 'Memulai siklus dan menerima hasilnya adalah dua catatan berbeda. Jangan memakai bahan saat data tidak lengkap.', image: 'Sinyal tidak menjadi model hanya karena janji; setiap tahap meninggalkan jejak.' },
      { id: 'tool', title: 'Peralatan tepercaya', action: 'Periksa inventaris dan daya tahan peralatan milikmu. Sebelum merakit atau memperbaiki, minta harga terbaru dan bandingkan dengan permintaan dompet.', caution: 'Gambar katalog bukan bukti kepemilikan NFT; harga dari artikel lama bukan penawaran terbaru.', image: 'Perajin yang teliti mendengar perubahan logam dan tak pernah memperbaiki secara membabi buta.' },
      { id: 'market', title: 'Alun-alun perdagangan', action: 'Lihat lapak terverifikasi dan jumlah untuk transaksi tertentu. Periksa pemilik, barang, penerima, serta biaya di dompet.', caution: 'Pesanan baru dan pencocokan buku pesanan sedang ditunda. Jangan tanda tangani pesanan melalui formulir harga lama.', image: 'Alun-alun memang riuh, tetapi angka terakhir harus terdengar jelas.' },
      { id: 'season', title: 'Napas panjang sebuah musim', action: 'Periksa status musim dan pass lewat data jaringan terbaru. Cari progres yang terverifikasi sebelum menganggap hadiah telah diterima.', caution: 'Indeks misi dan hadiah belum tersedia. Kelahiran kembali memungut biaya, mengatur ulang kemajuan musim, dan membakar kelebihan dalam satu transaksi — periksa harga dan daftar kelebihan di panel sebelum menandatangani.', image: 'Jalan panjang disusun dari langkah yang terkonfirmasi, bukan garis akhir yang digambar.' },
    ],
    note: 'Ini panduan tindakan yang mungkin, bukan penawaran transaksi. Jika jaringan tidak tersedia, progres, biaya, dan hadiah belum dapat dikonfirmasi.',
  },
  fil: {
    lead: 'Anim na turno, mula sa pagkilala sa wallet hanggang sa maingat na pagbasa sa network.',
    paragraphs: ['Walang sinisimulang gawain o ipinapangakong quest o gantimpala ang gabay na ito. Sa bawat hakbang, tingnan ang laro, estado ng network, at hinihinging pirma ng wallet.', 'Puwede kang huminto at bumalik. Dahilan para tumigil ang datos na hindi beripikado, hindi para hulaan ang presyo, takdang oras, o resulta.'],
    heading: 'Anim na turno sa pagawaan',
    steps: [
      { id: 'wallet', title: 'Pumasok sa pagawaan', action: 'Ikonekta ang wallet sa laro at suriin ang network at address ng site. Huwag kailanman ilagay ang recovery phrase sa pahina ng laro.', caution: 'Hindi dapat humingi ng lagda sa hindi inaasahang bayad ang pagkonekta. Tanggihan ang hiling na hindi mo nauunawaan.', image: 'Tinitingnan muna ng panday ang susi bago buksan ang pagawaan.' },
      { id: 'garden', title: 'Hardin ng mga sample', action: 'Basahin sa network ang enerhiya at estado ng mga puwesto. Kung bukas ang pagpapalaki, suriin ang gastos at bunga bago pumirma; anihin lamang kapag kumpirmado na ang oras.', caution: 'Ang bigong pagbasa sa puwesto ay hindi patunay na bakante ito. Hindi pinabibilis ng paulit-ulit na pagpindot ang paglaki.', image: 'May sariling oras ang bawat puwesto; kagamitan din ang pagtitiis.' },
      { id: 'model', title: 'Mula signal hanggang modelo', action: 'Suriin ang resipe, balanse, at estado ng paghihiwalay bago magsimula. Kapag kumpirmado ang pagkakuha ng signal, suriin nang hiwalay ang kundisyon sa pagsasanay.', caution: 'Magkaibang tala ang pagsisimula ng siklo at pagtanggap ng bunga. Huwag gumastos kung kulang ang datos.', image: 'Hindi nagiging modelo ang signal sa pangako lang; may bakas ang bawat yugto.' },
      { id: 'tool', title: 'Tapat na kagamitan', action: 'Tingnan ang imbentaryo at tibay ng kagamitang pag-aari mo. Bago gumawa o magkumpuni, humingi ng bagong presyo at ihambing sa kahilingan ng wallet.', caution: 'Hindi patunay ng NFT ownership ang larawan sa katalogo; hindi kapalit ng bagong presyo ang lumang artikulo.', image: 'Pinakikinggan ng maingat na panday ang pagbabago ng metal at hindi basta kumikilos nang bulag.' },
      { id: 'market', title: 'Liwasan ng palitan', action: 'Tingnan ang beripikadong listahan at halaga ng mismong transaksyon. Suriin sa wallet ang may-ari, gamit, tatanggap, at bayarin.', caution: 'Nakatigil ang bagong order at pagtutugma sa talaan. Huwag pumirma gamit ang lumang pormularyo ng presyo.', image: 'Maingay ang liwasan, ngunit dapat malinaw ang huling bilang.' },
      { id: 'season', title: 'Mahabang hininga ng panahon', action: 'Suriin ang estado ng panahon at pass gamit ang kasalukuyang datos ng network. Humanap ng beripikadong progreso bago ituring na nakuha ang gantimpala.', caution: 'Hindi pa available ang index ng quest at gantimpala. May bayad ang muling pagsilang, ni-reset ang progreso ng panahon, at sinusunog ang sobra sa isang transaksyon — tingnan ang presyo at listahan sa panel bago pumirma.', image: 'Binubuo ang mahabang landas ng mga kumpirmadong hakbang, hindi ng ipinintang dulo.' },
    ],
    note: 'Gabay ito sa maaaring gawain, hindi alok na transaksyon. Kung hindi maabot ang network, hindi pa kumpirmado ang progreso, halaga, o gantimpala.',
  },
};
