import type { Language } from './translations';

export type IntroId = 'start' | 'world' | 'energy';
type Intro = { lead: string; paragraphs: readonly string[]; steps?: { heading: string; items: readonly { title: string; text: string }[] } };
export const introPages: Record<Language, Record<IntroId, Intro>> = {
  ru: {
    start: { lead: 'От подключения кошелька до первого результата.', paragraphs: ['Изучи энергию, прочность и стоимость действий. Подключи Solana-кошелёк.','Не вводи seed-фразу на сайте. Подпись запрашивает кошелёк. Проверяй сеть, адрес программы и разрешения.','Начни с короткой цепочки: сетевая станция → культивация → съём. Перед сборкой проверь рецепт, перед продажей — цену и комиссию.'], steps: { heading: 'Газ · порядок действий', items: [{ title: 'Проверь запас', text: 'Ориентируйся на актуальное состояние игры.' },{ title: 'Пополняй осознанно', text: 'Сверь доступность, стоимость и результат.' },{ title: 'Контролируй разрешения', text: 'Описание сайта не отправляет транзакцию.' }] } },
    world: { lead: 'Четыре модуля одной системы.', paragraphs: ['Лаборатория культивирует образцы. Модуль сепарации и учебный стенд продолжают цепочку. Добыча и экспедиции дают редкие материалы.','Квантовая кузница превращает ресурсы в инструменты. Износ ведёт к ремонту. Рынок связывает твою работу с другими операторами.','Нагрузка сети меняет условия. Эпохи задают длинный ритм. Переобучение связывает окончание одного пути с началом другого.'] },
    energy: { lead: '20 единиц — запас действий, а не повод торопиться.', paragraphs: ['Диапазон энергии: 0–20. Перед действием сравни текущий запас и цену.','Регенерация: +1 единица каждые 30 минут. Действия тратят: культивация 1, съём 1, сепарация 2, обучение 2.'], steps: { heading: 'Энергия · порядок действий', items: [{ title: 'Проверь запас', text: 'Ориентируйся на актуальное состояние игры.' },{ title: 'Сравни стоимость', text: 'Сверь доступность, стоимость и результат.' },{ title: 'Восстанови при необходимости', text: 'Описание сайта не отправляет транзакцию.' }] } },
  },
  en: {
    start: { lead: 'From connecting a wallet to your first result.', paragraphs: ['Check your energy, tool durability and the cost of each action. Then connect a Solana wallet.','Never enter a seed phrase on this site. Your wallet handles signing. Check the network, program address and permissions before you approve anything.','Start with a short chain: network station → cultivation → harvest. Check the recipe before crafting and the price and fee before selling.'], steps: { heading: 'Gas · step by step', items: [{ title: 'Check your balance', text: 'Use the current in-game balance, not a figure from this guide.' },{ title: 'Top up with care', text: 'Review the available amount, cost and expected result before signing.' },{ title: 'Review permissions', text: 'This guide never submits a transaction.' }] } },
    world: { lead: 'Four modules, one interconnected system.', paragraphs: ['The laboratory grows samples. The separation module and training bench carry them forward. Mining and expeditions yield rare materials.','The quantum forge turns resources into tools. Worn tools need repair. The marketplace connects your work with other operators.','Network load changes the conditions. Epochs set the long rhythm. Retraining turns the end of one path into the beginning of another.'] },
    energy: { lead: '20 energy is a budget for action, not a reason to rush.', paragraphs: ['Energy ranges from 0 to 20. Check your current balance against the cost before acting.','Regeneration restores 1 energy every 30 minutes. Cultivation and harvesting cost 1 each; separation and training cost 2 each.'], steps: { heading: 'Energy · step by step', items: [{ title: 'Check your balance', text: 'Use the current energy shown in the game.' },{ title: 'Compare costs', text: 'Check availability, cost and the expected result.' },{ title: 'Wait for recovery when needed', text: 'This guide never submits a transaction.' }] } },
  },
  pt: {
    start: { lead: 'Da conexão da carteira ao primeiro resultado.', paragraphs: ['Confira a energia, a durabilidade das ferramentas e o custo de cada ação. Depois, conecte uma carteira Solana.','Nunca digite uma frase-semente neste site. A assinatura acontece na sua carteira. Confira a rede, o endereço do programa e as permissões antes de aprovar.','Comece com uma cadeia curta: estação de rede → cultivo → coleta. Antes de criar, confira a receita; antes de vender, confira preço e taxa.'], steps: { heading: 'Gás · passo a passo', items: [{ title: 'Confira o saldo', text: 'Use o saldo atual do jogo, não um valor deste guia.' },{ title: 'Abasteça com cuidado', text: 'Confira o valor disponível, o custo e o resultado esperado antes de assinar.' },{ title: 'Revise as permissões', text: 'Este guia não envia transações.' }] } },
    world: { lead: 'Quatro módulos, um sistema interligado.', paragraphs: ['O laboratório cultiva amostras. O módulo de separação e a bancada de treinamento dão continuidade ao processo. Extração e expedições fornecem materiais raros.','A forja quântica transforma recursos em ferramentas. Ferramentas gastas precisam de reparo. O mercado liga seu trabalho ao de outros operadores.','A carga da rede altera as condições. As épocas definem um ritmo mais longo. O retreinamento transforma o fim de um caminho no começo de outro.'] },
    energy: { lead: '20 unidades de energia são um orçamento, não um convite à pressa.', paragraphs: ['A energia varia de 0 a 20. Compare seu saldo atual com o custo antes de agir.','A regeneração devolve 1 unidade a cada 30 minutos. Cultivo e coleta custam 1 cada; separação e treinamento custam 2 cada.'], steps: { heading: 'Energia · passo a passo', items: [{ title: 'Confira o saldo', text: 'Consulte a energia atual exibida no jogo.' },{ title: 'Compare os custos', text: 'Confira disponibilidade, custo e resultado esperado.' },{ title: 'Espere recuperar, se necessário', text: 'Este guia não envia transações.' }] } },
  },
  es: {
    start: { lead: 'De conectar la cartera a obtener el primer resultado.', paragraphs: ['Comprueba la energía, la durabilidad de las herramientas y el coste de cada acción. Después conecta una cartera de Solana.','Nunca introduzcas una frase semilla en este sitio. Tu cartera se encarga de firmar. Revisa la red, la dirección del programa y los permisos antes de aprobar.','Empieza con una cadena corta: estación de red → cultivo → recolección. Antes de fabricar, comprueba la receta; antes de vender, revisa el precio y la comisión.'], steps: { heading: 'Gas · paso a paso', items: [{ title: 'Comprueba tu saldo', text: 'Consulta el saldo actual en el juego, no una cifra de esta guía.' },{ title: 'Recarga con cuidado', text: 'Revisa la cantidad disponible, el coste y el resultado esperado antes de firmar.' },{ title: 'Revisa los permisos', text: 'Esta guía nunca envía una transacción.' }] } },
    world: { lead: 'Cuatro módulos, un sistema interconectado.', paragraphs: ['El laboratorio cultiva muestras. El módulo de separación y la mesa de entrenamiento continúan el proceso. La extracción y las expediciones proporcionan materiales raros.','La forja cuántica transforma recursos en herramientas. Las herramientas gastadas necesitan reparación. El mercado conecta tu trabajo con el de otros operadores.','La carga de la red cambia las condiciones. Las épocas marcan un ritmo más largo. El reentrenamiento convierte el final de un camino en el inicio de otro.'] },
    energy: { lead: '20 de energía son un presupuesto para actuar, no una razón para correr.', paragraphs: ['La energía va de 0 a 20. Compara tu saldo actual con el coste antes de actuar.','La regeneración devuelve 1 punto cada 30 minutos. Cultivar y recolectar cuestan 1 cada uno; separar y entrenar cuestan 2 cada uno.'], steps: { heading: 'Energía · paso a paso', items: [{ title: 'Comprueba el saldo', text: 'Consulta la energía actual que muestra el juego.' },{ title: 'Compara los costes', text: 'Revisa disponibilidad, coste y resultado esperado.' },{ title: 'Espera a que se recupere si hace falta', text: 'Esta guía nunca envía una transacción.' }] } },
  },
  vi: {
    start: { lead: 'Từ kết nối ví đến kết quả đầu tiên.', paragraphs: ['Kiểm tra năng lượng, độ bền công cụ và chi phí từng hành động. Sau đó kết nối ví Solana.','Đừng bao giờ nhập cụm từ khôi phục ví trên trang này. Ví của bạn xử lý chữ ký. Hãy kiểm tra mạng, địa chỉ chương trình và quyền truy cập trước khi chấp thuận.','Bắt đầu với chuỗi ngắn: trạm mạng → nuôi cấy → thu hoạch. Kiểm tra công thức trước khi chế tạo; kiểm tra giá và phí trước khi bán.'], steps: { heading: 'Gas · từng bước', items: [{ title: 'Kiểm tra số dư', text: 'Dùng số dư hiện tại trong trò chơi, không dùng con số trong hướng dẫn này.' },{ title: 'Nạp một cách cẩn trọng', text: 'Xem lại số tiền, chi phí và kết quả dự kiến trước khi ký.' },{ title: 'Kiểm tra quyền truy cập', text: 'Hướng dẫn này không gửi giao dịch.' }] } },
    world: { lead: 'Bốn mô-đun trong một hệ thống liên kết.', paragraphs: ['Phòng thí nghiệm nuôi cấy mẫu. Mô-đun tách và bàn huấn luyện tiếp nối chuỗi sản xuất. Khai thác và thám hiểm mang về vật liệu hiếm.','Lò rèn lượng tử biến tài nguyên thành công cụ. Công cụ mòn cần sửa chữa. Thị trường kết nối công việc của bạn với những người vận hành khác.','Tải mạng thay đổi điều kiện. Các kỷ nguyên tạo nên nhịp dài hạn. Huấn luyện lại biến điểm kết thúc của con đường này thành khởi đầu của con đường khác.'] },
    energy: { lead: '20 năng lượng là ngân sách hành động, không phải lý do để vội vàng.', paragraphs: ['Năng lượng nằm trong khoảng 0–20. Hãy so số dư hiện tại với chi phí trước khi hành động.','Mỗi 30 phút hồi phục 1 năng lượng. Nuôi cấy và thu hoạch tốn 1 mỗi lần; tách mẫu và huấn luyện tốn 2 mỗi lần.'], steps: { heading: 'Năng lượng · từng bước', items: [{ title: 'Kiểm tra số dư', text: 'Xem mức năng lượng hiện tại trong trò chơi.' },{ title: 'So sánh chi phí', text: 'Kiểm tra khả năng sử dụng, chi phí và kết quả dự kiến.' },{ title: 'Chờ hồi phục nếu cần', text: 'Hướng dẫn này không gửi giao dịch.' }] } },
  },
  id: {
    start: { lead: 'Dari menghubungkan dompet hingga hasil pertamamu.', paragraphs: ['Periksa energi, daya tahan peralatan, dan biaya setiap tindakan. Setelah itu, hubungkan dompet Solana.','Jangan pernah memasukkan frasa pemulihan dompet di situs ini. Dompetmulah yang menangani tanda tangan. Periksa jaringan, alamat program, dan izin sebelum menyetujui.','Mulai dari rangkaian pendek: stasiun jaringan → kultivasi → panen. Periksa resep sebelum merakit serta harga dan biaya sebelum menjual.'], steps: { heading: 'Gas · langkah demi langkah', items: [{ title: 'Periksa saldo', text: 'Gunakan saldo terbaru di permainan, bukan angka dalam panduan ini.' },{ title: 'Isi ulang dengan cermat', text: 'Periksa jumlah tersedia, biaya, dan hasil yang diharapkan sebelum menandatangani.' },{ title: 'Tinjau izin', text: 'Panduan ini tidak mengirim transaksi.' }] } },
    world: { lead: 'Empat modul dalam satu sistem yang saling terhubung.', paragraphs: ['Laboratorium mengembangkan sampel. Modul pemisahan dan meja pelatihan meneruskan prosesnya. Penambangan dan ekspedisi menghasilkan bahan langka.','Penempaan kuantum mengubah sumber daya menjadi peralatan. Peralatan yang aus perlu diperbaiki. Pasar menghubungkan pekerjaanmu dengan operator lain.','Beban jaringan mengubah kondisi. Era menentukan ritme jangka panjang. Pelatihan ulang mengubah akhir sebuah perjalanan menjadi awal perjalanan lain.'] },
    energy: { lead: '20 energi adalah anggaran tindakan, bukan alasan untuk terburu-buru.', paragraphs: ['Energi berkisar antara 0–20. Bandingkan saldo saat ini dengan biaya sebelum bertindak.','Setiap 30 menit, 1 energi pulih. Kultivasi dan panen masing-masing membutuhkan 1; pemisahan dan pelatihan masing-masing membutuhkan 2.'], steps: { heading: 'Energi · langkah demi langkah', items: [{ title: 'Periksa saldo', text: 'Gunakan nilai energi terbaru yang ditampilkan permainan.' },{ title: 'Bandingkan biaya', text: 'Periksa ketersediaan, biaya, dan hasil yang diharapkan.' },{ title: 'Tunggu pemulihan jika perlu', text: 'Panduan ini tidak mengirim transaksi.' }] } },
  },
  fil: {
    start: { lead: 'Mula pagkonekta ng wallet hanggang unang resulta.', paragraphs: ['Suriin ang enerhiya, tibay ng kagamitan, at halaga ng bawat hakbang. Pagkatapos, ikonekta ang Solana wallet.','Huwag kailanman ilagay ang seed phrase sa site na ito. Wallet ang humahawak sa paglagda. Suriin ang network, address ng programa, at mga pahintulot bago ka sumang-ayon.','Magsimula sa maikling daloy: istasyon ng network → pagpapalaki → pag-ani. Suriin ang resipe bago gumawa; tingnan ang presyo at bayarin bago magbenta.'], steps: { heading: 'Gas · hakbang-hakbang', items: [{ title: 'Tingnan ang balanse', text: 'Gamitin ang kasalukuyang balanse sa laro, hindi ang bilang sa gabay na ito.' },{ title: 'Magdagdag nang may pag-iingat', text: 'Suriin ang halaga, bayarin, at inaasahang resulta bago lumagda.' },{ title: 'Suriin ang mga pahintulot', text: 'Hindi nagpapadala ng transaksyon ang gabay na ito.' }] } },
    world: { lead: 'Apat na modyul sa iisang magkakaugnay na sistema.', paragraphs: ['Nagpapalago ng mga sample ang laboratoryo. Itinutuloy ng modyul ng paghihiwalay at training bench ang proseso. Nagbibigay ng bihirang materyales ang pagmimina at ekspedisyon.','Ginagawang kagamitan ng quantum forge ang mga yaman. Kailangang ayusin ang napudpod na kagamitan. Pinag-uugnay ng pamilihan ang iyong trabaho sa ibang operator.','Binabago ng pasanin ng network ang mga kondisyon. Nagtatakda ng mahabang ritmo ang mga panahon. Ginagawang bagong simula ng muling pagsasanay ang pagtatapos ng isang landas.'] },
    energy: { lead: 'Ang 20 enerhiya ay puhunan sa mga gawain, hindi dahilan para magmadali.', paragraphs: ['Mula 0 hanggang 20 ang enerhiya. Ihambing ang kasalukuyang balanse sa halaga bago kumilos.','Bumabalik ang 1 enerhiya bawat 30 minuto. Tig-1 ang pagpapalaki at pag-ani; tig-2 ang paghihiwalay at pagsasanay.'], steps: { heading: 'Enerhiya · hakbang-hakbang', items: [{ title: 'Tingnan ang balanse', text: 'Gamitin ang kasalukuyang enerhiyang ipinapakita sa laro.' },{ title: 'Ihambing ang halaga', text: 'Suriin ang pagiging available, halaga, at inaasahang resulta.' },{ title: 'Maghintay ng pagbalik kung kailangan', text: 'Hindi nagpapadala ng transaksyon ang gabay na ito.' }] } },
  },
};

export const furtherLabels: Record<Language, string> = {
  ru: 'Читай дальше', en: 'Continue reading', pt: 'Continue lendo', es: 'Sigue leyendo', vi: 'Đọc tiếp', id: 'Baca selanjutnya', fil: 'Magbasa pa',
};
