import type { Language } from './translations';

type ToolId = 'plasma_cutter' | 'silicon_extractor' | 'data_harvester' | 'quantum_transmitter' | 'neural_seeder';
type HomeCopy = {
  title: string; workshop: string; packs: string; craft: string; repair: string; collection: string;
  sticker: string; console: string; noData: string; emptyRack: string; consoleTitle: string; consoleSubtitle: string;
  working: string; onRack: string; channelsOn: string; totalTools: string; noShift: string;
  connectHint: string; networkHint: string; loadingHint: string; emptyHint: string;
  inventory: string; inventoryConnect: string; inventoryLoading: string; inventoryUnavailable: string;
  inventoryEmpty: string; tool: string;
};
type CardCopy = {
  disabledMining: string; connectWallet: string; staking: string; unstaking: string; starting: string; opening: string; done: string; failed: string;
  healthy: string; normal: string; worn: string; broken: string; unknown: string; unknownRarity: string; durability: string;
  stake: string; stakeHint: string; miningHours: string; rarityHourCap: string; hourAbbrev: string; decrease: string; increase: string;
  start: string; startDisabled: string; unstake: string; needsFullDurability: string;
  collect: string; collectDisabled: string; extracting: string; timerUnknown: string;
};
type CollectionCopy = {
  intro: string; resources: string; special: string; nfts: string; caption: string;
  rarities: readonly [string, string, string, string, string];
};
type ToolsCopy = { names: Record<ToolId, string>; home: HomeCopy; card: CardCopy; collectionPage: CollectionCopy };

export const toolKeys: Record<string, ToolId> = {
  plasma_cutter: 'plasma_cutter',
  silicon_extractor: 'silicon_extractor',
  data_harvester: 'data_harvester',
  quantum_transmitter: 'quantum_transmitter',
  neural_seeder: 'neural_seeder',
};

export function toolName(language: Language, id?: string | null): string {
  const key = typeof id === 'string' ? toolKeys[id.toLowerCase()] : undefined;
  return key ? toolsCopy[language].names[key] : toolsCopy[language].home.tool;
}

export const toolsCopy: Record<Language, ToolsCopy> = {
  ru: {
    names: { plasma_cutter: 'Плазменный резчик', silicon_extractor: 'Экстрактор кремния', data_harvester: 'Сборщик данных', quantum_transmitter: 'Квантовый передатчик', neural_seeder: 'Нейральный сеятель' },
    home: { title: 'Инструменты', workshop: 'Мастерская', packs: 'Капсулы · выпуск', craft: 'Сборка · улучшение', repair: 'Ремонт', collection: 'Коллекция · 26 ресурсов и 25 NFT', sticker: 'СТОЙКА', console: 'ПУЛЬТ', noData: 'НЕТ ДАННЫХ', emptyRack: 'СТОЙКА ПУСТА', consoleTitle: 'Пульт мастерской', consoleSubtitle: 'прочность и режим каналов', working: 'В работе', onRack: 'В стойке', channelsOn: 'каналы с включённым M', totalTools: 'всего инструментов', noShift: 'нет данных о смене', connectHint: 'Подключи кошелёк — покажем прочность твоих инструментов.', networkHint: 'Стойка не читается: сеть не ответила.', loadingHint: 'Читаем инструменты…', emptyHint: 'Инструментов пока нет: собери первый в кузнице или открой капсулу.', inventory: 'Ваши инструменты', inventoryConnect: 'Подключите кошелёк, чтобы увидеть инвентарь', inventoryLoading: 'Читаем инструменты…', inventoryUnavailable: 'Инструменты недоступны из сети — не удалось прочитать стойку', inventoryEmpty: 'Инструментов пока нет — откройте первую капсулу дропа', tool: 'Инструмент' },
    card: { disabledMining: 'Добыча отключена до проверки правил в сети', connectWallet: 'Подключите кошелёк — кнопка в шапке', staking: 'Инструмент уходит на склад…', unstaking: 'Инструмент возвращается…', starting: 'Экстрактор запущен…', opening: 'Открываем контейнер…', done: 'Готово', failed: 'Операция не выполнена', healthy: 'Отличное состояние', normal: 'Норма', worn: 'Износ', broken: 'Сломан', unknown: 'Прочность неизвестна', unknownRarity: 'Неизвестная редкость', durability: 'Прочность', stake: 'На склад (стейк)', stakeHint: 'Залог 60 секунд. Добыча работает только из серверной стойки', miningHours: 'Часы добычи (прочность −1 за час)', rarityHourCap: 'для этой редкости не больше {hours} ч', hourAbbrev: 'ч', decrease: 'Уменьшить время добычи', increase: 'Увеличить время добычи', start: 'Начать добычу', startDisabled: 'Добыча отключена до проверки в сети', unstake: 'Вернуть в инвентарь', needsFullDurability: 'нужна прочность 20', collect: 'Забрать добычу', collectDisabled: 'Сбор отключён до проверки в сети', extracting: 'Экстрактор в забое…', timerUnknown: 'Срок добычи неизвестен из сети' },
    collectionPage: { intro: '26 видов ресурсов, особое ядро-душа и 25 NFT-инструментов (5 типов × 5 редкостей). Каждая пластина показана целиком.', resources: '26 видов ресурсов', special: 'Особое · 27-й ресурс', nfts: '25 NFT · 5 × 5', caption: 'Все 25 пластин: пять типов и пять редкостей. Изображение показано целиком.', rarities: ['Базовый', 'Усиленный', 'Квантовый', 'Сингулярность', 'Трансцендентный'] },
  },
  en: {
    names: { plasma_cutter: 'Plasma Cutter', silicon_extractor: 'Silicon Extractor', data_harvester: 'Data Harvester', quantum_transmitter: 'Quantum Transmitter', neural_seeder: 'Neural Seeder' },
    home: { title: 'Tools', workshop: 'Workshop', packs: 'Capsules · tool release', craft: 'Craft · upgrade', repair: 'Repair', collection: 'Collection · 26 resources and 25 NFTs', sticker: 'RACK', console: 'CONSOLE', noData: 'NO DATA', emptyRack: 'RACK EMPTY', consoleTitle: 'Workshop console', consoleSubtitle: 'durability and channel status', working: 'Working', onRack: 'On the rack', channelsOn: 'channels with M active', totalTools: 'tools in total', noShift: 'no shift data', connectHint: 'Connect a wallet to see your tools’ durability.', networkHint: 'The rack could not be read from the network.', loadingHint: 'Loading tools…', emptyHint: 'No tools yet: craft one or open a capsule.', inventory: 'Your tools', inventoryConnect: 'Connect a wallet to see your inventory', inventoryLoading: 'Loading tools…', inventoryUnavailable: 'Tools unavailable from the network — could not read the rack', inventoryEmpty: 'No tools yet — open your first drop capsule', tool: 'Tool' },
    card: { disabledMining: 'Mining is disabled until the on-chain rules are verified', connectWallet: 'Connect your wallet using the button in the header', staking: 'Moving tool to the rack…', unstaking: 'Returning tool to inventory…', starting: 'Starting the extractor…', opening: 'Opening the container…', done: 'Done', failed: 'Operation failed', healthy: 'Excellent condition', normal: 'Normal', worn: 'Worn', broken: 'Broken', unknown: 'Durability unknown', unknownRarity: 'Unknown rarity', durability: 'Durability', stake: 'Move to rack (stake)', stakeHint: '60-second lock. Mining only works with tools on the rack', miningHours: 'Mining hours (−1 durability per hour)', rarityHourCap: 'this rarity allows at most {hours} h', hourAbbrev: 'h', decrease: 'Shorten mining time', increase: 'Extend mining time', start: 'Start mining', startDisabled: 'Mining disabled pending verification', unstake: 'Return to inventory', needsFullDurability: 'requires 20 durability', collect: 'Collect output', collectDisabled: 'Collection disabled pending verification', extracting: 'Extractor working…', timerUnknown: 'Mining end time unavailable from the network' },
    collectionPage: { intro: '26 resource types, the special Soul Core and 25 NFT tools (5 types × 5 rarities). Each artwork is shown in full.', resources: '26 resource types', special: 'Special · resource 27', nfts: '25 NFTs · 5 × 5', caption: 'All 25 artworks: five tool types and five rarities, shown without cropping.', rarities: ['Base', 'Enhanced', 'Quantum', 'Singularity', 'Transcendent'] },
  },
  pt: {
    names: { plasma_cutter: 'Cortador de plasma', silicon_extractor: 'Extrator de silício', data_harvester: 'Coletor de dados', quantum_transmitter: 'Transmissor quântico', neural_seeder: 'Semeador neural' },
    home: { title: 'Ferramentas', workshop: 'Oficina', packs: 'Cápsulas · lançamento', craft: 'Criação · melhoria', repair: 'Reparo', collection: 'Coleção · 26 recursos e 25 NFTs', sticker: 'ESTANTE', console: 'CONSOLE', noData: 'SEM DADOS', emptyRack: 'ESTANTE VAZIA', consoleTitle: 'Console da oficina', consoleSubtitle: 'durabilidade e estado dos canais', working: 'Em uso', onRack: 'Na estante', channelsOn: 'canais com M ativo', totalTools: 'ferramentas ao todo', noShift: 'sem dados do turno', connectHint: 'Conecte sua carteira para ver a durabilidade das ferramentas.', networkHint: 'Não foi possível ler a estante na rede.', loadingHint: 'Carregando ferramentas…', emptyHint: 'Ainda não há ferramentas: crie uma ou abra uma cápsula.', inventory: 'Suas ferramentas', inventoryConnect: 'Conecte sua carteira para ver o inventário', inventoryLoading: 'Carregando ferramentas…', inventoryUnavailable: 'Ferramentas indisponíveis na rede — não foi possível consultar a estante', inventoryEmpty: 'Ainda não há ferramentas — abra sua primeira cápsula', tool: 'Ferramenta' },
    card: { disabledMining: 'Extração desativada até a verificação das regras na rede', connectWallet: 'Conecte a carteira pelo botão no topo', staking: 'Levando a ferramenta para a estante…', unstaking: 'Devolvendo a ferramenta ao inventário…', starting: 'Iniciando o extrator…', opening: 'Abrindo o recipiente…', done: 'Concluído', failed: 'A operação falhou', healthy: 'Ótimo estado', normal: 'Normal', worn: 'Desgastada', broken: 'Quebrada', unknown: 'Durabilidade desconhecida', unknownRarity: 'Raridade desconhecida', durability: 'Durabilidade', stake: 'Colocar na estante (staking)', stakeHint: 'Bloqueio de 60 segundos. A extração exige ferramentas na estante', miningHours: 'Horas de extração (−1 de durabilidade por hora)', rarityHourCap: 'esta raridade permite no máximo {hours} h', hourAbbrev: 'h', decrease: 'Reduzir o tempo de extração', increase: 'Aumentar o tempo de extração', start: 'Iniciar extração', startDisabled: 'Extração desativada até a verificação', unstake: 'Devolver ao inventário', needsFullDurability: 'exige durabilidade 20', collect: 'Coletar produção', collectDisabled: 'Coleta desativada até a verificação', extracting: 'Extrator em operação…', timerUnknown: 'Prazo da extração indisponível na rede' },
    collectionPage: { intro: '26 tipos de recursos, o Núcleo da alma especial e 25 ferramentas NFT (5 tipos × 5 raridades). Cada arte aparece por inteiro.', resources: '26 tipos de recursos', special: 'Especial · 27º recurso', nfts: '25 NFTs · 5 × 5', caption: 'As 25 artes: cinco tipos e cinco raridades, sem cortes.', rarities: ['Básico', 'Aprimorado', 'Quântico', 'Singularidade', 'Transcendente'] },
  },
  es: {
    names: { plasma_cutter: 'Cortador de plasma', silicon_extractor: 'Extractor de silicio', data_harvester: 'Recolector de datos', quantum_transmitter: 'Transmisor cuántico', neural_seeder: 'Sembrador neuronal' },
    home: { title: 'Herramientas', workshop: 'Taller', packs: 'Cápsulas · emisión', craft: 'Fabricación · mejora', repair: 'Reparación', collection: 'Colección · 26 recursos y 25 NFT', sticker: 'ESTANTE', console: 'CONSOLA', noData: 'SIN DATOS', emptyRack: 'ESTANTE VACÍO', consoleTitle: 'Consola del taller', consoleSubtitle: 'durabilidad y estado de los canales', working: 'En uso', onRack: 'En el estante', channelsOn: 'canales con M activo', totalTools: 'herramientas en total', noShift: 'sin datos del turno', connectHint: 'Conecta tu cartera para ver la durabilidad de tus herramientas.', networkHint: 'No se pudo consultar el estante en la red.', loadingHint: 'Cargando herramientas…', emptyHint: 'Aún no hay herramientas: fabrica una o abre una cápsula.', inventory: 'Tus herramientas', inventoryConnect: 'Conecta una cartera para ver el inventario', inventoryLoading: 'Cargando herramientas…', inventoryUnavailable: 'Herramientas no disponibles en la red — no se pudo consultar el estante', inventoryEmpty: 'Aún no hay herramientas — abre tu primera cápsula', tool: 'Herramienta' },
    card: { disabledMining: 'Extracción desactivada hasta verificar las reglas de la red', connectWallet: 'Conecta tu cartera con el botón superior', staking: 'Llevando la herramienta al estante…', unstaking: 'Devolviendo la herramienta al inventario…', starting: 'Iniciando el extractor…', opening: 'Abriendo el recipiente…', done: 'Listo', failed: 'La operación falló', healthy: 'Estado excelente', normal: 'Normal', worn: 'Desgastada', broken: 'Rota', unknown: 'Durabilidad desconocida', unknownRarity: 'Rareza desconocida', durability: 'Durabilidad', stake: 'Colocar en estante (staking)', stakeHint: 'Bloqueo de 60 segundos. La extracción solo funciona con herramientas en el estante', miningHours: 'Horas de extracción (−1 de durabilidad por hora)', rarityHourCap: 'esta rareza permite como máximo {hours} h', hourAbbrev: 'h', decrease: 'Reducir tiempo de extracción', increase: 'Aumentar tiempo de extracción', start: 'Iniciar extracción', startDisabled: 'Extracción desactivada hasta la verificación', unstake: 'Devolver al inventario', needsFullDurability: 'requiere durabilidad 20', collect: 'Recoger producción', collectDisabled: 'Recolección desactivada hasta la verificación', extracting: 'Extractor trabajando…', timerUnknown: 'No se pudo consultar cuándo termina la extracción' },
    collectionPage: { intro: '26 tipos de recursos, el Núcleo del alma especial y 25 herramientas NFT (5 tipos × 5 rarezas). Cada ilustración se muestra completa.', resources: '26 tipos de recursos', special: 'Especial · recurso 27', nfts: '25 NFT · 5 × 5', caption: 'Las 25 ilustraciones: cinco tipos y cinco rarezas, sin recortes.', rarities: ['Básico', 'Mejorado', 'Cuántico', 'Singularidad', 'Trascendente'] },
  },
  vi: {
    names: { plasma_cutter: 'Máy cắt plasma', silicon_extractor: 'Máy chiết silic', data_harvester: 'Máy thu thập dữ liệu', quantum_transmitter: 'Máy phát lượng tử', neural_seeder: 'Máy gieo mầm thần kinh' },
    home: { title: 'Công cụ', workshop: 'Xưởng chế tạo', packs: 'Hộp vật phẩm · mở', craft: 'Chế tạo · nâng cấp', repair: 'Sửa chữa', collection: 'Bộ sưu tập · 26 tài nguyên và 25 NFT', sticker: 'GIÁ CÔNG CỤ', console: 'BẢNG ĐIỀU KHIỂN', noData: 'CHƯA CÓ DỮ LIỆU', emptyRack: 'GIÁ TRỐNG', consoleTitle: 'Bảng điều khiển xưởng', consoleSubtitle: 'độ bền và trạng thái các kênh', working: 'Đang dùng', onRack: 'Trên giá', channelsOn: 'kênh đã bật M', totalTools: 'tổng số công cụ', noShift: 'chưa có dữ liệu ca', connectHint: 'Kết nối ví để xem độ bền công cụ.', networkHint: 'Không thể đọc giá công cụ từ mạng.', loadingHint: 'Đang tải công cụ…', emptyHint: 'Chưa có công cụ: hãy chế tạo hoặc mở một hộp vật phẩm.', inventory: 'Công cụ của bạn', inventoryConnect: 'Kết nối ví để xem kho đồ', inventoryLoading: 'Đang tải công cụ…', inventoryUnavailable: 'Không thể tải công cụ từ mạng — không đọc được giá', inventoryEmpty: 'Chưa có công cụ — hãy mở hộp vật phẩm đầu tiên', tool: 'Công cụ' },
    card: { disabledMining: 'Chưa bật khai thác cho đến khi xác minh quy tắc trên chuỗi', connectWallet: 'Kết nối ví bằng nút trên đầu trang', staking: 'Đang chuyển công cụ lên giá…', unstaking: 'Đang trả công cụ về kho…', starting: 'Đang khởi động máy chiết…', opening: 'Đang mở kho chứa…', done: 'Hoàn tất', failed: 'Thao tác thất bại', healthy: 'Tình trạng tốt', normal: 'Bình thường', worn: 'Đã mòn', broken: 'Hỏng', unknown: 'Chưa rõ độ bền', unknownRarity: 'Chưa rõ độ hiếm', durability: 'Độ bền', stake: 'Đặt lên giá (staking)', stakeHint: 'Khóa 60 giây. Chỉ công cụ trên giá mới có thể khai thác', miningHours: 'Giờ khai thác (mất 1 độ bền mỗi giờ)', rarityHourCap: 'độ hiếm này tối đa {hours} giờ', hourAbbrev: 'giờ', decrease: 'Giảm thời gian khai thác', increase: 'Tăng thời gian khai thác', start: 'Bắt đầu khai thác', startDisabled: 'Chưa bật khai thác trước khi xác minh', unstake: 'Trả về kho', needsFullDurability: 'cần đủ 20 độ bền', collect: 'Thu sản lượng', collectDisabled: 'Chưa bật thu sản lượng', extracting: 'Máy chiết đang hoạt động…', timerUnknown: 'Chưa có thời gian kết thúc khai thác từ mạng' },
    collectionPage: { intro: '26 loại tài nguyên, Lõi linh hồn đặc biệt và 25 công cụ NFT (5 loại × 5 độ hiếm). Hình ảnh được hiển thị đầy đủ.', resources: '26 loại tài nguyên', special: 'Đặc biệt · tài nguyên thứ 27', nfts: '25 NFT · 5 × 5', caption: 'Đủ 25 hình: năm loại công cụ và năm độ hiếm, không cắt ảnh.', rarities: ['Cơ bản', 'Nâng cao', 'Lượng tử', 'Điểm kỳ dị', 'Siêu việt'] },
  },
  id: {
    names: { plasma_cutter: 'Pemotong plasma', silicon_extractor: 'Ekstraktor silikon', data_harvester: 'Pengumpul data', quantum_transmitter: 'Pemancar kuantum', neural_seeder: 'Penyemai saraf' },
    home: { title: 'Peralatan', workshop: 'Bengkel', packs: 'Kapsul · rilis alat', craft: 'Perakitan · peningkatan', repair: 'Perbaikan', collection: 'Koleksi · 26 sumber daya dan 25 NFT', sticker: 'RAK', console: 'KONSOL', noData: 'TANPA DATA', emptyRack: 'RAK KOSONG', consoleTitle: 'Konsol bengkel', consoleSubtitle: 'daya tahan dan status saluran', working: 'Digunakan', onRack: 'Di rak', channelsOn: 'saluran dengan M aktif', totalTools: 'jumlah peralatan', noShift: 'belum ada data giliran', connectHint: 'Hubungkan dompet untuk melihat daya tahan peralatanmu.', networkHint: 'Rak tidak dapat dibaca dari jaringan.', loadingHint: 'Memuat peralatan…', emptyHint: 'Belum ada peralatan: rakit alat atau buka kapsul.', inventory: 'Peralatanmu', inventoryConnect: 'Hubungkan dompet untuk melihat inventaris', inventoryLoading: 'Memuat peralatan…', inventoryUnavailable: 'Peralatan tidak tersedia dari jaringan — gagal membaca rak', inventoryEmpty: 'Belum ada peralatan — buka kapsul pertamamu', tool: 'Peralatan' },
    card: { disabledMining: 'Penambangan dinonaktifkan sampai aturan blockchain diverifikasi', connectWallet: 'Hubungkan dompet dengan tombol di bagian atas', staking: 'Memindahkan peralatan ke rak…', unstaking: 'Mengembalikan peralatan ke inventaris…', starting: 'Menjalankan ekstraktor…', opening: 'Membuka wadah…', done: 'Selesai', failed: 'Tindakan gagal', healthy: 'Kondisi sangat baik', normal: 'Normal', worn: 'Aus', broken: 'Rusak', unknown: 'Daya tahan belum diketahui', unknownRarity: 'Kelangkaan belum diketahui', durability: 'Daya tahan', stake: 'Letakkan di rak (staking)', stakeHint: 'Kunci 60 detik. Penambangan hanya berlaku untuk peralatan di rak', miningHours: 'Jam penambangan (−1 daya tahan per jam)', rarityHourCap: 'kelangkaan ini paling lama {hours} jam', hourAbbrev: 'jam', decrease: 'Kurangi waktu penambangan', increase: 'Tambah waktu penambangan', start: 'Mulai menambang', startDisabled: 'Penambangan nonaktif sampai verifikasi', unstake: 'Kembalikan ke inventaris', needsFullDurability: 'perlu daya tahan 20', collect: 'Ambil hasil', collectDisabled: 'Pengambilan nonaktif sampai verifikasi', extracting: 'Ekstraktor sedang bekerja…', timerUnknown: 'Waktu selesai penambangan belum tersedia dari jaringan' },
    collectionPage: { intro: '26 jenis sumber daya, Inti Jiwa khusus, dan 25 peralatan NFT (5 jenis × 5 kelangkaan). Semua gambar ditampilkan utuh.', resources: '26 jenis sumber daya', special: 'Khusus · sumber daya ke-27', nfts: '25 NFT · 5 × 5', caption: 'Seluruh 25 gambar: lima jenis dan lima tingkat kelangkaan, tanpa potongan.', rarities: ['Dasar', 'Ditingkatkan', 'Kuantum', 'Singularitas', 'Transenden'] },
  },
  fil: {
    names: { plasma_cutter: 'Pamutol na plasma', silicon_extractor: 'Pangkuha ng silikon', data_harvester: 'Pang-ani ng datos', quantum_transmitter: 'Tagapaghatid ng kuwantum', neural_seeder: 'Panghasik ng neural na binhi' },
    home: { title: 'Mga kagamitan', workshop: 'Pagawaan', packs: 'Mga kapsula · pagkuha', craft: 'Paggawa · pagpapahusay', repair: 'Pagkukumpuni', collection: 'Koleksiyon · 26 yaman at 25 NFT', sticker: 'ISTANTE', console: 'KONSOL', noData: 'WALANG DATOS', emptyRack: 'WALANG LAMAN ANG ISTANTE', consoleTitle: 'Konsol ng pagawaan', consoleSubtitle: 'tibay at kalagayan ng mga channel', working: 'Ginagamit', onRack: 'Sa istante', channelsOn: 'mga channel na naka-on ang M', totalTools: 'kabuuang kagamitan', noShift: 'walang datos ng turno', connectHint: 'Ikonekta ang wallet upang makita ang tibay ng kagamitan.', networkHint: 'Hindi mabasa ang istante mula sa network.', loadingHint: 'Kinukuha ang mga kagamitan…', emptyHint: 'Wala pang kagamitan: gumawa o magbukas ng kapsula.', inventory: 'Iyong mga kagamitan', inventoryConnect: 'Ikonekta ang wallet upang makita ang imbentaryo', inventoryLoading: 'Kinukuha ang mga kagamitan…', inventoryUnavailable: 'Hindi makuha ang kagamitan mula sa network — hindi mabasa ang istante', inventoryEmpty: 'Wala pang kagamitan — buksan ang unang kapsula', tool: 'Kagamitan' },
    card: { disabledMining: 'Nakasara ang pagmimina hanggang masuri ang mga patakaran sa blockchain', connectWallet: 'Ikonekta ang wallet gamit ang pindutan sa itaas', staking: 'Inilalagay ang kagamitan sa istante…', unstaking: 'Ibinabalik ang kagamitan sa imbentaryo…', starting: 'Sinisimulan ang pangkuha…', opening: 'Binubuksan ang lalagyan…', done: 'Tapos na', failed: 'Nabigo ang gawain', healthy: 'Napakagandang kalagayan', normal: 'Karaniwan', worn: 'Luma na', broken: 'Sira', unknown: 'Hindi alam ang tibay', unknownRarity: 'Hindi alam ang antas ng pambihira', durability: 'Tibay', stake: 'Ilagay sa istante (staking)', stakeHint: 'Kandado na 60 segundo. Kagamitan sa istante lang ang puwedeng magmina', miningHours: 'Oras ng pagmimina (−1 tibay kada oras)', rarityHourCap: 'hanggang {hours} oras para sa antas na ito', hourAbbrev: 'oras', decrease: 'Bawasan ang oras ng pagmimina', increase: 'Dagdagan ang oras ng pagmimina', start: 'Magsimulang magmina', startDisabled: 'Nakasara ang pagmimina habang sinusuri', unstake: 'Ibalik sa imbentaryo', needsFullDurability: 'kailangan ang tibay na 20', collect: 'Kunin ang ani', collectDisabled: 'Nakasara ang pagkuha habang sinusuri', extracting: 'Gumagana ang pangkuha…', timerUnknown: 'Hindi makuha sa network ang oras ng pagtatapos' },
    collectionPage: { intro: '26 uri ng yaman, ang natatanging Core ng Kaluluwa, at 25 NFT na kagamitan (5 uri × 5 antas ng pambihira). Buo ang bawat larawan.', resources: '26 uri ng yaman', special: 'Natatangi · ika-27 yaman', nfts: '25 NFT · 5 × 5', caption: 'Lahat ng 25 larawan: limang uri at limang antas ng pambihira, walang putol.', rarities: ['Batayan', 'Pinahusay', 'Kuwantum', 'Singularidad', 'Transendente'] },
  },
};
