import { legalUnavailableCopy } from './legalUnavailableCopy';
// Editorial translations for the shared navigation and landing introduction.
// Long-form reference material is NOT translated here. Do not remove the
// Russian-language notice until those pages have reviewed translations.
export const languages = ['en', 'pt', 'es', 'vi', 'id', 'fil', 'ru'] as const;
export type Language = typeof languages[number];
export type LanguageChoice = Language | 'auto';

export const languageOptions: { code: Language; native: string; english: string }[] = [
  { code: 'en', native: 'English', english: 'English' },
  { code: 'pt', native: 'Português', english: 'Portuguese' },
  { code: 'es', native: 'Español', english: 'Spanish' },
  { code: 'vi', native: 'Tiếng Việt', english: 'Vietnamese' },
  { code: 'id', native: 'Bahasa Indonesia', english: 'Indonesian' },
  { code: 'fil', native: 'Filipino', english: 'Filipino' },
  { code: 'ru', native: 'Русский', english: 'Russian' },
];

const ids = ['home','manifesto','start','world','energy','weather','farm','craft','tools','mine','packs','lottery','economy','market','seasons','trust','resources','guide','strategies','quests','recipes','trade','investors','potato','lore','glossary','docs','faq','roadmap','rules'] as const;
export type PageId = typeof ids[number];
const toPages = (titles: readonly string[]): Record<PageId, string> => {
  if (titles.length !== ids.length) throw new Error('Incomplete navigation translation');
  return Object.fromEntries(ids.map((id, i) => [id, titles[i]])) as Record<PageId, string>;
};

export const pageNames: Record<Language, Record<PageId, string>> = {
  ru: toPages(['Лаборатория','Манифест','Первая смена','Лаборатория и сеть','Энергия','Нагрузка сети','От образца до модели','Квантовая кузница','Инструменты','Добыча','Капсулы дропа','Квантовый розыгрыш','Экономика','Рынок','Эпохальный путь','Доверие','Каталог ресурсов','Первые смены','Пути мастера','Журнал знакомства','Книга рецептов','Способы торговли','Экономика для инвестора','Токен MIND','История мастерской','Словарь','Индекс инструкций','Частые вопросы','Карта развития','Правила']),
  en: toPages(['The Laboratory','Manifesto','First shift','Laboratory & network','Energy','Network load','From sample to model','Quantum forge','Tools','Mining','Drop capsules','Quantum draw','Economy','Market','Seasons','Trust','Resources','First shifts','Strategies','Journal','Recipes','Trading','Investor guide','MIND token','Story','Glossary','Documentation','FAQ','Roadmap','Rules']),
  pt: toPages(['Laboratório','Manifesto','Primeiro turno','Laboratório e rede','Energia','Carga da rede','Da amostra ao modelo','Forja quântica','Ferramentas','Extração','Cápsulas de itens','Sorteio quântico','Economia','Mercado','Épocas','Confiança','Recursos','Primeiros turnos','Estratégias','Diário','Receitas','Formas de negociação','Guia para investidores','Token MIND','História','Glossário','Documentação','Perguntas frequentes','Roteiro','Regras']),
  es: toPages(['Laboratorio','Manifiesto','Primer turno','Laboratorio y red','Energía','Carga de la red','De la muestra al modelo','Forja cuántica','Herramientas','Extracción','Cápsulas de botín','Sorteo cuántico','Economía','Mercado','Épocas','Confianza','Recursos','Primeros turnos','Estrategias','Diario','Recetas','Formas de comerciar','Guía para inversores','Token MIND','Historia','Glosario','Documentación','Preguntas frecuentes','Hoja de ruta','Reglas']),
  vi: toPages(['Phòng thí nghiệm','Tuyên ngôn','Ca đầu tiên','Phòng thí nghiệm và mạng','Năng lượng','Tải mạng','Từ mẫu đến mô hình','Lò rèn lượng tử','Công cụ','Khai thác','Viên nang vật phẩm','Vòng quay lượng tử','Kinh tế','Thị trường','Các kỷ nguyên','Niềm tin','Tài nguyên','Những ca đầu','Chiến lược','Nhật ký','Công thức','Cách giao dịch','Dành cho nhà đầu tư','Token MIND','Câu chuyện','Thuật ngữ','Tài liệu','Câu hỏi thường gặp','Lộ trình','Quy tắc']),
  id: toPages(['Laboratorium','Manifesto','Giliran pertama','Laboratorium dan jaringan','Energi','Beban jaringan','Dari sampel ke model','Penempaan kuantum','Peralatan','Penambangan','Kapsul hadiah','Undian kuantum','Ekonomi','Pasar','Era','Kepercayaan','Sumber daya','Giliran awal','Strategi','Jurnal','Resep','Cara berdagang','Panduan investor','Token MIND','Kisah','Glosarium','Dokumentasi','Tanya jawab','Peta jalan','Aturan']),
  fil: toPages(['Laboratoryo','Manipesto','Unang turno','Laboratoryo at network','Enerhiya','Pasanin ng network','Mula sample hanggang modelo','Pandayang kuwantum','Mga kagamitan','Pagmimina','Mga kapsula ng gantimpala','Bunutan ng kuwantum','Ekonomiya','Pamilihan','Mga panahon','Tiwala','Mga yaman','Mga unang turno','Mga estratehiya','Talaan','Mga resipe','Mga paraan ng kalakalan','Gabay sa mamumuhunan','MIND token','Kuwento','Talasalitaan','Dokumentasyon','Mga madalas itanong','Plano ng pag-unlad','Mga patakaran']),
};

export type UIKey = 'playGroup'|'craftGroup'|'chanceGroup'|'economyGroup'|'progressGroup'|'learnGroup'|'skip'|'nav'|'menu'|'language'|'auto'|'launch'|'playShort'|'siteMenu'|'homeTitle'|'homeLead'|'homeIntro'|'homeNumbers'|'heroGuide'|'galleryTitle'|'laboratory'|'workshop'|'market'|'gameTitle'|'gameDescription'|'resourceLink'|'energy'|'durability'|'rarities'|'trust'|'fourNumbers'|'footerTitle'|'footerLead'|'rules'|'translationNotice'|'resourcesLabel';
const ui = (values: readonly string[]): Record<UIKey, string> => {
  const keys: UIKey[] = ['playGroup','craftGroup','chanceGroup','economyGroup','progressGroup','learnGroup','skip','nav','menu','language','auto','launch','playShort','siteMenu','homeTitle','homeLead','homeIntro','homeNumbers','heroGuide','galleryTitle','laboratory','workshop','market','gameTitle','gameDescription','resourceLink','energy','durability','rarities','trust','fourNumbers','footerTitle','footerLead','rules','translationNotice','resourcesLabel'];
  if (values.length !== keys.length) throw new Error('Incomplete interface translation');
  return Object.fromEntries(keys.map((key, i) => [key, values[i]])) as Record<UIKey, string>;
};
export const messages: Record<Language, Record<UIKey, string>> = {
  ru: ui(['Играть','Ремесло','Случайность','Экономика','Путь','Знания','Перейти к содержимому','Основная навигация','Меню','Язык','Автоматически','Запустить игру','Игра','Сайт и меню','Лаборатория','Культивируй образцы. Обучай модели. Держи лабораторию в порядке.','NeuroForge — лаборатория-RPG на Solana. Выращивай образцы, обучай модели, создавай инструменты и торгуй.','20 единиц энергии. 20 прочности. 5 редкостей. Решение за тобой.','Как начать','Мир лаборатории','Лаборатория','Мастерская','Рынок','Наш продукт','Создай свою лабораторию на Solana: выращивай образцы, обучай модели, собирай NFT-инструменты и торгуй.','Каталог ресурсов','максимум энергии','максимум прочности','редкости инструмента','тиров доверия','Четыре числа, с которых стоит начать','Создавай модели. Торгуй интеллектом.','NeuroForge — лаборатория-RPG на Solana: образцы, модели, инструменты и рынок.','Правила',legalUnavailableCopy.ru.notice,'Ресурсы']),
  en: ui(['Play','Craft','Chance','Economy','Progress','Learn','Skip to content','Main navigation','Menu','Language','Automatic','Launch game','Play','Site & menu','The Laboratory','Grow samples. Train models. Keep your laboratory running.','NeuroForge is a laboratory RPG on Solana. Grow samples, train models, craft tools and trade.','20 energy. 20 durability. 5 rarities. The decisions are yours.','First shift guide','Explore the world','Laboratory','Workshop','Marketplace','The game','Build your laboratory on Solana: grow samples, train models, craft NFT tools and trade.','Resources','energy capacity','max durability','tool rarities','trust tiers','Four numbers to know','Train models. Trade intelligence.','NeuroForge is a laboratory RPG on Solana: samples, models, tools and a marketplace.','Rules',legalUnavailableCopy.en.notice,'Resources']),
  pt: ui(['Jogar','Criar','Sorte','Economia','Progresso','Conhecer','Ir para o conteúdo','Navegação principal','Menu','Idioma','Automático','Iniciar o jogo','Jogar','Site e menu','O Laboratório','Cultive amostras. Treine modelos. Cuide do seu laboratório.','NeuroForge é um RPG de laboratório na Solana. Cultive amostras, treine modelos, crie ferramentas e negocie.','20 de energia. 20 de durabilidade. 5 raridades. As decisões são suas.','Guia do primeiro turno','Explore este universo','Laboratório','Oficina','Mercado','O jogo','Construa seu laboratório na Solana: cultive amostras, treine modelos, crie ferramentas NFT e negocie.','Recursos','energia máxima','durabilidade máxima','raridades das ferramentas','níveis de confiança','Quatro números para começar','Treine modelos. Negocie inteligência.','NeuroForge é um RPG de laboratório na Solana: amostras, modelos, ferramentas e mercado.','Regras',legalUnavailableCopy.pt.notice,'Recursos']),
  es: ui(['Jugar','Crear','Azar','Economía','Progreso','Aprender','Ir al contenido','Navegación principal','Menú','Idioma','Automático','Iniciar el juego','Jugar','Sitio y menú','El laboratorio','Cultiva muestras. Entrena modelos. Mantén tu laboratorio en marcha.','NeuroForge es un RPG de laboratorio en Solana. Cultiva muestras, entrena modelos, fabrica herramientas y comercia.','20 de energía. 20 de durabilidad. 5 rarezas. Tú decides.','Guía del primer turno','Explora este mundo','Laboratorio','Taller','Mercado','El juego','Construye tu laboratorio en Solana: cultiva muestras, entrena modelos, fabrica herramientas NFT y comercia.','Recursos','energía máxima','durabilidad máxima','rarezas de herramientas','niveles de confianza','Cuatro cifras para empezar','Entrena modelos. Comercia con inteligencia.','NeuroForge es un RPG de laboratorio en Solana: muestras, modelos, herramientas y mercado.','Reglas',legalUnavailableCopy.es.notice,'Recursos']),
  vi: ui(['Chơi','Chế tạo','May rủi','Kinh tế','Tiến trình','Tìm hiểu','Đến nội dung','Điều hướng chính','Menu','Ngôn ngữ','Tự động','Vào trò chơi','Chơi','Trang web và menu','Phòng thí nghiệm','Nuôi cấy mẫu. Huấn luyện mô hình. Vận hành phòng thí nghiệm của bạn.','NeuroForge là game nhập vai phòng thí nghiệm trên Solana. Nuôi cấy mẫu, huấn luyện mô hình, chế tạo công cụ và giao dịch.','20 năng lượng. 20 độ bền. 5 cấp độ hiếm. Quyết định nằm trong tay bạn.','Hướng dẫn ca đầu','Khám phá thế giới','Phòng thí nghiệm','Xưởng chế tạo','Thị trường','Trò chơi','Xây dựng phòng thí nghiệm trên Solana: nuôi cấy mẫu, huấn luyện mô hình, chế tạo công cụ NFT và giao dịch.','Tài nguyên','năng lượng tối đa','độ bền tối đa','cấp độ hiếm công cụ','cấp độ tin cậy','Bốn con số cần biết','Huấn luyện mô hình. Giao dịch trí tuệ.','NeuroForge là game nhập vai phòng thí nghiệm trên Solana: mẫu, mô hình, công cụ và thị trường.','Quy tắc',legalUnavailableCopy.vi.notice,'Tài nguyên']),
  id: ui(['Main','Merakit','Peluang','Ekonomi','Progres','Pelajari','Lewati ke konten','Navigasi utama','Menu','Bahasa','Otomatis','Mulai bermain','Main','Situs dan menu','Laboratorium','Kembangkan sampel. Latih model. Kelola laboratoriummu.','NeuroForge adalah RPG laboratorium di Solana. Kembangkan sampel, latih model, rakit peralatan, dan berdagang.','20 energi. 20 daya tahan. 5 tingkat kelangkaan. Keputusan ada di tanganmu.','Panduan giliran pertama','Jelajahi dunia','Laboratorium','Bengkel','Pasar','Permainan','Bangun laboratoriummu di Solana: kembangkan sampel, latih model, rakit peralatan NFT, dan berdagang.','Sumber daya','energi maksimum','daya tahan maksimum','kelangkaan peralatan','tingkat kepercayaan','Empat angka penting','Latih model. Perdagangkan kecerdasan.','NeuroForge adalah RPG laboratorium di Solana: sampel, model, peralatan, dan pasar.','Aturan',legalUnavailableCopy.id.notice,'Sumber daya']),
  fil: ui(['Maglaro','Lumikha','Tsansa','Ekonomiya','Pag-unlad','Matuto','Tumalon sa nilalaman','Pangunahing nabigasyon','Menu','Wika','Awtomatiko','Simulan ang laro','Maglaro','Site at menu','Ang Laboratoryo','Magpalago ng mga sample. Sanayin ang mga modelo. Patakbuhin ang iyong laboratoryo.','Ang NeuroForge ay laboratoryong RPG sa Solana. Magpalago ng mga sample, sanayin ang mga modelo, gumawa ng kagamitan, at makipagkalakalan.','20 enerhiya. 20 tibay. 5 antas ng pambihira. Ikaw ang magpapasya.','Gabay sa unang turno','Tuklasin ang mundo','Laboratoryo','Pagawaan','Pamilihan','Ang laro','Bumuo ng laboratoryo sa Solana: magpalago ng mga sample, sanayin ang mga modelo, gumawa ng mga NFT na kagamitan, at makipagkalakalan.','Mga yaman','pinakamataas na enerhiya','pinakamataas na tibay','antas ng kagamitan','antas ng tiwala','Apat na bilang na dapat malaman','Sanayin ang mga modelo. Ikalakal ang talino.','Ang NeuroForge ay laboratoryong RPG sa Solana: mga sample, modelo, kagamitan, at pamilihan.','Mga patakaran',legalUnavailableCopy.fil.notice,'Mga yaman']),
};

export const groupKeys: Record<string, UIKey> = { 'Играть':'playGroup','Ремесло':'craftGroup','Случайность':'chanceGroup','Экономика':'economyGroup','Путь':'progressGroup','Знания':'learnGroup' };

export function detectLanguage(preferences: readonly string[]): Language {
  for (const raw of preferences) {
    const code = raw.toLowerCase().split('-')[0];
    if (code === 'tl' || code === 'fil') return 'fil';
    if ((languages as readonly string[]).includes(code)) return code as Language;
  }
  return 'ru';
}
