import type { Language } from './translations';

export type WeatherCopy = { unavailable: string; noNetwork: string; networkLoad: string; dayAbbrev: string; day: string; of: string; untilChange: string; epoch: string; forecast: string; stationIdle: string; stationRate: string; perHour: string; seasons: { spring: string; summer: string; autumn: string; winter: string } };
export const weatherCopy: Record<Language, WeatherCopy> = {
  ru: { unavailable: 'Погода недоступна из сети', noNetwork: 'нет данных сети', networkLoad: 'Нагрузка сети', dayAbbrev: 'д.', day: 'День', of: 'из', untilChange: 'до смены', epoch: 'Эпоха', forecast: 'Прогноз на 3 дня · расписание дня из цепи:', stationIdle: 'Станция не качает: 0/час', stationRate: 'Станция качает', perHour: '/час', seasons: { spring: 'Весна', summer: 'Лето', autumn: 'Осень', winter: 'Зима' } },
  en: { unavailable: 'Weather data unavailable from the network', noNetwork: 'no network data', networkLoad: 'Network load', dayAbbrev: 'd.', day: 'Day', of: 'of', untilChange: 'until change', epoch: 'Epoch', forecast: 'Next 3 days · on-chain schedule:', stationIdle: 'Station offline: 0/hour', stationRate: 'Station output', perHour: '/hour', seasons: { spring: 'Spring', summer: 'Summer', autumn: 'Autumn', winter: 'Winter' } },
  pt: { unavailable: 'Dados da rede indisponíveis', noNetwork: 'sem dados da rede', networkLoad: 'Carga da rede', dayAbbrev: 'd.', day: 'Dia', of: 'de', untilChange: 'até a troca', epoch: 'Época', forecast: 'Próximos 3 dias · calendário da rede:', stationIdle: 'Estação parada: 0/hora', stationRate: 'Produção da estação', perHour: '/hora', seasons: { spring: 'Primavera', summer: 'Verão', autumn: 'Outono', winter: 'Inverno' } },
  es: { unavailable: 'Datos meteorológicos no disponibles en la red', noNetwork: 'sin datos de la red', networkLoad: 'Carga de la red', dayAbbrev: 'd.', day: 'Día', of: 'de', untilChange: 'hasta el cambio', epoch: 'Época', forecast: 'Próximos 3 días · calendario de la red:', stationIdle: 'Estación detenida: 0/hora', stationRate: 'Producción de la estación', perHour: '/hora', seasons: { spring: 'Primavera', summer: 'Verano', autumn: 'Otoño', winter: 'Invierno' } },
  vi: { unavailable: 'Không có dữ liệu thời tiết từ mạng', noNetwork: 'chưa có dữ liệu mạng', networkLoad: 'Tải mạng', dayAbbrev: 'ng.', day: 'Ngày', of: '/', untilChange: 'đến lần chuyển tiếp', epoch: 'Kỷ nguyên', forecast: '3 ngày tới · lịch trình trên chuỗi:', stationIdle: 'Trạm ngừng hoạt động: 0/giờ', stationRate: 'Sản lượng của trạm', perHour: '/giờ', seasons: { spring: 'Xuân', summer: 'Hạ', autumn: 'Thu', winter: 'Đông' } },
  id: { unavailable: 'Data cuaca tidak tersedia dari jaringan', noNetwork: 'tidak ada data jaringan', networkLoad: 'Beban jaringan', dayAbbrev: 'h.', day: 'Hari', of: 'dari', untilChange: 'hingga pergantian', epoch: 'Era', forecast: '3 hari ke depan · jadwal di blockchain:', stationIdle: 'Stasiun berhenti: 0/jam', stationRate: 'Produksi stasiun', perHour: '/jam', seasons: { spring: 'Musim semi', summer: 'Musim panas', autumn: 'Musim gugur', winter: 'Musim dingin' } },
  fil: { unavailable: 'Hindi makuha ang datos ng panahon sa network', noNetwork: 'walang datos sa network', networkLoad: 'Pasanin ng network', dayAbbrev: 'ar.', day: 'Araw', of: 'sa', untilChange: 'bago magpalit', epoch: 'Panahon', forecast: 'Susunod na 3 araw · iskedyul sa blockchain:', stationIdle: 'Nakahinto ang istasyon: 0/oras', stationRate: 'Produksyon ng istasyon', perHour: '/oras', seasons: { spring: 'Tagsibol', summer: 'Tag-init', autumn: 'Taglagas', winter: 'Taglamig' } },
};
