import type { Language } from './translations';

type WellCopy = {
  station: string; connectWallet: string; sourceNetwork: string; missingState: string;
  refreshing: string; refresh: string; load: string; rate: string; perHour: string;
  accumulation: string; onChain: string; networkCalculation: string; noStation: string;
  processing: string; create: string; collect: string; noLocalEstimate: string;
  loadUpdated: string; collectionSubmitted: string; failed: string;
  recorder: string; noTape: string; day: string; barograph: string; season: string;
  unknownSeason: string; noConnection: string; tapeFor: string; days: string;
  noForecast: string; today: string; seasonDay: string; flow: string;
  flowHint: string; pen: string; penHint: string;
  auto: string; motion: string; firstCall: string; villagers: string;
  emptyWindow: string; windowHours: string; rateNote: string;
  lastCollection: string; notYet: string;
  seasonNames: { spring: string; summer: string; autumn: string; winter: string };
};

export const wellCopy: Record<Language, WellCopy> = {
  ru: {
    station: 'Сетевая станция', connectWallet: 'Подключите кошелёк', sourceNetwork: 'Источник: сеть', missingState: 'WeatherState не найден. Без него программа не может рассчитать энергопоток.', refreshing: 'Обновляем…', refresh: 'Обновить нагрузку в сети', load: 'Нагрузка сети', rate: 'Скорость', perHour: '/час', accumulation: 'Накопление', onChain: 'Определяется программой', networkCalculation: 'Итоговый энергопоток считает сама сеть по времени и нагрузке; локальная оценка не показывается.', noStation: 'Станции ещё нет в сети. Первый вызов создаёт её и начинает накопление.', processing: 'Обрабатываем…', create: 'Создать сетевую станцию', collect: 'Собрать энергопоток', noLocalEstimate: 'Итог считает сама сеть: локальная оценка не показывается.', loadUpdated: 'Нагрузка сети обновлена', collectionSubmitted: 'Станция обработана; баланс обновится после подтверждения', failed: 'Операция не выполнена', recorder: 'НАГРУЗКА СЕТИ', noTape: 'ЛЕНТА НЕ ЗАПРАВЛЕНА', day: 'ДЕНЬ', barograph: 'Барограф нагрузки', season: 'сезон', unknownSeason: 'сезон неизвестен', noConnection: 'нет связи с сетью', tapeFor: 'лента на', days: 'дн.', noForecast: 'прогноза нет', today: 'Сегодня', seasonDay: 'день сезона', flow: 'Поток', flowHint: 'энергопоток в час', pen: 'Перо', penHint: 'высота записи', auto: 'Станция обновляет показания сама. Для чтения кнопка не нужна.', motion: 'Свечение — только движение. Это не выплата.', firstCall: 'Первый сбор создаёт станцию и не чеканит энергопоток.', villagers: 'Сбор требует запись игрока с жителями.', emptyWindow: 'Пустое окно не чеканит. Подождите и соберите снова.', windowHours: 'Считаются только последние 24 часа. Каждая секунда берёт погоду своего дня.', rateNote: 'Число скорости — ставка этого часа, не сумма к сбору.', lastCollection: 'Последний сбор', notYet: 'ещё не записан', seasonNames: { spring: 'Инициализация', summer: 'Обучение', autumn: 'Дообучение', winter: 'Инференс' },
  },
  en: {
    station: 'Network station', connectWallet: 'Connect your wallet', sourceNetwork: 'Source: on-chain', missingState: 'WeatherState was not found. The program cannot calculate power flow without it.', refreshing: 'Updating…', refresh: 'Update network load', load: 'Network load', rate: 'Rate', perHour: '/hour', accumulation: 'Accumulation', onChain: 'Calculated on-chain', networkCalculation: 'The network calculates the final power flow from elapsed time and load; no local estimate is shown.', noStation: 'No station was found on-chain. The first call creates it and starts accumulation.', processing: 'Processing…', create: 'Create network station', collect: 'Collect power flow', noLocalEstimate: 'The network calculates the result; no local estimate is shown.', loadUpdated: 'Network load updated', collectionSubmitted: 'Station request submitted; the balance updates after confirmation', failed: 'Operation failed', recorder: 'NETWORK LOAD', noTape: 'NO NETWORK RECORD', day: 'DAY', barograph: 'Load recorder', season: 'season', unknownSeason: 'season unknown', noConnection: 'no network connection', tapeFor: 'record for', days: 'days', noForecast: 'no forecast', today: 'Today', seasonDay: 'season day', flow: 'Flow', flowHint: 'power flow per hour', pen: 'Pen', penHint: 'trace height', auto: 'The station refreshes its reading by itself. No button is needed for the reading.', motion: 'The glow is only motion. It is not a payout.', firstCall: 'The first collection creates the station and does not mint power.', villagers: 'Collection needs a player record with villagers.', emptyWindow: 'An empty window does not mint. Wait, then collect again.', windowHours: 'Only the last 24 hours count. Each second uses the weather of that day.', rateNote: 'The rate number is the rate for this hour, not the amount waiting.', lastCollection: 'Last collection', notYet: 'not recorded yet', seasonNames: { spring: 'Initialization', summer: 'Training', autumn: 'Fine-tuning', winter: 'Inference' },
  },
  pt: {
    station: 'Estação de rede', connectWallet: 'Conecte sua carteira', sourceNetwork: 'Fonte: blockchain', missingState: 'WeatherState não encontrado. Sem ele, o programa não pode calcular o fluxo de energia.', refreshing: 'Atualizando…', refresh: 'Atualizar carga da rede', load: 'Carga da rede', rate: 'Taxa', perHour: '/hora', accumulation: 'Acúmulo', onChain: 'Calculado na rede', networkCalculation: 'A rede calcula o fluxo final com base no tempo e na carga; nenhuma estimativa local é exibida.', noStation: 'Ainda não há estação na rede. A primeira operação cria a estação e inicia o acúmulo.', processing: 'Processando…', create: 'Criar estação de rede', collect: 'Coletar fluxo de energia', noLocalEstimate: 'A rede calcula o resultado; nenhuma estimativa local é exibida.', loadUpdated: 'Carga da rede atualizada', collectionSubmitted: 'Operação enviada; o saldo será atualizado após a confirmação', failed: 'A operação falhou', recorder: 'CARGA DA REDE', noTape: 'SEM REGISTRO DA REDE', day: 'DIA', barograph: 'Registro de carga', season: 'fase', unknownSeason: 'fase desconhecida', noConnection: 'sem conexão com a rede', tapeFor: 'registro de', days: 'dias', noForecast: 'sem previsão', today: 'Hoje', seasonDay: 'dia da fase', flow: 'Fluxo', flowHint: 'fluxo de energia por hora', pen: 'Pena', penHint: 'altura do traçado', auto: 'A estação atualiza a leitura sozinha. Nenhum botão é necessário para a leitura.', motion: 'O brilho é apenas movimento. Não é um pagamento.', firstCall: 'A primeira coleta cria a estação e não cunha energia.', villagers: 'A coleta exige um registro de jogador com habitantes.', emptyWindow: 'Uma janela vazia não cunha. Espere e colete de novo.', windowHours: 'Só contam as últimas 24 horas. Cada segundo usa o clima do próprio dia.', rateNote: 'O número da taxa é a taxa desta hora, não o valor à espera.', lastCollection: 'Última coleta', notYet: 'ainda não registrado', seasonNames: { spring: 'Inicialização', summer: 'Treinamento', autumn: 'Ajuste fino', winter: 'Inferência' },
  },
  es: {
    station: 'Estación de red', connectWallet: 'Conecta tu cartera', sourceNetwork: 'Fuente: cadena', missingState: 'No se encontró WeatherState. Sin él, el programa no puede calcular el flujo de energía.', refreshing: 'Actualizando…', refresh: 'Actualizar carga de la red', load: 'Carga de la red', rate: 'Ritmo', perHour: '/hora', accumulation: 'Acumulación', onChain: 'Calculado en la red', networkCalculation: 'La red calcula el flujo final según el tiempo y la carga; no se muestra ninguna estimación local.', noStation: 'Aún no hay estación en la red. La primera operación la crea e inicia la acumulación.', processing: 'Procesando…', create: 'Crear estación de red', collect: 'Recoger flujo de energía', noLocalEstimate: 'La red calcula el resultado; no se muestra ninguna estimación local.', loadUpdated: 'Carga de la red actualizada', collectionSubmitted: 'Operación enviada; el saldo se actualizará después de la confirmación', failed: 'La operación falló', recorder: 'CARGA DE LA RED', noTape: 'SIN REGISTRO DE RED', day: 'DÍA', barograph: 'Registrador de carga', season: 'fase', unknownSeason: 'fase desconocida', noConnection: 'sin conexión con la red', tapeFor: 'registro de', days: 'días', noForecast: 'sin pronóstico', today: 'Hoy', seasonDay: 'día de la fase', flow: 'Flujo', flowHint: 'flujo de energía por hora', pen: 'Pluma', penHint: 'altura del registro', auto: 'La estación actualiza la lectura sola. No hace falta un botón para la lectura.', motion: 'El brillo es solo movimiento. No es un pago.', firstCall: 'La primera recolección crea la estación y no acuña energía.', villagers: 'La recolección exige un registro de jugador con habitantes.', emptyWindow: 'Una ventana vacía no acuña. Espere y recoja de nuevo.', windowHours: 'Solo cuentan las últimas 24 horas. Cada segundo usa el clima de su propio día.', rateNote: 'El número del ritmo es el ritmo de esta hora, no la cantidad en espera.', lastCollection: 'Última recolección', notYet: 'aún no registrado', seasonNames: { spring: 'Inicialización', summer: 'Entrenamiento', autumn: 'Ajuste fino', winter: 'Inferencia' },
  },
  vi: {
    station: 'Trạm mạng', connectWallet: 'Kết nối ví của bạn', sourceNetwork: 'Nguồn: blockchain', missingState: 'Không tìm thấy WeatherState. Thiếu dữ liệu này, chương trình không thể tính dòng năng lượng.', refreshing: 'Đang cập nhật…', refresh: 'Cập nhật tải mạng', load: 'Tải mạng', rate: 'Tốc độ', perHour: '/giờ', accumulation: 'Tích lũy', onChain: 'Do mạng tính toán', networkCalculation: 'Mạng tính dòng năng lượng thực tế theo thời gian và tải; không hiển thị số liệu ước tính cục bộ.', noStation: 'Chưa có trạm trên chuỗi. Lần gọi đầu tiên sẽ tạo trạm và bắt đầu tích lũy.', processing: 'Đang xử lý…', create: 'Tạo trạm mạng', collect: 'Thu dòng năng lượng', noLocalEstimate: 'Mạng tính kết quả; không hiển thị số liệu ước tính cục bộ.', loadUpdated: 'Đã cập nhật tải mạng', collectionSubmitted: 'Đã gửi yêu cầu cho trạm; số dư sẽ cập nhật sau khi xác nhận', failed: 'Thao tác thất bại', recorder: 'TẢI MẠNG', noTape: 'CHƯA CÓ DỮ LIỆU MẠNG', day: 'NGÀY', barograph: 'Máy ghi tải mạng', season: 'giai đoạn', unknownSeason: 'chưa rõ giai đoạn', noConnection: 'không có kết nối mạng', tapeFor: 'ghi dữ liệu', days: 'ngày', noForecast: 'chưa có dự báo', today: 'Hôm nay', seasonDay: 'ngày của giai đoạn', flow: 'Dòng', flowHint: 'dòng năng lượng mỗi giờ', pen: 'Bút', penHint: 'độ cao nét ghi', auto: 'Trạm tự làm mới số liệu. Không cần nút để đọc.', motion: 'Ánh sáng chỉ là chuyển động. Đó không phải khoản trả.', firstCall: 'Lần thu đầu tạo trạm và không đúc năng lượng.', villagers: 'Việc thu cần hồ sơ người chơi có dân.', emptyWindow: 'Cửa sổ trống không đúc. Hãy đợi rồi thu lại.', windowHours: 'Chỉ 24 giờ gần nhất được tính. Mỗi giây dùng thời tiết của ngày đó.', rateNote: 'Con số tốc độ là tốc độ giờ này, không phải số đang chờ.', lastCollection: 'Lần thu gần nhất', notYet: 'chưa ghi', seasonNames: { spring: 'Khởi tạo', summer: 'Huấn luyện', autumn: 'Tinh chỉnh', winter: 'Suy luận' },
  },
  id: {
    station: 'Stasiun jaringan', connectWallet: 'Hubungkan dompetmu', sourceNetwork: 'Sumber: blockchain', missingState: 'WeatherState tidak ditemukan. Program tidak dapat menghitung aliran daya tanpanya.', refreshing: 'Memperbarui…', refresh: 'Perbarui beban jaringan', load: 'Beban jaringan', rate: 'Laju', perHour: '/jam', accumulation: 'Akumulasi', onChain: 'Dihitung di blockchain', networkCalculation: 'Jaringan menghitung aliran daya akhir berdasarkan waktu dan beban; perkiraan lokal tidak ditampilkan.', noStation: 'Stasiun belum ada di blockchain. Tindakan pertama membuatnya dan memulai akumulasi.', processing: 'Memproses…', create: 'Buat stasiun jaringan', collect: 'Ambil aliran daya', noLocalEstimate: 'Jaringan menghitung hasilnya; perkiraan lokal tidak ditampilkan.', loadUpdated: 'Beban jaringan diperbarui', collectionSubmitted: 'Permintaan stasiun terkirim; saldo diperbarui setelah konfirmasi', failed: 'Tindakan gagal', recorder: 'BEBAN JARINGAN', noTape: 'BELUM ADA CATATAN JARINGAN', day: 'HARI', barograph: 'Perekam beban', season: 'fase', unknownSeason: 'fase belum diketahui', noConnection: 'tidak terhubung ke jaringan', tapeFor: 'catatan untuk', days: 'hari', noForecast: 'belum ada prakiraan', today: 'Hari ini', seasonDay: 'hari dalam fase', flow: 'Aliran', flowHint: 'aliran daya per jam', pen: 'Pena', penHint: 'ketinggian jejak', auto: 'Stasiun memperbarui bacaan sendiri. Tidak perlu tombol untuk membaca.', motion: 'Cahaya hanya gerakan. Itu bukan pembayaran.', firstCall: 'Pengambilan pertama membuat stasiun dan tidak mencetak daya.', villagers: 'Pengambilan butuh catatan pemain dengan penduduk.', emptyWindow: 'Jendela kosong tidak mencetak. Tunggu, lalu ambil lagi.', windowHours: 'Hanya 24 jam terakhir yang dihitung. Setiap detik memakai cuaca harinya sendiri.', rateNote: 'Angka laju adalah laju jam ini, bukan jumlah yang menunggu.', lastCollection: 'Pengambilan terakhir', notYet: 'belum tercatat', seasonNames: { spring: 'Inisialisasi', summer: 'Pelatihan', autumn: 'Penyempurnaan', winter: 'Inferensi' },
  },
  fil: {
    station: 'Istasyon ng network', connectWallet: 'Ikonekta ang wallet', sourceNetwork: 'Pinagmulan: blockchain', missingState: 'Hindi makita ang WeatherState. Kung wala ito, hindi makakalkula ng programa ang daloy ng enerhiya.', refreshing: 'Ina-update…', refresh: 'I-update ang pasan ng network', load: 'Pasanin ng network', rate: 'Bilis', perHour: '/oras', accumulation: 'Pag-iipon', onChain: 'Kinakalkula sa blockchain', networkCalculation: 'Kinakalkula ng network ang huling daloy ayon sa oras at pasan; walang lokal na pagtatayang ipinapakita.', noStation: 'Wala pang istasyon sa blockchain. Lilikhain ito ng unang transaksiyon at sisimulan ang pag-iipon.', processing: 'Pinoproseso…', create: 'Lumikha ng istasyon ng network', collect: 'Kunin ang daloy ng enerhiya', noLocalEstimate: 'Kinakalkula ng network ang resulta; walang lokal na pagtatayang ipinapakita.', loadUpdated: 'Na-update ang pasan ng network', collectionSubmitted: 'Naipadala ang kahilingan; maa-update ang balanse pagkatapos makumpirma', failed: 'Nabigo ang gawain', recorder: 'PASANIN NG NETWORK', noTape: 'WALA PANG TALA SA NETWORK', day: 'ARAW', barograph: 'Tagapagtala ng pasan', season: 'yugto', unknownSeason: 'hindi pa alam ang yugto', noConnection: 'walang koneksiyon sa network', tapeFor: 'tala para sa', days: 'araw', noForecast: 'walang tantiya', today: 'Ngayon', seasonDay: 'araw ng yugto', flow: 'Daloy', flowHint: 'daloy ng enerhiya kada oras', pen: 'Panulat', penHint: 'taas ng guhit', auto: 'Ang istasyon ang nagre-refresh ng tala. Hindi kailangan ng pindutan para sa pagbasa.', motion: 'Ang liwanag ay galaw lamang. Hindi ito bayad.', firstCall: 'Ang unang pagkuha ay lumilikha ng istasyon at hindi nagmi-mint ng enerhiya.', villagers: 'Ang pagkuha ay kailangan ng tala ng manlalaro na may mga naninirahan.', emptyWindow: 'Ang walang laman na bintana ay hindi nagmi-mint. Maghintay, saka kunin muli.', windowHours: 'Ang huling 24 oras lamang ang binibilang. Bawat segundo ay gumagamit ng panahon ng sarili nitong araw.', rateNote: 'Ang bilang ng bilis ay bilis ng oras na ito, hindi ang halagang naghihintay.', lastCollection: 'Huling pagkuha', notYet: 'hindi pa naitala', seasonNames: { spring: 'Pagsisimula', summer: 'Pagsasanay', autumn: 'Pagpino', winter: 'Paghihinuha' },
  },
};
